### PR TITLE
update text based emotion detection

### PR DESCRIPTION
**Pull request by Balaji91221**
# Project-Guidance! 🎊🎈

### Welcome! 🎉

Thank you for visiting our repository! We're excited to have you here. If you find this project useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔

- [] YES
- [x] NO

### 📝 Description

This proposal introduces a **Text-Based Emotion Detection** feature to Project-Guidance. The feature will involve preprocessing text, building a classifier to detect emotions from text, and an interactive interface for users to view results. This addition aims to enhance the project's scope and usability.

### 🔧 Fixes #issue_no

*(Provide the specific issue number here if applicable)*

### 🏷️ Initiative Participation

This pull request is associated with the following initiative:

- [x] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [x] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Comment by Kushal997-das** [comment]
@Balaji91221 KIndly mentio issue number.

**Comment by Balaji91221** [comment]
> @Balaji91221 KIndly mentio issue number.

This is not a issue I have added the project

**Comment by Kushal997-das** [comment]
@Balaji91221 You have to follow this [guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)

**Comment by Balaji91221** [comment]
> @Balaji91221 You have to follow this [guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)


 Hi @Kushal997-das ,

I understand that the mentor of GSSoC is currently reviewing the project. I have followed the process:

1. Raised an issue (step 1).


2. My project is currently under review (step 2).



However, the review is taking longer than expected. Since there was no update, I went ahead and created a pull request. I apologize for any confusion caused by this.

**Pull request closed without merging**
