### PR TITLE
Music Download

### LINKED ISSUE #707: Music Downloader (python)
### Is your feature request related to a problem? Please describe.

Download music

### Describe the solution you'd like.

uploading...

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by DragonUncaged**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #707 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by DragonUncaged** [comment]
i have been assigned the issue. atleast accept the previously assigned pr

**Comment by Kushal997-das** [comment]
WE already mentioned in the discord itself 28th was the last to to submit the PR.

**Comment by Kushal997-das** [comment]
https://discord.com/channels/927533015364677672/947486594858893312/977116075760173077

**Comment by DragonUncaged** [comment]
https://github.com/Kushal997-das/Project-Guidance/issues/361#issuecomment-1140380741

**Comment by Kushal997-das** [comment]
> [#361 (comment)](https://github.com/Kushal997-das/Project-Guidance/issues/361#issuecomment-1140380741)
> 
> You said here today is the last day. I did not see in discord. I saw in github
> 
> image

This one only for one person she had exam so requested me to extend this message was not for everyone ,moreover as a GSSOC participant you should active on discord .

**Comment by Kushal997-das** [comment]
https://discord.com/channels/927533015364677672/947486594858893312/977116075760173077

@DragonUncaged

**Comment by Kushal997-das** [comment]
We have already pending PR so not possible to reopen this we already mentioned 28th was the last date . thanks

**Comment by DragonUncaged** [comment]
> We have already pending PR so not possible to reopen this we already mentioned 28th was the last date . thanks

okay okay..

**Pull request closed without merging**
