### PR TITLE
Admission Prediction Using Machine Learning

### LINKED ISSUE #492: Title:  To Add Admission Prediction Project Using ML
### Is your feature request related to a problem? Please describe.

There are many a times people are unaware about whether they are eligible for the admission or not base don their past performance so i came up with a solution to predict their chance of admission .

### Describe the solution you'd like.

I have made an admission prediction project based on different parameter entry. I would like to add it under machine learning and data science section.

### Describe alternatives you've considered.

nan

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by AyushJain001**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

Made machine learning basic project to predict the chances of admission in university based on parameter givenl

Fixes #492 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by AyushJain001** [comment]
Kindly review my work and suggest valuable feedback if any.

**Review by photon149 — COMMENTED** [review]
@AyushJain001 Please check that your image isn't loading in the jupyter notebook
image
There are 2 occurences like this , correct both of them.

**Comment by AyushJain001** [comment]
> @AyushJain001 Please check that your image isn't loading in the jupyter notebook image There are 2 occurences like this , correct both of them.

I have corrected/edited all the images that was not showing.

**Review by photon149 — CHANGES_REQUESTED** [review]
@AyushJain001 Okay , so the code and content wise it's fine , but the README file you have created doesn't relates to the work you have done in your jupyter notebook.
Since , you have mentioned about Linear Regression , but since you have used 2 other methods & regularizations please mention accordingly what you have done in your README file.

**Comment by AyushJain001** [comment]
> @AyushJain001 Okay , so the code and content wise it's fine , but the README file you have created doesn't relates to the work you have done in your jupyter notebook. Since , you have mentioned about Linear Regression , but since you have used 2 other methods & regularizations please mention accordingly what you have done in your README file.

I have updated the README file according to the work I implemented.

**Review by photon149 — APPROVED** [review]
@AyushJain001 great 👍🏻 
No Duplicity ✔️ 
@Kushal997-das @prakhar3062 have a look

**Review by prakhar3062 — APPROVED** [review]

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
