### PR TITLE
Added Form Validation to Basic Web Development

### PR DESCRIPTION
**Pull request by kriti242**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description
This form validation program performs form fields validation in real time i.e., when the user is entering the details. 

Fixes https://github.com/Kushal997-das/Project-Guidance/issues/241

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue https://github.com/Kushal997-das/Project-Guidance/issues/241

### CODE REVIEW

**Review by photon149 — CHANGES_REQUESTED** [review]
@kriti242 Please put a validation for registering only when all the details are filled.
image

**Comment by kriti242** [comment]
> @kriti242 Please put a validation for registering only when all the details are filled. image

Ok

**Review by photon149 — APPROVED** [review]
Looks Good
@Kushal997-das @prakhar3062 have a look.

**Review by prakhar3062 — APPROVED** [review]
okay from my side

**Review by Kushal997-das — APPROVED** [review]
@kriti242 Good 👍

**Pull request merged**
