### PR TITLE
EDA on Netflix Data

### PR DESCRIPTION
**Pull request by ABHIGPT401**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)
EDA on Netflix data

Fixes #issue_no
#298 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by photon149** [comment]
@ABHIGPT401 please follow contributing guidelines while making a PR.
Add the issue number to which the particular PR relates

**Comment by ABHIGPT401** [comment]
> @ABHIGPT401 please follow contributing guidelines while making a PR. Add the issue number to which the particular PR relates

#298

**Review by photon149 — CHANGES_REQUESTED** [review]
@ABHIGPT401 Please attach a README file to your project giving a brief description of the project along side outputs.

**Comment by ABHIGPT401** [comment]
Okay

**Comment by ABHIGPT401** [comment]
Done

**Comment by photon149** [comment]
@ABHIGPT401 Great Visualizations 👍🏻 
Just one minor addition , add all the accuracy scores of the various models applied in a tabular format in your README file.
@prakhar3062 you can take a look , everything else looks good to me.

**Comment by photon149** [comment]
@ABHIGPT401 You have added the same file twice , you have to  delete one file within the Ionosphere dataset.
Also , you have to create a new folder named "EDA on Netflix Data " under the Machine Learning folder under "Basic" category.
There you have to upload your .ipynb file as well as README file.
Apart from that , your README file needs to be more elaborated , you can add a brief about your project .

**Comment by ABHIGPT401** [comment]
Done. Please Check and Sirs, I request you to please give the Gssoc'22 Badge

**Review by photon149 — COMMENTED** [review]
@ABHIGPT401 Everything looks great , however if you add comments in your Jupyter notebook that would enhance code readability.
Do this change and revert.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@ABHIGPT401 Add a small gif or may be photos of your output in `readme.md` file .

**Comment by ABHIGPT401** [comment]
Done Sir.  Please check.

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
