### PR TITLE
added_CurrencyConverter_app

### LINKED ISSUE #451: Title: Add a Currency Converter App
### Is your feature request related to a problem? Please describe.

I have made a very user friendly Currency Converter App.

### Describe the solution you'd like.

Live - https://priyanshu688.github.io/Currency_Converter/

### Describe alternatives you've considered.

This is built using Java language.

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by priyanshu688**
I have added the Currency Converter App in the Intermediate level project.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Yes.)

### Description

(Added Currency Converter App)

Fixes #451

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Comment by priyanshu688** [comment]
@Kushal997-das Kindly review and merge this PR.

**Comment by photon149** [comment]
@priyanshu688 Please attach a README file to your project.

**Comment by priyanshu688** [comment]
@photon149 Okh

**Review by photon149 — CHANGES_REQUESTED** [review]
@priyanshu688 Kindly add content to your README file.
- Working of the Application
- Output SS/GIF of the app
- How to run the app (steps and necessary modules)

**Comment by Kushal997-das** [comment]
@priyanshu688 Do the requires changes ASAP else we will close this .

**Comment by priyanshu688** [comment]
@Kushal997-das Yeah sure.. I am doing this

**Review by photon149 — COMMENTED** [review]
@priyanshu688 Just  some minor additions :
- Add a OUTPUT ss as well in your README
- Remove any unnecessary Files
No Duplicity ✅

**Review by prakhar3062 — APPROVED** [review]
Add More points in readme like tech stack demo video/live you can see other pr for reference

**Comment by Kushal997-das** [comment]
@priyanshu688 It's been more than 15days but you didn't response so this PR gonna closed . Thanks .

**Pull request closed without merging**
