### PR TITLE
changes

### LINKED ISSUE #1314: Title: Can add logo and favicon.
### Is your feature request related to a problem? Please describe.

The website lacks a logo and favicon, affecting project visibility. Adding these features will enhance professionalism and user recognition. Implementing them will improve the overall site appearance and user experience. 

### Describe the solution you'd like.

I would like to add a new logo and favicon to enhance the project’s visual identity and overall presentation. This update will improve the project's appearance and visibility, contributing to a more professional and recognizable site.

### Describe alternatives you've considered.

Adding a new logo and favicon directly offers the best fit for unique branding, providing the necessary customization and alignment with the project’s needs.

### Add any other context or screenshots about the feature request here.

Screenshot 2024-07-25 212344

### PR DESCRIPTION
**Pull request by sweta-singh28**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

Added a logo and favicon.

Fixes #1314

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@sweta-singh28 Could you please deploy the project and send me the link? I'd like to see how it looks.

**Comment by sweta-singh28** [comment]
> @sweta-singh28 Could you please deploy the project and send me the link? I'd like to see how it looks.

 @Kushal997-das sir,    https://project-guidance-blush.vercel.app/

**Review by Kushal997-das — APPROVED** [review]

**Comment by sweta-singh28** [comment]
@Kushal997-das sir,  please review and merge this pr as gssoc would not count this pr if merged after 31st July 11:59 pm
It's my humble request sir to review and merge this pr asap!.

**Comment by Kushal997-das** [comment]
> @Kushal997-das sir, please review and merge this pr as gssoc would not count this pr if merged after 31st July 11:59 pm It's my humble request sir to review and merge this pr asap!.

Done

**Pull request merged**
