### PR TITLE
please add tic tac toe using c++

### LINKED ISSUE #307: TIC-TAC-TOE game using C++
This is a beginner level project using C++ programming. I am a Gssoc'22 participant. please assign me this issue.

### PR DESCRIPTION
**Pull request by gaurijoshi22**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

yes

### Description

(Write your answer here.)

Fixes #307 
[tic tac toe c++.txt](https://github.com/Kushal997-das/Project-Guidance/files/8229602/tic.tac.toe.c%2B%2B.txt)
https://github.com/gaurijoshi22/tic-tac-toe-using-C-.git

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by photon149 — CHANGES_REQUESTED** [review]
@gaurijoshi22 Please remove unwanted files.

**Comment by Kushal997-das** [comment]
@gaurijoshi22 Why you are spamming i said again and again then don't send PR with multiple files you are doing same mistake again and again , You are not allowed to send any PR to this REPO .

**Comment by gaurijoshi22** [comment]
@Kushal997-das I am a beginner I don't know how to submit project

**Comment by Kushal997-das** [comment]
@gaurijoshi22 https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md 

Go through this for reference !!

**Pull request closed without merging**
