### PR TITLE
added hackathon tracker

### LINKED ISSUE #1364: Title: Add hackathon tracker
### Is your feature request related to a problem? Please describe.

willing to add hackathon tracker under web dev projects

### Describe the solution you'd like.

working video
https://github.com/user-attachments/assets/d53dc8f9-2b76-4b4a-95df-06604411c1a4

### Describe alternatives you've considered.

n/a

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by ananyag309**
solved #1364 

pl

https://github.com/user-attachments/assets/df75b15b-e742-46bd-99f7-6899a57160db

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 

added hackathon tracker to web development project

### 🏷️ Initiative Participation *(Required)*

This pull request is associated with the following initiative. Please choose the one you are contributing to:

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Comment by ananyag309** [comment]
@Kushal997-das please check and merge it

**Comment by ananyag309** [comment]
@Kushal997-das sir please review and merge it as i need to raise 1 more pr

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@ananyag309 

Hello, here are the changes you need to make:

1. Please fetch the repository and make the necessary updates.
2. Ensure that you add the screenshots in the readme.md file [here](https://github.com/ananyag309/Project-Guidance/blob/main/Web%20Development/Intermediate/Hackathon%20Tracker/README.md).
3. Add comments in the code lines.

**Comment by ananyag309** [comment]
@Kushal997-das made necessary changes - sync the repo, added comments and screenshot. please check

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Hi @ananyag309,

Could you please deploy the project and add the live link to the `README.md` file? This will help users easily access and check the project.

Thank you!

**Comment by ananyag309** [comment]
@Kushal997-das how to deploy ? can you tell what exactly i need to do

**Comment by Kushal997-das** [comment]
> Could you please deploy the project and add the live link to the `README.md` file? This will help users easily access and check the project.
> 
> Thank you!

You don't know what is deploy ? I want you to deploy (Host your project) so that we can see the website easily.

**Comment by ananyag309** [comment]
@Kushal997-das added the live deployment

**Comment by ananyag309** [comment]
@Kushal997-das i hope i have fixed everything correct now, please check and merge. also sorry for the inconvenience caused.

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
