### PR TITLE
Added color code converter webpage files

### LINKED ISSUE #302: Color Code Converter
## 🚀 Feature

Color Code Converter is a web page that converts from and to different color codes such as RGB, CMYK, Hsl, & Hex.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

- [x] Yes

## Motivation

A nice project to get one's hands dirty with solid JS principles such as functions and variables scope. It's also a good tool to convert between different color codes on haste.

## Pitch

It's an on-the-go project that converts between color code formats on haste with accurate values.

Issue created under GSSoC'22 contributions

### PR DESCRIPTION
**Pull request by XZANATOL**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

- [x] Yes

### Description

Added color code converter that converts between RGB, Hex, CMYK & Hsl.

Fixes #302 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #302 
PR made under GSSoC'22 contributions

### CODE REVIEW

**Comment by XZANATOL** [comment]
@Kushal997-das any updates about the PR review?

**Review by photon149 — APPROVED** [review]
Looks good to me.
@Kushal997-das  @prakhar3062 Have a look.

**Review by prakhar3062 — APPROVED** [review]
works fine @Kushal997-das

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@XZANATOL LGTM 👍 

One change requires-
Your project should under basic section . 

Web Development/Basic/Color_Code_Converter/

**Comment by XZANATOL** [comment]
@Kushal997-das Done.

**Review by Kushal997-das — APPROVED** [review]
@XZANATOL Great work !

**Pull request merged**
