### PR TITLE
Web Dev README Updated

### PR DESCRIPTION
**Pull request by JohnWesleyK**
Updated Web Developement README coresponding to this [issue](https://github.com/Kushal997-das/Project-Guidance/issues/78)

### CODE REVIEW

**Comment by TawfikYasser** [comment]
> Updated Web Developement README coresponding to this [issue](https://github.com/Kushal997-das/Project-Guidance/issues/78)

Great work @JohnWesleyK

**Comment by JohnWesleyK** [comment]
Cheers @TawfikYasser !!

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@JohnWesleyK Great job but no Need to add gif as many contributor didn't add the gif of their project Stay with project and and their respective links in attractive manner.

**Comment by JohnWesleyK** [comment]
@Kushal997-das So should I remove Gifs and images then ?

**Comment by SamarpanCoder2002** [comment]
> @Kushal997-das So should I remove Gifs and images then ?

Yeah....please remove it according to @Kushal997-das

**Comment by JohnWesleyK** [comment]
@SamarpanCoder2002 @Kushal997-das does this seem ok ?

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Add the projects name with hyper link don't use bold. Moreover don't use too much animation like flowers keep this simple.

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 @Kushal997-das does this seem ok ?

Please add hyperlink with hotel management project under advanced in web development....

**Comment by JohnWesleyK** [comment]
@SamarpanCoder2002 I seem to be having this in the MD file, but the hyperlink is'nt working for some reason
`- [<h3>Hotel Reservation System</h3>](https://github.com/Kushal997-das/Project-Guidance/tree/main/Web%20Development/Advanced/Hotel%20Reservation%20System)</br>`

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Great job @JohnWesleyK Please add the hyperlink in under advance. And yeah please fetch the repo and send PR

**Comment by JohnWesleyK** [comment]
The Hyperlink doesn't seem to be rendering for some reason, so should I close this and create a new PR @Kushal997-das ?

**Comment by TawfikYasser** [comment]
@JohnWesleyK  If you still have a problem try this command: 

`Name`

**Comment by JohnWesleyK** [comment]
> @JohnWesleyK If you still have a problem try this command:
> 
> `Name`

tried doing that, still doesn't seem to be working :( @TawfikYasser

**Comment by Kushal997-das** [comment]
> > @JohnWesleyK If you still have a problem try this command:
> > `Name`
> 
> tried doing that, still doesn't seem to be working :( @TawfikYasser

Okey @JohnWesleyK I'll merge I gonna fixed this make sure you fetch the repo first.

**Comment by SamarpanCoder2002** [comment]
> > > @JohnWesleyK If you still have a problem try this command:
> > > `Name`
> > 
> > 
> > tried doing that, still doesn't seem to be working :( @TawfikYasser
> 
> Okey @JohnWesleyK I'll merge I gonna fixed this make sure you fetch the repo first.

Yeah...first fetch it @JohnWesleyK

**Comment by JohnWesleyK** [comment]
I think I have fetched it now @SamarpanCoder2002

**Comment by Kushal997-das** [comment]
> I think I have fetched it now @SamarpanCoder2002

@JohnWesleyK 14 commits behind the original repo . Please fetch then send PR.

**Review by SamarpanCoder2002 — CHANGES_REQUESTED** [review]
Not at all..you are 14 commit  behind of main repo...please fetch it at first..
```bash
git fetch upstream
get merge upstream/main main
git push
```

**Comment by JohnWesleyK** [comment]
I think the fetch was successful now

**Review by SamarpanCoder2002 — COMMENTED** [review]
Thanks for your contribution....

**Pull request merged**
