### PR TITLE
Added SMS-Classification

### PR DESCRIPTION
**Pull request by Avishek8136**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes.

### Description

I have read all the guidelines and followed them. 

Fixes #issue_no
#983 

### Checklist

- [✔️ ] I've read the contribution guidelines.
- [ ✔️] I've checked the issue list before deciding what to submit.
- [✔️ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

N/A

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Avishek8136 You been created PR in under basic and intermediate , kindly add under basic and remove it from intermediate.

**Comment by Avishek8136** [comment]
Ok i will do it by evening. Sorry

**Comment by Avishek8136** [comment]
Have completed

**Comment by Avishek8136** [comment]
Requesting you to check it once

**Comment by Avishek8136** [comment]
Sorry i created another pull request, I have completed my work

**Comment by Avishek8136** [comment]
Added SMS Classification in Basic

**Pull request closed without merging**
