### PR TITLE
Single Neural Network

### LINKED ISSUE #380: Add a single neural network program
### Is your feature request related to a problem? Please describe.

Add a single neural network program which is not back feeded.

### Describe the solution you'd like.

Add a single neural network program which is not back feeded

### Describe alternatives you've considered.

Add a single neural network program which is not back feeded

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by ABHIGPT401**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.) 
Yes
### Description

(Write your answer here.)
This is a program that shows the single layer neural network.
Fixes #380

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by ABHIGPT401** [comment]
Done sir please check

**Review by Kushal997-das — APPROVED** [review]
@ABHIGPT401 
LGTM 👍 
@photon149 check !!!

**Review by photon149 — APPROVED** [review]
Approved from my end.
@prakhar3062 have a look.

**Review by prakhar3062 — APPROVED** [review]
okay from my side also

**Pull request merged**
