### PR TITLE
Shopping List Project

### PR DESCRIPTION
**Pull request by TawfikYasser**
Hi,

This PR to add the Shopping List Project to the following path:

/Desktop Application/Basic/C++/Shopping List

Project description in the README file

Assigned with issue #46 

I hope my contributions helps the beginner developers.

I will add more projects soon.

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Delete .exe file and your file extension are not proper.

**Comment by TawfikYasser** [comment]
> Delete .exe file and your file extension are not proper.

Okay I deleted them.

**Review by Kushal997-das — APPROVED** [review]
Looks good to me:)

**Comment by TawfikYasser** [comment]
Thanks

**Pull request merged**
