### PR TITLE
Budgeting Website

### LINKED ISSUE #274: Budgeting App
## 🚀 Feature

Budgeting app - A all in one solution to all your financial problems

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes I have gone through the CONTRIBUTING.md file .

## Motivation

We often ignore our expenditure in the starting of the month and end up spending more than we were supposed to . So this app will be a solution to this problem and will help us in planning our monthly expense.

## Pitch

This app will help people in becoming their own financial advisor and stop them from spending on unnecessary goods by giving them a complete foresight of how much money they are spending on different stuffs and what will be their leftover balance in the end of the month with their current expenditure rate.

After this , it will calculate the amount of money they can spend on different things (such as food , savings , entertainment , travel etc) in a tabular manner.

In the end this will also give them a PRO-TIP based on their expense so that manage their finance more efficiently in the future.

Issue made under GSSoC'22 contributions.

### PR DESCRIPTION
**Pull request by Kunal0220**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes I have read the Contributing Guidelines.

### Description

1.  This is a simple budget app which takes your monthly salary as input and your expenditure (in %) for different things.
2. Once we click on calculate , It will show a table with the amount of money you can spend on each item.
3. It will give an error if people spend more than they earn.

Fixes #274 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #274 

[Contribution made under GSSoC 22']

### CODE REVIEW

**Comment by Kunal0220** [comment]
https://user-images.githubusercontent.com/71934168/161367919-dd54aa18-c130-40f1-99bc-4d2cf43df827.mp4

**Comment by Kunal0220** [comment]
Video Walkthrough of how the website works!

**Review by photon149 — APPROVED** [review]
Great Project @Kunal0220 
@Kushal997-das Please have a look approved from my end.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Kunal0220 Delete both  `.DS_Store` .

**Comment by Kunal0220** [comment]
On it . 🙌🏻

**Comment by Kunal0220** [comment]
Hey @Kushal997-das , I am facing some problem while deleting the .DS_Store file , It's not appearing in my folders . I remember trying to correct it even in a previous PR under GSSoC itself in an organisation named Ace-The-Frontend (
here is the [link](https://github.com/surajm-333/Ace-The-FrontEnd/pull/240/commits/ef52f9926f6ee003eb69661c69d1c9179e4f346f) for the same .) 

Can you guide me on how to fix it ? Or should I raise a new PR ?

**Comment by Kushal997-das** [comment]
@Kunal0220 please raise a new one .

**Comment by Kunal0220** [comment]
Ok Sir

**Pull request closed without merging**
