### PR TITLE
Added Vaccination Centre Locator

### LINKED ISSUE #237: Vaccination Centre Locator
## 🚀 Feature

A python project that helps users locate nearby COVID vaccination centres by providing their location data as input.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

## Motivation

A major problem that people face nowadays is finding a vaccination centre. An ample number of people have not been vaccinated yet just because they don't know where the centre is. Through this project, I have tried to solve this problem.

## Pitch

This program not only gives the location of the vaccination centre as output but also gives all the information about the vaccine, like which vaccine is available, which dose is available and the schedule (date and time) of vaccination.

### PR DESCRIPTION
**Pull request by lovishprabhakar**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)?

Yes

### Description

Added Vaccination centre locator using python in the intermediate folder of Internet Of Things.

Fixes #237 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #237

### CODE REVIEW

**Review by photon149 — CHANGES_REQUESTED** [review]
@lovishprabhakar  Please add a README file to explain your project in brief with Output Screenshots attached.

**Comment by lovishprabhakar** [comment]
> @lovishprabhakar Please add a README file to explain your project in brief with Output Screenshots attached.

done sir. @Kushal997-das

**Review by photon149 — APPROVED** [review]
Looks good to me.
@prakhar3062 , have a look.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@lovishprabhakar how this project comes under IOT ? This project should comes under this [Folder](https://github.com/lovishprabhakar/Project-Guidance/tree/main/Desktop%20Application/Basic/Python)

**Comment by Kushal997-das** [comment]
> Looks good to me. @prakhar3062 , have a look.

Please check first whether the project belong to appropriate folder or not .

**Comment by lovishprabhakar** [comment]
@Kushal997-das done sir. Shifted the project to the instructed folder.

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
