### PR TITLE
added organization event management system under GSSOC2022

### LINKED ISSUE #485: Title:  Organization event management system
### Is your proposal related to a problem? Please describe.

This is an web development project which helps an organization to manage the committee, committee members, events, and to manage the meeting rooms and provide the food facility to the attendees of the event. And the committee members can view the events allotted to them and attend the events.

### PR DESCRIPTION
**Pull request by jyothi-k-g**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

yes

### Description

added event management system

Fixes #485 

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by photon149 — CHANGES_REQUESTED** [review]
@jyothi-k-g Please remove unnecesssary files.

**Comment by jyothi-k-g** [comment]
done @Kushal997-das

**Review by photon149 — COMMENTED** [review]
Looks good to me.
No Duplicity ✔️ 
@Kushal997-das Please review once and  recheck the path once as well.

**Review by Kushal997-das — APPROVED** [review]
@jyothi-k-g Great work 💯

**Comment by Kushal997-das** [comment]
> Looks good to me. No Duplicity ✔️ @Kushal997-das Please review once and recheck the path once as well.

Everything is looks correct please approve it @photon149

**Comment by Kushal997-das** [comment]
@prakhar3062 have a look .

**Review by photon149 — APPROVED** [review]
Approved from my end.

**Review by prakhar3062 — APPROVED** [review]

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
