### PR TITLE
Added text to speech application

### LINKED ISSUE #604: Text to speech mobile application
### Is your proposal related to a problem? Please describe.

This mobile application helps to convert from Text to speech

### Add any other context or screenshots about the proposal request here.

_No response_

### PR DESCRIPTION
**Pull request by jyothi-k-g**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes
### Description

This is an android application which converts text to speech

Fixes #604 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by photon149 — CHANGES_REQUESTED** [review]
@jyothi-k-g Please add in README 
- steps to run the app
- technologies to run the app
- if possible small output gif/vdo of the running app

**Comment by jyothi-k-g** [comment]
Done @photon149

**Review by photon149 — APPROVED** [review]
@jyothi-k-g 👍🏻 
Approved from my end
@Kushal997-das @prakhar3062 check

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@jyothi-k-g Nice work but for this project please add one gif or may be any video link about your output so people can under how the text changes to speech .

**Comment by jyothi-k-g** [comment]
Done @Kushal997-das

**Review by Kushal997-das — APPROVED** [review]
LGTM 💯

**Pull request merged**
