### PR TITLE
app built successfuly

### LINKED ISSUE #290: Mobile Application Project: Youtube Videos Downloader
**It is a flutter app which lets users download Youtube videos of their choice in different formats i.e video or audio or video without audio.
@Kushal997-das  I am a contributor in GSSOC'22. Can you please assign this project to me?
Thank you**

### PR DESCRIPTION
**Pull request by rahulNetkar**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes, I've read the guidelines.

### Description

A youtube downloader app which lets users download the videos and audios of their choice from Youtube.

Fixes #290 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

No issues, the app works perfectly. Please review this pull request. Thank you

### CODE REVIEW

**Review by photon149 — COMMENTED** [review]
@rahulNetkar Great Work 👍🏻 
Just a few minor changes required :
- In your README , add a section of requirements and the steps of how to run your app
- Add a Output GIF in your README

**Comment by rahulNetkar** [comment]
Hello mentors, and PA
I have made the changes that were requested.
Kindly check the recent commit.
Thank you

**Review by photon149 — APPROVED** [review]
@rahulNetkar Great Work.
@Kushal997-das @prakhar3062 have a look.

**Review by prakhar3062 — APPROVED** [review]
okay from my side

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@rahulNetkar Please delete all unwanted files like your .gitignore and delete all those files those are starting with dot(.) .

**Comment by rahulNetkar** [comment]
> @rahulNetkar Please delete all unwanted files like your .gitignore and delete all those files those are starting with dot(.) .

Done sir

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@rahulNetkar Still there are lot of unwanted files please delete them , those files are really necessary add them only .

**Comment by rahulNetkar** [comment]
> @rahulNetkar Still there are lot of unwanted files please delete them , those files are really necessary add them only .

I have deleted all the files starting with a dot(.). Can you specify exactly which files are to be deleted?

**Comment by rahulNetkar** [comment]
@Kushal997-das Please check now, sir.

**Pull request merged**
