### PR TITLE
Type Writer Effect Project Added

### PR DESCRIPTION
**Pull request by nouraan-ahmed**

### CODE REVIEW

**Review by prakhar3062 — CHANGES_REQUESTED** [review]
@nouraan-ahmed  add readme file

**Comment by prakhar3062** [comment]
looks okay to me @photon149

**Review by photon149 — APPROVED** [review]
@nouraan-ahmed Please mention the issue number related to the PR.
No Duplicity ✅ 
@Kushal997-das please review and merge the same

**Comment by Kushal997-das** [comment]
@nouraan-ahmed Please mentioned the issue number that you been fixed . Thanks

**Comment by nouraan-ahmed** [comment]
> Issue Number #569

@Kushal997-das

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
