### PR TITLE
Small Contributions in web project -> Tourist Places

### PR DESCRIPTION
**Pull request by TawfikYasser**

### CODE REVIEW

**Comment by TawfikYasser** [comment]
My last two commit for the CONTRIBUTING RULES File

**Review by Kushal997-das — COMMENTED** [review]
@TawfikYasser What kind of contribution you have done?

**Review by SamarpanCoder2002 — COMMENTED** [review]
You have increase code readability in index.html under web development and also add images in contributing.MD file...That really nice....this will clear the visitors about the contribution rules...Thanks for that...

**Comment by TawfikYasser** [comment]
> You have increase code readability in index.html under web development and also add images in contributing.MD file...That really nice....this will clear the visitors about the contribution rules...Thanks for that...

Thanks a lot @SamarpanCoder2002 

I hope this be good

@Kushal997-das This what I mean...

**Pull request merged**
