### PR TITLE
Issue#1181 fixed. Added Age Calculator Project

### LINKED ISSUE #1181: Title: Add an Age calculator under medium section of Web Development. I want to contribute under GSSOC' 24.
### Is your feature request related to a problem? Please describe.

No, it is an addition to the list of projects.

### Describe the solution you'd like.

I made an Age Calculator in ReactJs and TailwindCSS with clean UI and understandable code. I want to add it under medium section of Web Development. Here is an SS of my site:

Screenshot 2024-06-06 210040

### Describe alternatives you've considered.

N/A

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by ParnaRoyChowdhury777**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

 Yes I have gone through the project contribution guidelines.

### Description

I have added the Age Calculator Project under the intermediate section of Web Development. I have also updated the README of the Web Development section.

Fixes #1181 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes issue #1181

### CODE REVIEW

**Comment by ParnaRoyChowdhury777** [comment]
@Kushal997-das Please check the PR and tell me the changes needed

**Review by Kushal997-das — COMMENTED** [review]
@ParnaRoyChowdhury777 Please make the following changes:

1. Add all images to a single folder named 'Images'.
2. Deploy your project and include the live deployment link in the readme.md file.
3. Place this project under the `basic` folder.
4. Fix the error shown in the attached image.

fix this

**Comment by ParnaRoyChowdhury777** [comment]
@Kushal997-das  I have sent a fresh PR with all the changes

**Comment by Kushal997-das** [comment]
@ParnaRoyChowdhury777 You need to understand that you have to update the same PR. Or else close the old one. Learn how to update the things in the existing PR.

**Pull request closed without merging**
