### PR TITLE
Dawrha shop

### PR DESCRIPTION
**Pull request by ZeyadTarekk**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes
### Description

- Fullstack web application using PHP and MySQL

- We all should be responsible for protecting our environment and recycling is one of the easiest ways that we can do at home to contribute to the reduction of pollution so we decided to build an online shop that you can sell or buy recyclable items like (bottles, paper, boxes, etc.…).

- User can enter the site and offer some items to sell and another user can interact with him to buy this item.

- The main concern of the shop is to provide a way for the consumers to get rid of their garbage with a nominal cost and help recycling companies to save the effort of separating the garbage.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Comment by photon149** [comment]
@ZeyadTarekk Please mention the Issue Number the following PR relates to.

**Comment by ZeyadTarekk** [comment]
No issue number its a new project

**Comment by photon149** [comment]
@ZeyadTarekk Okay.
So to add to this repository , you first need to create an Issue regarding the same.
You can go to the issue section & create an Issue for your topic.
@Kushal997-das will assign you the issue then you we can look for  merging the PR.

**Comment by ZeyadTarekk** [comment]
Now it Fixes issue #610

**Review by Kushal997-das — APPROVED** [review]
@photon149 have a look .

**Review by photon149 — APPROVED** [review]
Approved from my end.
@ZeyadTarekk  Nicely made , though if there is scope of deleting any non important files do remove the same.
No Duplicity ✅ 
@prakhar3062 have a look

**Review by prakhar3062 — APPROVED** [review]

**Pull request merged**
