### PR TITLE
Resolving issue #222 as a part of GSSoC'22

### PR DESCRIPTION
**Pull request by AnIkeT126**
This PR contains the project file and a readme explaining the code.

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@Kushal997-das can you approve the workflow?

**Review by photon149 — CHANGES_REQUESTED** [review]
@AnIkeT126 Kindly do the following Changes.
- Increase Code Readability (Add Comments in your code)
- Put Output Screenshots of your Output in README file.

**Comment by AnIkeT126** [comment]
Hey @photon149, can I add all outputs inside a pdf as the number of outputs are seemingly large so it would be advantageous if I can upload a bunch of them in a pdf file?

**Comment by photon149** [comment]
If possible pick a few of the important Inference Graphs and update them in the README.
The prime reason of README is just to give a brief understanding of the project , so from that Point of View you can add the Output SS.

**Comment by AnIkeT126** [comment]
@photon149 can you check this now?

**Review by photon149 — APPROVED** [review]
Looks good to me.
@Kushal997-das approved from my end , please review and merge the same.

**Comment by Kushal997-das** [comment]
@AnIkeT126 This is not under appropriate folder please read the guidelines carefully , And also mention the Issue number here .

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@AnIkeT126 Please read contributing.md file very carefully .

**Comment by AnIkeT126** [comment]
> @AnIkeT126 This is not under appropriate folder please read the guidelines carefully , And also mention the Issue number here .

Hey, so I will change it to the appropriate folder but can you tell me where exactly are you asking me to mention issue number, becuase I have mentioned it as #222

**Pull request closed without merging**
