### PR TITLE
Expense Management App

### LINKED ISSUE #440: Title: Add Expense Tracker
### Is your feature request related to a problem? Please describe.

NA

### Describe the solution you'd like.

A web app to track and manage expenses with features to add , update , delete expense and other functionalities.

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by kaustav202**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

An expense management app using vanilla js, html and css. With full crud functionality.

Fixes #440 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Comment by Kushal997-das** [comment]
@kaustav202 

You keeps adding this project on multiple reops . Don't do this .
Btw i have exact project already in my repo . You project contains also same things like which i have in my repo .

[`Check`](https://github.com/Kushal997-das/Project-Guidance/pull/523)

**Comment by kaustav202** [comment]
@Kushal997-das  then may I know why you assigned the issue if it was already there and would be redundant?

**Comment by kaustav202** [comment]
Also, I've made the project so I may chose which repos to contribute too isn't it. Is there GSSOC rule that prevents it?

**Comment by Kushal997-das** [comment]
@kaustav202 First of all you are trying to add this project on multiple repos those are under GSSOC22 which break the rule of GSSOC22 . And Secondly before contributing any of the repo you should check their `contributing.md` file 
I have clearly mentioned this point in step 0 , you may check https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md#step-0--key-points-to-remember-

And the project which i have  already in my repo that project and your project exactly look like same even the variable name also same .

P.S. Don't be overconfidence on your words because you are spamming .

**Comment by kaustav202** [comment]
@Kushal997-das  
Okay I was not aware about this rule I accept but.. it was not there when the issue was created so I think it's for you to answer how same issue was approved which I had already been assigned. : ) Think about it from next time.
And it's not exactly same so I guess you can keep your opinions about spam to yourselves.

**Pull request closed without merging**
