### PR TITLE
Added issue forms

### LINKED ISSUE #276: Adding issue forms for the repo
## 🚀 Feature

I want to add a few issue forms so that it will be convenient for new contributors to open issues.
There are already issue templates for this project but they are deprecated now, issue forms instead work way better. I plan to create  **Bug Report**, **Feature Request**, **Documentation** and **Proposal** forms.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes.

## Motivation

Issue forms enable contributors to describe the issue more conveniently than issue templates. They enhance the **user experience** and enable contributors to create an issue hassle-free.

## Pitch

This feature can save people's time and make it easier for them to create issues. That's why I think it will be a good enhancement to the repo.  You can read more about issue forms [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

### PR DESCRIPTION
**Pull request by MonarchGitHub**
I have added **Bug Report**, **Proposal** , **Documentation**  and **Feature Request** issue forms to the repo.

**_Previews_**

- [Bug Report](https://github.com/MonarchGitHub/Project-Guidance/blob/monarchgithub/.github/ISSUE_TEMPLATE/bug_report.yaml)

- [Feature Request](https://github.com/MonarchGitHub/Project-Guidance/blob/monarchgithub/.github/ISSUE_TEMPLATE/feature.yaml)

- [Proposal](https://github.com/MonarchGitHub/Project-Guidance/blob/monarchgithub/.github/ISSUE_TEMPLATE/proposal.yaml)

- [Documentation](https://github.com/MonarchGitHub/Project-Guidance/blob/monarchgithub/.github/ISSUE_TEMPLATE/documentation.yaml)

I have a question, in the old Proposal issue template, there is a mention of **NeoAlgo**. I'm not sure what it is but i have not changed the description in the new proposal form. 

image

Kindly review the changes

fixes #276

### CODE REVIEW

**Review by Kushal997-das — APPROVED** [review]
@MonarchGitHub 👍

**Comment by Kushal997-das** [comment]
@MonarchGitHub Great work !! Yes that was a type i made changes . Thanks

**Comment by Kushal997-das** [comment]
@MonarchGitHub Can you please fetch this repo and send PR again !

**Comment by MonarchGitHub** [comment]
> @MonarchGitHub Can you please fetch this repo and send PR again !

Yes for sure.

**Pull request merged**
