### PR TITLE
Added Personal Portfolio Website Folder in Basics of Web Dev under SWOC3 contribution(#869) 

### LINKED ISSUE #869: Title: Include Portfolio website project in webdev
### Is your proposal related to a problem? Please describe.

I want to add the project of a personal portfolio website to the web development folder

### Add any other context or screenshots about the proposal request here.

_No response_

### PR DESCRIPTION
**Pull request by Prekshathakkar51**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #869

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Prekshathakkar51 This PR contains the file which is in aritificial intelligence delete this first .

**Comment by Prekshathakkar51** [comment]
I have deleted that AI file

**Comment by Kushal997-das** [comment]
> I have deleted that AI file

It is still there .

**Comment by Prekshathakkar51** [comment]
Kindly, check it now!
If still it does, then let me know

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Prekshathakkar51 You need to follow below instructions: 
1. You need to add a `readme.md` file in your project .
2. You need to deploy your project and put the link in `readme.md` file
3. You need to write description about your project in `readme.md` file.
4. You need to add images about your project in `readme.md` file. 
Complete these mentioned things first then will tell later what to do .

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Prekshathakkar51 Just add your project name under `web development/readme.md` in alphabetical order .

**Comment by Prekshathakkar51** [comment]
I have added the readme file

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Prekshathakkar51 You have deleted some existing projects name in your case under basic folder only 60 projects are there but look [here](https://github.com/Kushal997-das/Project-Guidance/tree/main/Web%20Development#level-1-basic-) this already have 68 under basic .

**Comment by Prekshathakkar51** [comment]
Kindly see now

**Review by Kushal997-das — APPROVED** [review]
@Prekshathakkar51 👍🏻

**Pull request merged**
