### PR TITLE
youtube-clone

### LINKED ISSUE #768: Title: Youtube Clone Frontend using Flutter
### Is your feature request related to a problem? Please describe.

Youtube is a complex app with very simple UI. So to learn many components in Flutter,  I have made Youtube Clone

### Describe the solution you'd like.

Using Flutter frontend containers are designed to design lightweight application of Youtube Clone

### Describe alternatives you've considered.

Flutter is the base framework of mobile application development that is platform independent where Dart programming language is used.

### Add any other context or screenshots about the feature request here.

I would appreciate if you assign this issue to me as a SWOC S3 Contributer

### PR DESCRIPTION
**Pull request by Gaurav8604**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

YouTube Clone Frontend design using Flutter

Fixes #768 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

-

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Gaurav-8604 This file contains lot of files , if possible please reduce those files those are not required to this project , only Make a PR on programmable file .

**Comment by Gaurav-8604** [comment]
@Kushal997-das Please check

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Gaurav-8604 Please do provide any link in readme.md where user can use this app or see this app at least

**Comment by Gaurav-8604** [comment]
@Kushal997-das  Please check my PR. 
All your requirements are surely met now!.
Thank you!

**Review by Kushal997-das — COMMENTED** [review]
@Gaurav-8604 Do not copy paste the someone project . This project is made by other fellow and he also contribute the same project i my repo already . Now you are not allowed to contribute in my project .

**Comment by Gaurav-8604** [comment]
@Kushal997-das . There is no such project as YouTube frontend clone in your repository. I took literally 15 days to make this frontend from scratch and you say you copied. Can you show me from where it is copied i.e. the link or GitHub repository. 

As well check properly before deciding someone's hardwork

Also this project is totally made in flutter and it was one of my first projects

You can check my GitHub repository and see that my project is uploaded on 14th July 2022.

And also please think before you speak

**Comment by Gaurav-8604** [comment]
And lastly if you say it is already there in your repository why did you approve my issue??

**Comment by Kushal997-das** [comment]
> And lastly if you say it is already there in your repository why did you approve my issue??

You need to check man and also in contributing guidelines it clearly mentioned duplication project not allowed . You have to check first for this only we made contributing guidelines file.

**Comment by Gaurav-8604** [comment]
Show me from where I copied?

And no such duplicate project is present in your repository. If present, show me

I am following all the guidelines, I think you should also follow your code of conduct and recheck

**Comment by Kushal997-das** [comment]
> @Kushal997-das . There is no such project as YouTube frontend clone in your repository. I took literally 15 days to make this frontend from scratch and you say you copied. Can you show me from where it is copied i.e. the link or GitHub repository.
> 
> As well check properly before deciding someone's hardwork
> 
> Also this project is totally made in flutter and it was one of my first projects
> 
> You can check my GitHub repository and see that my project is uploaded on 14th July 2022.
> 
> And also please think before you speak

Tell me what is that https://www.youtube.com/watch?v=naEy3Wc3iBs

**Comment by Kushal997-das** [comment]
> > @Kushal997-das . There is no such project as YouTube frontend clone in your repository. I took literally 15 days to make this frontend from scratch and you say you copied. Can you show me from where it is copied i.e. the link or GitHub repository.
> > As well check properly before deciding someone's hardwork
> > Also this project is totally made in flutter and it was one of my first projects
> > You can check my GitHub repository and see that my project is uploaded on 14th July 2022.
> > And also please think before you speak
> 
> Tell me what is that https://www.youtube.com/watch?v=naEy3Wc3iBs

This this you ?

**Comment by Gaurav-8604** [comment]
Ok. Not one world from that video matches my project


Have you checked what I have uploaded?
Difference between a catalog app and YouTube clone

You can see my output screenshots as well as apk file in my PR.

Please check and recheck

**Comment by Kushal997-das** [comment]
> Ok. Not one world from that video matches my project
> 
> Have you checked what I have uploaded? Difference between a catalog app and YouTube clone
> 
> You can see my output screenshots as well as apk file in my PR.
> 
> Please check and recheck

Check [this](https://github.com/SomyaRanjanSahu/Catalog-App ) out and yes this guy i know him , so you can't make admin fool . Anyways don't make any PR in to or issue you are no longer participant in this project

**Comment by Gaurav-8604** [comment]
Have you seen my PR?
Screenshots in Readme.md file


Not one word matched

This repository given from you is true no problem

But it doesn't even match my project title nor my project.

How can you compare???

Please give valid reason and before sending other's repository links, check my project and compare before you speak


It's the third time I am telling you to just compare my screenshots with his

**Comment by Gaurav-8604** [comment]
And the word fool. Think before checking my PR, compare them with what so you have and then check foolishness of others.

**Comment by Gaurav-8604** [comment]
@Kushal997-das  Reply me till tomorrow about the following.
Your friends project output:
image

My output:
image

They are totally different. There is no Plagiarism at all.

And if you are not familiar with the terms, Flutter is an open source framework by Google for building beautiful, natively compiled, multi-platform applications using Dart as language. Clearly there is no plagiarism here.

Also I feel the need to complaint about you on the SWOC platform tomorrow of rejecting PR for unfair or no reason and hampering the open source platform.

*Mistakes happen. No need to worry about getting running using unfair means. You still can merge my pull and the matter will be sorted*

**Comment by Gaurav-8604** [comment]
@Kushal997-das Reply me till tomorrow about the following.
Your friends project output:
image

My output:
image

They are totally different. There is no Plagiarism at all.

And if you are not familiar with the terms, Flutter is an open source framework by Google for building beautiful, natively compiled, multi-platform applications using Dart as language. Clearly there is no plagiarism here.

Also I feel the need to complaint about you on the SWOC platform tomorrow of rejecting PR for unfair or no reason and hampering the open source platform.

Mistakes happen. No need to worry about getting running using unfair means. You still can merge my pull and the matter will be sorted

**Comment by Kushal997-das** [comment]
> @Kushal997-das Reply me till tomorrow about the following. Your friends project output: image
> 
> My output: image
> 
> They are totally different. There is no Plagiarism at all.
> 
> And if you are not familiar with the terms, Flutter is an open source framework by Google for building beautiful, natively compiled, multi-platform applications using Dart as language. Clearly there is no plagiarism here.
> 
> Also I feel the need to complaint about you on the SWOC platform tomorrow of rejecting PR for unfair or no reason and hampering the open source platform.
> 
> Mistakes happen. No need to worry about getting running using unfair means. You still can merge my pull and the matter will be sorted

Change your tone first of all , yes you can complain and please do not teach me . You are not allowed to participate in thus project , that's all from my end . You said already lot of things .

**Comment by Gaurav-8604** [comment]
This is open source. Even if there is no mistake of mine I will suffer?

I said a lot of things but they have logic.
I just asked you to look again in my PR and tell me what is plagiarised. That's it

**Comment by Gaurav-8604** [comment]
I said a lot of things but they have logic.
I just asked you to look again in my PR and tell me what is plagiarised. That's it

Did you check my PR again. As a request just.
Even with proof you are not believing.
What should I do then?

**Comment by Kushal997-das** [comment]
> Sorry but despite requesting for so many times and proving it is not plagiarised what should I do next?
> 
> Sorry again but request you to check my PR again.

Will check  and do not talk like that with anyone .

**Comment by Gaurav8604** [comment]
@Kushal997-das Please check!

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Gaurav8604 Just add your project name [here](https://github.com/Gaurav8604/Project-Guidance/blob/youtube-clone/Mobile%20Applications/README.md) with alphabetical order .

**Comment by Gaurav8604** [comment]
@Kushal997-das  Please check!!

Thank You

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Gaurav8604 Link is not working

**Comment by Gaurav8604** [comment]
@Kushal997-das  The link will work when the pull request will be merged because the path will only work my folder is in your repository.

Thank You!

**Comment by Kushal997-das** [comment]
> @Kushal997-das The link will work when the pull request will be merged because the path will only work when my folder will be in your repository.
> 
> Thank You!

@Gaurav8604 No it's working like this a link can be work without even merge PR , fix this up

**Comment by Kushal997-das** [comment]
@Gaurav8604 Paste the URL over here .

**Comment by Gaurav8604** [comment]
Do I need to put link of my repository. Because relative path will not work.

I suggest to merge my PR and then check if it works.

I did the same as others did. Please look into it.

Thank you!

**Comment by Gaurav8604** [comment]
https://github.com/Kushal997-das/Project-Guidance/tree/main/Mobile%20Applications/Intermediate/YouTube-Clone

**Comment by Kushal997-das** [comment]
@Gaurav8604 Hello add my user in this URL so that after merge it gonna redirect in my repo only not urs .

**Comment by Gaurav8604** [comment]
@Kushal997-das 
I have done the same in the PR before. Just changes my Username to Yours

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
