### PR TITLE
Added BaseX Converter Files

### LINKED ISSUE #261: BaseX Calculator WebPage
## 🚀 Feature

A calculator that can convert numbers from base-X to base-Y. Example: `` Decimal to Binary ``, `` Binary to Octal ``, `` Base 3 to Base 6 ``, ..etc.

- The calculator will be able to also deal with decimal numbers.
- The page will make use of HTML, CSS & JS.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

- [x] Yes

## Motivation

It demonstrates how to convert from one base to another and it's a good on-the-go tool to quickly convert numbers when there is no pen & paper available to calculate

Issue created under GSSoC'22 Contributions

### PR DESCRIPTION
**Pull request by XZANATOL**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

- [x] Yes

### Description

Added BaseX Converter WebApp Files

Fixes #261 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue: #261 

PR made under GSSoC'22 contributions

### CODE REVIEW

**Comment by Kushal997-das** [comment]
@XZANATOL Wait for your first PR get merged !

**Review by Kushal997-das — APPROVED** [review]
LGTM 💯 
@photon149 Check !!

**Review by photon149 — COMMENTED** [review]
@XZANATOL Please Add Output Screenshots in README file.

**Comment by XZANATOL** [comment]
@photon149 I added a demonstration video that I uploaded on GDrive.

**Comment by photon149** [comment]
@XZANATOL Good Job
@prakhar3062 please have a look at this.

**Review by prakhar3062 — CHANGES_REQUESTED** [review]
@Kushal997-das  okay from my side

**Review by prakhar3062 — APPROVED** [review]
@Kushal997-das  okay from my side

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
