### PR TITLE
python-ping-pong-game

### LINKED ISSUE #329: Ping pong game using python
## 🚀 Feature

It is ping pong game using python turtle graphics

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

## Motivation

Previous projects which were already added in this repo motivated me to request  this,

## Pitch

Since previous issues contain different games as well by different  languages , I thought  my ping-pong python game should  also present in this repo

### PR DESCRIPTION
**Pull request by mayank-del**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description
This this basically a game which contains python turtle graphics

Fixes #329

### Checklist

- [ y] I've read the contribution guidelines.
- [ y] I've checked the issue list before deciding what to submit.
- [y ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

NO issues , it is just a  feature , I want to add.

### CODE REVIEW

**Review by photon149 — CHANGES_REQUESTED** [review]
@mayank-del Please do the following changes : 
- Add Comments to your code
- Attach a README file with output SS

**Comment by mayank-del** [comment]
Ok , i will add  both the things

**Comment by Kushal997-das** [comment]
@mayank-del Are you going to do the changes ? Or else your PR will close .

**Comment by mayank-del** [comment]
yaa , i am changing , wait.

**Review by mayank-del — COMMENTED** [review]
[Readme.md](https://github.com/Kushal997-das/Project-Guidance/files/8239944/Readme.md)

**Comment by mayank-del** [comment]
added comments and readme as well

**Comment by mayank-del** [comment]
Done everything

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@mayank-del Do the changes as @photon149 Mentioned .

**Comment by mayank-del** [comment]
@Kushal997-das  see i have added readme and comments both

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@mayank-del 
- Your project should not be under `web development` your project should under `desktop application/basic/python` . 
-  Add any gif about your project output in your `readme.md` file.

**Comment by mayank-del** [comment]
@Kushal997-das , @photon149 , sir please see pull request #405 , I added all the things, in desktop app directory, just ignore this request, git was creating error , That's why I have to recreate a new pull request. So, please see pull request #405

**Comment by Kushal997-das** [comment]
@mayank-del Okey !

**Pull request closed without merging**
