### PR TITLE
Flutter Basic BMI Calculator App

### LINKED ISSUE #341: BMI Calculator App
## 🚀 Feature

BMI Calculator is a basic level app development project that helps an individual to calculate his/her body mass index with just a few taps.

First of all the person has to select his/her gender and then set the height, weight, and age. Then after tapping on calculate button the result(BMI) is shown. It also gives feedback based on the result obtained.

Tools used: Flutter(2.8.1), Dart

Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)?
Yes

### PR DESCRIPTION
**Pull request by SomyaRanjanSahu**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

BMI Calculator is a basic level app development project that helps an individual to calculate his/her body mass index with just a few taps.

Fixes #341 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Comment by SomyaRanjanSahu** [comment]
@Kushal997-das Kindly review my pull request under GSSoc'22

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@SomyaRanjanSahu Delete all unwanted files and all (.) files .

**Comment by SomyaRanjanSahu** [comment]
@Kushal997-das Can you please tell me which files you are referring to?

**Comment by Kushal997-das** [comment]
> @Kushal997-das Can you please tell me which files you are referring to?

All .files means starting from . only.

**Comment by SomyaRanjanSahu** [comment]
@Kushal997-das Kindly check now I have removed all .files from the repo.

**Review by Kushal997-das — APPROVED** [review]
@SomyaRanjanSahu 

LGTM 👍 

@photo149 Check !!

**Comment by Kushal997-das** [comment]
@photon149 check

**Review by photon149 — APPROVED** [review]
@SomyaRanjanSahu Great work.
@prakhra3062 have a look , approved from my end.

**Pull request merged**
