### PR TITLE
Added Arduino_Servo_Motor files

### LINKED ISSUE #561: Arduino Servo Motor
### Is your proposal related to a problem? Please describe.

Add an arduino setup that demonstrates how to control a servo-motor.

### Add any other context or screenshots about the proposal request here.

Issue made under GSSoC'22 contributions.

### PR DESCRIPTION
**Pull request by XZANATOL**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

- [x] Yes

### Description

Added an arduino setup that demonstrates how to control a servo-motor.

fixes #561

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

PR made under GSSoC'22 contributions

### CODE REVIEW

**Review by photon149 — APPROVED** [review]
@XZANATOL 👍🏻 
Approved from my end
@Kushal997-das @prakhar3062 have a look

**Review by Kushal997-das — APPROVED** [review]

**Comment by Kushal997-das** [comment]
@prakhar3062 have a look .

**Review by prakhar3062 — APPROVED** [review]
@photon149 okay from my side

**Comment by XZANATOL** [comment]
@Kushal997-das Any updates?

**Pull request merged**
