### PR TITLE
Atm Machine

### LINKED ISSUE #510: ATM using PYTHON & MYSQL
### Is your feature request related to a problem? Please describe.

Create an ATM-like setup using Python and MySQL

### Describe the solution you'd like.

Create an ATM-like setup using Python and MySQL

### Describe alternatives you've considered.

None as Such

### Add any other context or screenshots about the feature request here.

None as Such

### PR DESCRIPTION
**Pull request by AnIkeT126**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

I thought to take a realistic topic so 
that I can implement it in a better and more understandable way. ATM is to help people in managing bank activities without 
visiting bank and in a safe, secured manner. With this in mind, I
chose to make a project on ATMs with works similar to real-world ATMs. 

Fixes #510 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue number #510

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@Kushal997-das can you please review this PR, and merge it upon finding it correct.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@AnIkeT126 

Just change the file location like this `Desktop Application/Basic/Python/ATM Machine/ATM.py`

**Comment by AnIkeT126** [comment]
> @AnIkeT126
> 
> Just change the file location like this `Desktop Application/Basic/Python/ATM Machine/ATM.py`

@Kushal997-das it's already in the format u requested

**Comment by AnIkeT126** [comment]
@Kushal997-das please review this PR, as I already made the submission in the format suggested, so please merge it.

**Comment by Kushal997-das** [comment]
> @Kushal997-das please review this PR, as I already made the submission in the format suggested, so please merge it.

This is not in the format . Do the changes .

**Comment by Kushal997-das** [comment]
> @AnIkeT126
> 
> Just change the file location like this `Desktop Application/Basic/Python/ATM Machine/ATM.py`

Here i mentioned basic see carefully.

**Comment by AnIkeT126** [comment]
@Kushal997-das I am closing this PR, I have updated the changes in #572

**Pull request closed without merging**
