### PR TITLE
Added Voting.sol and Raffle.sol to Blockchain/Intermediate

### LINKED ISSUE #1340: Title: Addition of more Blockchain development Projects as Part of GsWOB
### Is your feature request related to a problem? Please describe.

There are few basic blockchain projects and not in any intermediate and advance.

### Describe the solution you'd like.

I would like to add more projects in intermediate levels of blockchain development.

### Describe alternatives you've considered.

Some basic and advance level projects may also be entered.

### Add any other context or screenshots about the feature request here.

Please label the issue according to GsWOB labels and assign it to me. Thank you.

### PR DESCRIPTION
**Pull request by ShivRaiGithub**
### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 
I have added two solidity smart contracts `Voting.sol` and `Raffle.sol` to Blockchain Development/Intermediate. Voting allows a decentralized and tamperproof voting to be conducted where a user(owner) adds the candidates and authorizes selected voters to vote whereas Raffle is like lottery where an owner starts it and other users can enter it by paying a small fee, at end of which a winner is randomly selected and can claim the prize amount.

### 🏷️ Initiative Participation *(Required)*

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [x] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Comment by SakiraAli1115** [comment]
I am the mentor of this project.
@ShivRaiGithub Hello
I appreciate your pull request , can you give working video !!!!

**Comment by ShivRaiGithub** [comment]
Hi @SakiraAli1115
Sure. Will send a demo video of both of them on remix (online compiler) till tonight.

**Comment by ShivRaiGithub** [comment]
@SakiraAli1115  Here is the demo video
https://github.com/user-attachments/assets/3b24483f-1d3a-4e4a-9fef-ae8aa05ad783

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@ShivRaiGithub There's no readme.md file available, and documentation is insufficient. Please check other projects to understand the expected format.

**Comment by ShivRaiGithub** [comment]
Ok sure, will do the required changes.

**Comment by ShivRaiGithub** [comment]
@Kushal997-das I have updated the documentation readme files, structured files according to the format, updated the Intermediate readme file. Please review and let me know.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@ShivRaiGithub Add both your `Raffle` and `Voting` folder under one folder, that should be your project name folder.

**Comment by ShivRaiGithub** [comment]
@Kushal997-das  Raffle and voting are 2 separate projects.

**Comment by Kushal997-das** [comment]
You can’t add two projects in single time , you must read our guidelines
first before blindly contribution

**Comment by ShivRaiGithub** [comment]
@Kushal997-das Although I wasn't able to find any point which explicitly mentioned that there has to be only one project per pr, yet if you want,  I can create another PR for the 2nd project and make sure this one contains only 1 project.

**Comment by ShivRaiGithub** [comment]
Hey @Kushal997-das I have updated the PR to contain only 1 project in the intermediate section. Its Raffle. Will create a new PR to include Voting after this is accepted.

**Comment by Kushal997-das** [comment]
Hello @ShivRaiGithub no need to create another one .

**Comment by ShivRaiGithub** [comment]
Ok @Kushal997-das . How do you wish to proceed then ? Since there are 2 projects. I have already removed one of them. I can add it again if you want 2 to be included in 1.

**Comment by Kushal997-das** [comment]
@ShivRaiGithub Add only one.

**Comment by ShivRaiGithub** [comment]
@Kushal997-das Ok. There is only one in this PR

**Comment by ShivRaiGithub** [comment]
You can review.

**Comment by AKSHITHA-CHILUKA** [comment]
add level labels @Kushal997-das 
Regards ,
Community Manager gssoc-ext

**Pull request merged**
