### PR TITLE
Desktop Application README File

### PR DESCRIPTION
**Pull request by TawfikYasser**
Hi @Kushal997-das 

This PR to add the README file associated  with issue #58 

I hope you like it.

Thanks

### CODE REVIEW

**Review by SamarpanCoder2002 — COMMENTED** [review]
That really awesome and cool for understanding....But I think I can improve more about presentation...By the way...Your design really triggers me to contribute more here...really...your vision about that project is really awesome...We need more from you...

**Comment by TawfikYasser** [comment]
Thank your very much @SamarpanCoder2002 

I have another idea what is your opinion to add collapsible section with the directory tree structure?

Thanks

**Review by Kushal997-das — COMMENTED** [review]
Indeed awesome job @TawfikYasser Your contribution is just wow. 
@TawfikYasser I want more developers to contribute in this project please do share and you can guide them as a mentor. 
Good luck :)

**Comment by Kushal997-das** [comment]
> Thank your very much @SamarpanCoder2002
> 
> I have another idea what is your opinion to add collapsible section with the directory tree structure?
> 
> Thanks

Great idea you can add tree structure in Desktop Application. For visitors point of view it would be great if you will add.

**Comment by TawfikYasser** [comment]
Thanks @Kushal997-das 

Okay I will add the tree and give me your feedback.

Thanks

**Comment by SamarpanCoder2002** [comment]
> Thanks @Kushal997-das
> 
> Okay I will add the tree and give me your feedback.
> 
> Thanks

I think we can add a tree structure and added a project corresponding gif or picture with the project name. I think it will better...I try it for some projects and make pull requests after some time...

**Comment by Kushal997-das** [comment]
@TawfikYasser One thing you can do when you gonna create tree like structure then make sure you use root tree as "Desktop Application" Then you add another tree inside "the root tree" Like basic, intermediate, Advanced then add the project name according to the levels (basic, intermediate, advanced) make you you add also hyper link.

**Comment by SamarpanCoder2002** [comment]
> @TawfikYasser One thing you can do when you gonna create tree like structure then make sure you use root tree as "Desktop Application" Then you add another tree inside "the root tree" Like basic, intermediate, Advanced then add the project name according to the levels (basic, intermediate, advanced) make you you add also hyper link.

Don't worry guys..I try it...I think I think I can make it..

**Comment by Kushal997-das** [comment]
> > Thanks @Kushal997-das
> > Okay I will add the tree and give me your feedback.
> > Thanks
> 
> I think we can add a tree structure and added a project corresponding gif or picture with the project name. I think it will better...I try it for some projects and make pull requests after some time...

@SamarpanCoder2002 This gonna be awesome if we add gif. (But make sure you have to add small gif)

**Comment by SamarpanCoder2002** [comment]
> > > Thanks @Kushal997-das
> > > Okay I will add the tree and give me your feedback.
> > > Thanks
> > 
> > 
> > I think we can add a tree structure and added a project corresponding gif or picture with the project name. I think it will better...I try it for some projects and make pull requests after some time...
> 
> @SamarpanCoder2002 This gonna be awesome if we add gif. (But make sure you have to add small gif)

Project readme containing gif will I add...But some projects not having a gif in the readme, I can't add...

**Comment by TawfikYasser** [comment]
Okay @Kushal997-das , @SamarpanCoder2002 

See my last PR

Thanks

**Comment by SamarpanCoder2002** [comment]
> Okay @Kushal997-das , @SamarpanCoder2002
> 
> See my last PR
> 
> Thanks

Some Changes are requested...Please See that..Thanks for your time...

**Pull request merged**
