### PR TITLE
Added a dynamic Web Based Quiz App

### LINKED ISSUE #1324: Title: Web Based Quiz App
### Is your feature request related to a problem? Please describe.

A quiz app is a great project because it combines educational value with engaging user interaction, making learning fun and accessible.

### Describe the solution you'd like.

A quiz app keeps mind sharp and knowledge uptodate

### Describe alternatives you've considered.

I have thought of other apps but quiz app seems best

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by Sourabh782**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
Yes i have gone through the Contributing Guidelines.
(Write your answer here.)

### Description
Are you ready to dive into the world of technology and test your expertise? Welcome to TechQuiz Pro, the premier quiz app specifically designed for tech enthusiasts, professionals, and curious minds alike!

(Write your answer here.)

Fixes #1324 

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1324 

Realted Images:
Screenshot 2024-08-03 131647

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Hi @Sourabh782,

Please make the following changes:

1. Move the project into the `basic` folder.
2. Create a `readme.md` file that provides a comprehensive explanation of the project.
3. Deploy the project and include the deployment link in the `readme.md` file. 

Thanks!

**Comment by Sourabh782** [comment]
@Kushal997-das ok I'll implement the following changes

**Comment by Sourabh782** [comment]
@Kushal997-das  I have implemented the changes suggested by you.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Sourabh782 Make it for mobile view as well.

**Comment by Sourabh782** [comment]
@Kushal997-das all changes made

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Hi, @Sourabh782 everything else is good , just add your project name [here](https://techquiz-pro.netlify.app/)

**Comment by Sourabh782** [comment]
hello @Kushal997-das  where should i add it? Your link is opening the app

**Comment by Sourabh782** [comment]
@Kushal997-das added my project in Web Development -> README.md

**Review by Kushal997-das — APPROVED** [review]

**Comment by Kushal997-das** [comment]
@Sourabh782 I am awarding you `Level 2` in recognition of your hard work.

**Comment by Sourabh782** [comment]
Really Appreciated @Kushal997-das Thnaks a lot 💯💯

**Pull request merged**
