### PR TITLE
Donation website model

### LINKED ISSUE #303: ADD DONATION WEBSITE MODEL
## 💥 Proposal

A desktop website for donation, designed in html Css with little JS. It is just a design so that anyone can use the code if required anyway.
I am a GSSOC participant and wish to work under your project thus bringing this proposal.

### PR DESCRIPTION
**Pull request by Daksh-jha**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes, I have read contributing Guidelines.

### Description

Added a desktop donation website which can be used by beginners to learn code which include gateway payment integration

Fixes #303

### Checklist

- I've read the contribution guidelines.
- I've checked the issue list before deciding what to submit.
- I've edited the `README.md` and link to my code.

### CODE REVIEW

**Review by photon149 — COMMENTED** [review]
@Daksh-jha Please rename your folder name as "Donation Website".

**Comment by Daksh-jha** [comment]
@photon149 , I have done the required changes. Please review it.

**Comment by photon149** [comment]
@Daksh-jha 👍🏻 
@Kushal997-das @prakhar3062 have a look.

**Review by prakhar3062 — APPROVED** [review]
okay from my side

**Review by Kushal997-das — APPROVED** [review]
@Daksh-jha 👍

**Pull request merged**
