### PR TITLE
Added Snake game

### PR DESCRIPTION
**Pull request by Rashmisingh-18**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

Snake game built using html, css, js

### CODE REVIEW

**Comment by Kushal997-das** [comment]
@Rashmisingh-18 Please mention the issue is fixes !

**Comment by Rashmisingh-18** [comment]
Fixes issue #342

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Rashmisingh-18 Create one `readme.md` file and Please add any gif or photos about your project in `raedme.md` file.

**Comment by Rashmisingh-18** [comment]
Added readme.md file.
@Kushal997-das

**Pull request merged**
