### PR TITLE
🤖  Add GroqDev LLM application 

### LINKED ISSUE #1381: Title: Add GroqDev LLM application
### Is your feature request related to a problem? Please describe.

Add a LLM bot project in the Artificial Intelligence category, which is a chatbot for coding purposes.

### Describe the solution you'd like.

Develop a new LLM bot that uses API key to chat & invoke LLM call functions to create & generate reponses tailored to user's prompt

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

NA

### PR DESCRIPTION
**Pull request by yashksaini-coder**
# Project-Guidance! 🎊🎈

### Welcome! 🎉

Thank you for visiting our repository! We're excited to have you here. If you find this project useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [X] YES
- [ ] NO

### 📝 Description 

My GroqDev chatbot is a basic implementation of using Groq API keys and to create a flask application which can be use & invoke different models based on the user's choice. The codebase is very simple and not much complicated. It is the best AI application for beginners who want to get a crack in the AI application workflow

### 🏷️ Initiative Participation *(Required)*

This pull request is associated with the following initiative. Please choose the one you are contributing to:

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [X] 🌼 GSSoC 2024 Extd.
- [X] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [X] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
@Kushal997-das review the PR & can you assign me the PR with proper labels

**Comment by yashksaini-coder** [comment]
@Kushal997-das how long will the review period take ?

**Comment by yashksaini-coder** [comment]
@Kushal997-das can you give your review on this PR

**Comment by yashksaini-coder** [comment]
@Kushal997-das when will the approval be given to my PR

**Review by yashksaini-coder — COMMENTED** [review]
When can I expect the merge ? @Kushal997-das

**Comment by yashksaini-coder** [comment]
@Kushal997-das please review the changes

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@yashksaini-coder,

Hello! Here are the changes you need to make:

1. Add relevant output screenshots to the README.md file.
2. If possible, host the project and include the deployment link in the README.md file.
3. Make the README.md file clearer and more informative.
4. Change your project name to something more interactive.
5. Update your project in the basic section here: [Project Guidance - AI](https://github.com/Kushal997-das/Project-Guidance/blob/main/Artificial%20Intelligence/README.md).

Thank you!

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder,
> 
> Hello! Here are the changes you need to make:
> 
> 1. Add relevant output screenshots to the README.md file.
> 2. If possible, host the project and include the deployment link in the README.md file.
> 3. Make the README.md file clearer and more informative.
> 4. Change your project name to something more interactive.
> 5. Update your project in the basic section here: [Project Guidance - AI](https://github.com/Kushal997-das/Project-Guidance/blob/main/Artificial%20Intelligence/README.md).
> 
> Thank you!

okh understood @Kushal997-das

**Comment by yashksaini-coder** [comment]
can it be level 3 @Kushal997-das  ??

**Comment by yashksaini-coder** [comment]
@Kushal997-das Can you look at this `dir` strucuture

**Comment by yashksaini-coder** [comment]
@Kushal997-das also I have added main repo link, deployment is currently inactive.

**Comment by yashksaini-coder** [comment]
Hi @Kushal997-das I completed the given request as much as possible, now the flask application is ready.
However I have not added the deployment link, as I am in the middle of changing the backend deployment service currently. 

Added screenshots, Add badges & banners in the README, add project in the `Artificial Intelligence/README.md`

**Comment by yashksaini-coder** [comment]
> can it be level 3 @Kushal997-das ??

can this be promoted to Level 3

**Comment by yashksaini-coder** [comment]
@Kushal997-das

**Comment by Kushal997-das** [comment]
@yashksaini-coder I appreciate your efforts, but there are a few important points that need to be addressed:

1. The information I provided wasn't fully incorporated. Instead, you included details about your social profile on the readme.md, which is less relevant.
2. The deployment link is missing. Without this, we cannot proceed.
3. It seems you're more focused on achieving higher levels, but it's essential to prioritize the required changes first.
4. Please refrain from posting multiple comments in a row. If you're in a hurry, you may choose to close this.
5. This will be my final reminder regarding the necessary changes. If they're not addressed, I will have to close this issue.

**Pull request closed without merging**
