### PR TITLE
Add mern stack Todo app

### LINKED ISSUE #1163: Title: Adding MERN stack todo app
### Is your feature request related to a problem? Please describe.

A crud mern stack project is missing in this repository.

### Describe the solution you'd like.

I would like to add a todo app, created using mern stack. Users can add, edit, delete, view todo tasks. They can also categorize task into categories such as personal, home, work and urgent.

Kindly please assign this issue to me.

### Describe alternatives you've considered.

None

### Add any other context or screenshots about the feature request here.

Screenshot 2024-06-02 142215
Screenshot 2024-06-02 142228
Screenshot 2024-06-02 142246

### PR DESCRIPTION
**Pull request by DharshiBalasubramaniyam**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

yes

### Description

(Write your answer here.)'
I have added a todo app using mern stack.

Fixes #1163 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
NA

### CODE REVIEW

**Comment by DharshiBalasubramaniyam** [comment]
@Kushal997-das, please kindly review this pr.

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam Could you please include an explanation of the CRUD operations in the `readme.md` file to enhance the user experience? Also, kindly categorize the project under Intermediate.

I can add an readme file. In the intermediate section there is already a project exist with name todo app. May I name this project as MERN-CRUD?

**Comment by Kushal997-das** [comment]
@DharshiBalasubramaniyam Ok, please keep this in the advance folder. However, could you include an explanation of the CRUD operations in the README.md file to improve the user experience?

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam Ok, please keep this in the advance folder. However, could you include an explanation of the CRUD operations in the README.md file to improve the user experience?

Okay, I'll do it

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam Ok, please keep this in the advance folder. However, could you include an explanation of the CRUD operations in the README.md file to improve the user experience?

I have updated the read me file. 

image

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@DharshiBalasubramaniyam Arey, Mention the full form of CRUD and explain what does it mean , and yes keep the image also.

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam Arey, Mention the full form of CRUD and explain what does it mean , and yes keep the image also.

I have done some changes read me file. Could you kindly check to see if they are correct?

**Review by Kushal997-das — APPROVED** [review]
@DharshiBalasubramaniyam LGTM 👍🏻

**Pull request merged**
