### PR TITLE
Add files via upload #153

### PR DESCRIPTION
**Pull request by suy1968**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by suy1968** [comment]
Let's add the contributing files Covid19_statewise dataset using Streamlit library

**Review by suy1968 — COMMENTED** [review]
let's add my contributing file covid19_syatewise using streamlit

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@suy1968 I reviewed but please try to make your readme.md file more attractive not just put a simple link .
Please [Check this link](https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application/Basic/Python/Scientific%20Calculator%20Dolly) like this you can add more details about your project and don't forget to add  a simple `gif` .

**Comment by suy1968** [comment]
Let's add my contributing  file Iriswebapp using streamlit library

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Please try to do as i mentioned @suy1968

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@suy1968 hey do like as i mentioned after completion send PR ok

**Review by Kushal997-das — COMMENTED** [review]
(:

**Review by Kushal997-das — APPROVED** [review]
LGTM 🥇 
Great work @suy1968 Thanks for contributing . I hope you contribute more 💯

**Review by SamarpanCoder2002 — APPROVED** [review]
LGTM .... thanks for your contribution... Expecting more contribution from you...

**Pull request merged**
