### PR TITLE
Added Converse Chat Appln Feature

### LINKED ISSUE #205: Converse - Application to communicate with the clients
## 🚀 Feature

Its a Web Chat Application which uses firebase services to communicate with multiple clients by creating multiple instances

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yeah

## Motivation

So, Working with Database, Sockets and clear visualization of Web Dev Concepts can be achieved when one can create a chat appln. This chat appln uses Firebase services so we can learn to use Firebase as the Database instead of a local database. 

## Pitch

This feature can be implemented by deploying the code on an opensource platform like Heroku or using Google Cloud (Free Tier).  The deployment link can be used directly in various places to interact with the customers.

### PR DESCRIPTION
**Pull request by saiadityaviswanadham**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yeah

### Description

Chat Apps are increasingly being used to replace SMS text messaging where it is
free, offers group messaging and photo sharing. A chat application is a platform
that enables users to instant message and connect with each other through their
computers or mobile devices.

This chat client web application will be done by syncing data using Cloud Firestore
and Cloud Storage for Firebase. Firebase Authentication will be used for the
authentication of users. Web app will be deployed on Firebase Hosting. The
notifications will be sent with Firebase Cloud Messaging. It can also be
programmed to collect the user’s web app's performance data.

Fixes #205 

### Checklist

- [ x ] I've read the contribution guidelines.
- [ x ] I've checked the issue list before deciding what to submit.
- [ x ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Assigned Issue #205

### CODE REVIEW

**Comment by saiadityaviswanadham** [comment]
@Kushal997-das I have removed all the unnecessary files

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@saiadityaviswanadham Please add a good gif about your project and add in `readme.md` file and try to reduce the file those are really not necessary .

**Comment by saiadityaviswanadham** [comment]
@Kushal997-das Added a gif file. All the files are required and so I didn't remove any files.

**Comment by Kushal997-das** [comment]
> @Kushal997-das Added a gif file. All the files are required and so I didn't remove any files.

All the files are not required here like your all (.) files like .gitignore like this file your have to remove .

**Comment by saiadityaviswanadham** [comment]
@Kushal997-das I removed the files which are not required.

**Comment by Kushal997-das** [comment]
> @Kushal997-das I removed the files which are not required.

Please add only your project files why you add all unwanted files . Delete all these . After all required changes then tell me.

**Comment by saiadityaviswanadham** [comment]
@Kushal997-das I am not able to find unwanted files...All the files are of use only....I have removed .git and other unwanted files. Can you give me any example of an unwanted file.  All the rules files are required by firebase. And the remaining are the functions. Can you please give an example of unwanted file which is present in my folder..

**Comment by Kushal997-das** [comment]
@saiadityaviswanadham Open new fresh PR .

**Pull request closed without merging**
