### PR TITLE
Code Enhancements

### PR DESCRIPTION
**Pull request by TawfikYasser**
Hi
This PR to apply some enhancements in code in project `Tourists Places`
I hope this be good
Thanks

### CODE REVIEW

**Review by Kushal997-das — COMMENTED** [review]
What kind of enhancement you have done? Please elaborate. 
@TawfikYasser 
@SamarpanCoder2002 don't merge this update now.

**Comment by TawfikYasser** [comment]
Format code to be more readable and removing a lot of unimportant spaces.

**Comment by Kushal997-das** [comment]
> Format code to be more readable and removing a lot of unimportant spaces.

Okey I'll merge @TawfikYasser but @TawfikYasser we need more contributor to contribute please tell your friends to contribute.

**Review by Kushal997-das — APPROVED** [review]
Great @TawfikYasser

**Comment by TawfikYasser** [comment]
> > Format code to be more readable and removing a lot of unimportant spaces.
> 
> Okey I'll merge @TawfikYasser but @TawfikYasser we need more contributor to contribute please tell your friends to contribute.

Of course I am telling my friends, and i will tell them again in my WhatsApp and telegram, but i think we need to make more marketing and enhancements for the repo to make it more useful and attractive.

**Comment by Kushal997-das** [comment]
> > > Format code to be more readable and removing a lot of unimportant spaces.
> > 
> > 
> > Okey I'll merge @TawfikYasser but @TawfikYasser we need more contributor to contribute please tell your friends to contribute.
> 
> Of course I am telling my friends, and i will tell them again in my WhatsApp and telegram, but i think we need to make more marketing and enhancements for the repo to make it more useful and attractive.

Absolutely @TawfikYasser we will do :)

**Pull request merged**
