### PR TITLE
Issue#1181 fixed. Added age calculator project with the required changes

### LINKED ISSUE #1181: Title: Add an Age calculator under medium section of Web Development. I want to contribute under GSSOC' 24.
### Is your feature request related to a problem? Please describe.

No, it is an addition to the list of projects.

### Describe the solution you'd like.

I made an Age Calculator in ReactJs and TailwindCSS with clean UI and understandable code. I want to add it under medium section of Web Development. Here is an SS of my site:

Screenshot 2024-06-06 210040

### Describe alternatives you've considered.

N/A

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by ParnaRoyChowdhury777**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

I have added the Age Calculator Project under the Basic section of Web Development and have done the changes you mentioned previously.

Fixes #1181 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes Issue #1181 
Corrects the previous PR #1251

### CODE REVIEW

**Comment by ParnaRoyChowdhury777** [comment]
@Kushal997-das I closed the previous one...

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Hi, @ParnaRoyChowdhury777. Please make the following updates:

1. Remove sections like 'Contributing' and 'Contact' from your `readme.md` file.
   
2. Pull the latest updates from the repository.
   
3. Address the issue in your `readme.md` file as described [here](https://github.com/ParnaRoyChowdhury777/Project-Guidance/tree/main/Web%20Development#level-1-basic-).

4. Additionally, include instructions prompting users to enter their age for better clarity.


dd

**Comment by ParnaRoyChowdhury777** [comment]
@Kushal997-das check once

**Comment by ParnaRoyChowdhury777** [comment]
@Kushal997-das check once

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Hi, @ParnaRoyChowdhury777,

---

We still have a couple of issues:

1. There are elements out of place. Please refer to the image below for details.

not fix


2. Clicking `age calculator` redirects to another project. Please correct this without altering previous configurations, or we will have to close the PR.

---

**Pull request closed without merging**
