### PR TITLE
Added New logo

### PR DESCRIPTION
**Pull request by UG-SEP**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)?
Yes

### Description

(New logo of project guidance and added the image in document folder)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
related: #154

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@UG-SEP The background color is blue i think the bg color is not so attractive . Let's discuss over discussion section create a new discussion under [this](https://github.com/Kushal997-das/Project-Guidance/discussions/categories/q-a)

**Comment by meenagupta5** [comment]
@Kushal997-das please review it

**Comment by Kushal997-das** [comment]
@UG-SEP Fetch this repo first .

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@UG-SEP Fetch this repo first .

**Review by Kushal997-das — APPROVED** [review]
Great work @UG-SEP

**Pull request merged**
