### PR TITLE
Added Face Mask Detector

### LINKED ISSUE #248: Face Mask Detector
## 🚀 Feature

This will check if person is wearing a face mask or not.  

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

## Motivation

Contibution to open source and love for python.

## Pitch

Face Mask Detection is one of the easy ways to get into OpenCV. This would be a nice way to showcase how with OpenCV we can detect faces and check if they are wearing a mask.

@Kushal997-das 
> I am a GSSOC-Contributor'22 I would be happy to contribute  . If you assign me this, I could start working on this immediately . Thank you :)

### PR DESCRIPTION
**Pull request by Sabyasachi-Seal**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

Added the Face Mask Detector under the ML Projects and Data Science Folder (Basic Level)

Fixes #248 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Face Mask Detector #248 -> Project-Guidance\Machine Learning and Data Science\Basic\Face Mask Detector\

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Sabyasachi-Seal Hey! please add some gif of your project in `readme.md` file .

**Comment by Sabyasachi-Seal** [comment]
Ok, Noted. Will be adding it soon.

**Comment by Sabyasachi-Seal** [comment]
@Kushal997-das I have made the necessary changes. :)

**Review by Kushal997-das — APPROVED** [review]
@Sabyasachi-Seal Great work :)

LGTM 💯 

@photon149

**Review by prakhar3062 — APPROVED** [review]
@photon149 okay from my side

**Review by photon149 — APPROVED** [review]
@Sabyasachi-Seal Really neat code.
Approved from my end .
@Kushal997-das please merge the same.

**Pull request merged**
