### PR TITLE
Added Random Joke Generator added. Web Development

### LINKED ISSUE #667: Title: want to add a random joke app
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like.

Hey project admin I'm a GSSOC  participant and I want to add a random joke web app created with HTML CSS and JS to the current repository. the jokes are coming through third party API so it is a good practice for beginners how to use API and handle asynchronous tasks. 
please go through my issue and assign me this issue to work on.

### Describe alternatives you've considered.

No, I have not described any alternative.

### Add any other context or screenshots about the feature request here.

Joke App - Google Chrome 15-05-2022 11 40 03 AM
Joke App - Google Chrome 15-05-2022 11 40 25 AM

### PR DESCRIPTION
**Pull request by AmolShelke2**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)?

(yes)

### Description

(Hey, project admin, as you assigned me this issue to work on, I created the pull request regarding that. please go through the pull request and review it thanks :D )

(I have also fixed the README.md file some of the links were not attached properly so I have attached them properly and now it looks perfect.)

Fixes #667 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Joke App - Google Chrome 15-05-2022 11 40 03 AM

@Kushal997-das please review this pull request.

### CODE REVIEW

**Review by photon149 — APPROVED** [review]
Approved.
@Kushal997-das @prakhar3062

**Review by prakhar3062 — APPROVED** [review]
Nice work

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@AmolShelke2 Hello Amol please rename the project name since it's a website not a app.

**Comment by AmolShelke2** [comment]
> @AmolShelke2 Hello Amol please rename the project name since it's a website, not a app.

@Kushal997-das I have renamed the project name and folder name also please go through the pull request.

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
