### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by TawfikYasser**

### CODE REVIEW

**Review by SamarpanCoder2002 — COMMENTED** [review]
Looks Good

**Review by Kushal997-das — APPROVED** [review]
Looks good to me :) 
@TawfikYasser please fetch first then send PR

**Comment by TawfikYasser** [comment]
Okay fetch done

**Review by SamarpanCoder2002 — COMMENTED** [review]
Good

**Comment by Kushal997-das** [comment]
@SamarpanCoder2002 Please check before merging he was 1commit behind the original repo .

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 Please check before merging he was 1commit behind the original repo .

Yeah...that my mistake....sorry...I will remember this..

**Pull request merged**
