### PR TITLE
Completed the issue #283 under GSSoC'22

### LINKED ISSUE #283: Animal adoption portal GSSoC22
It is an web development project through which one can view all the pets which are available for adoption and adopt them.

@Kushal997-das  please assign this issue to me. I'm an participant of GSSOC'22

### PR DESCRIPTION
**Pull request by jyothi-k-g**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

Animal adoption portal
Fixes #283 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by photon149** [comment]
@jyothi-k-g please follow the PR making format.
Add the details in your PR in accordance to the Contributing Guidelines

**Comment by jyothi-k-g** [comment]
@Kushal997-das  I have done all the changes kindly check it

**Review by photon149 — APPROVED** [review]
Approved from my end.
@prakhar3062 please have a look at this.

**Review by prakhar3062 — APPROVED** [review]
Everything is okay

**Pull request merged**
