### PR TITLE
Advanced Authentication system added

### LINKED ISSUE #731: Advanced Authentication System using MERN
### Is your feature request related to a problem? Please describe.

Since authentication is the most important part while building any web app I would like to contribute a project related to that.

### Describe the solution you'd like.

An advanced authentication system using MERN stack . It will contain email verification feature that will be implemented using Sendgrid and  hashing password and storing them securely, generating JWT and storing it in the frontend . It will be a full stack web app with proper middleware setup . This will go under web dvelopment advanced projects .

### Describe alternatives you've considered.

Please assign me this issue under GSSoC'22.

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by piyusha2001**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

Created a fullstack  authentication system project using MERN stack that uses jwt authorization .User is authenticated via email ,for this nodemailer is used, after authentication update profile functionality is also provided. 

Fixes #731 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

#Working-

https://user-images.githubusercontent.com/81703477/170821988-5b4cd441-c3b3-4647-ad51-6fb931aec1da.mp4

### CODE REVIEW

**Comment by piyusha2001** [comment]
@Kushal997-das  please review my PR

**Review by prakhar3062 — APPROVED** [review]

**Comment by piyusha2001** [comment]
@Kushal997-das  please review this PR

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@piyusha2001 Add any gif or may be image about your project in the `readme.md` file . And those files are really not required please delete those . Do the Changes by today EOD .

**Comment by piyusha2001** [comment]
@Kushal997-das  done please check once.

> @piyusha2001 Add any gif or may be image about your project in the `readme.md` file . And those files are really not required please delete those . Do the Changes by today EOD .

Done . Please check once .

**Review by photon149 — APPROVED** [review]
LGTM 👍🏻 
Approved.

**Comment by piyusha2001** [comment]
@Kushal997-das  can you please review it as gssoc is about to end now

**Review by Kushal997-das — APPROVED** [review]

**Comment by piyusha2001** [comment]
@Kushal997-das wouldnt this be level 3 project ? It can be used as templete before starting any mern project

**Comment by Kushal997-das** [comment]
No this is under level 2 only.

**Comment by piyusha2001** [comment]
> No this is under level 2 only.

Okay

**Pull request merged**
