### PR TITLE
Examination

### LINKED ISSUE #730: Examination Management System
### Is your proposal related to a problem? Please describe.

to manage the Online Exam

### Add any other context or screenshots about the proposal request here.

_No response_

### PR DESCRIPTION
**Pull request by DragonUncaged**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #730 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by Kushal997-das** [comment]
@DragonUncaged We already mentioned after 28th of this month we will not accept any PR . Thanks .

**Comment by DragonUncaged** [comment]
> ept any PR . Thanks .

i was already assigned this issue

**Comment by Kushal997-das** [comment]
@DragonUncaged But the submission date of PR was yesterday .

**Comment by DragonUncaged** [comment]
> @DragonUncaged But the submission date of PR was yesterday .

only 10 pr are there in the repository now. 
okay

**Pull request closed without merging**
