### PR TITLE
Added Calculator in JAVA under Basic Desktop Applications 

### LINKED ISSUE #481: Calculator in JAVA
### Is your feature request related to a problem? Please describe.

A simple calculator application for basic operations like addition, subtraction, division, multiplication, nth root of any number. 
**Additional features**
'=' sign to perform the selected operation and get the output on screen/textfield.
'Delete' to delete one character at a time.
'Reset' to clear the entire screen/textfield (functions as All Clear).

### Describe the solution you'd like.

A small non-scientific calculator built using Java AWT Package to perform basic operations. The program makes use of various object-oriented programming methodologies such as inheritance (inheriting the Frame class and implementing the ActionListener interface), anonymous class, polymorphism (method overriding and overloading), etc.

### Describe alternatives you've considered.

None.

### Add any other context or screenshots about the feature request here.

152673637-31dba5b7-02a0-4be5-af0b-8add53c78d78

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

- Added Calculator under Basic Desktop Applications in JAVA
- Made corresponding changes to README

Fixes #481

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#481)

### CODE REVIEW

**Review by photon149 — APPROVED** [review]
Looks good to me.
@Kushal997-das @prakhar3062 have a look.

**Comment by abhilipsasahoo03** [comment]
Hi @Kushal997-das kindly look into my PR and let me know if any change is required

**Comment by Kushal997-das** [comment]
@photon149 Please check is this PR already exits in other repos or not ?

@abhilipsasahoo03 We found in your last 2 PR'S as a spam , you added same project in multiple repos. this is not acceptable by `GSsOC22` so we removed the tags which we added .  Please make sure this PR is not exits in other Repos !

**Comment by abhilipsasahoo03** [comment]
> @photon149 Please check is this PR already exits in other repos or not ?
> 
> @abhilipsasahoo03 We found in your last 2 PR'S as a spam , you added same project in multiple repos. this is not acceptable by `GSsOC22` so we removed the tags which we added .  Please make sure this PR is not exits in other Repos ! 

Hi @Kushal997-das I think there's a minute confusion. I submitted Instagram Login Page clone to two repositories before it was announced that it was unacceptable (also because I had seen many other participants doing the same). However, I haven't submitted Spotify Landing Page Clone to any other repository. Please let me know why it's marked duplicate.

Also, Calculator in JAVA has not been submitted to any other repository previously.

**Review by Kushal997-das — APPROVED** [review]

**Comment by Kushal997-das** [comment]
@prakhar 3062 Have a look .

**Comment by abhilipsasahoo03** [comment]
@prakhar3062 @Kushal997-das @photon149 let me know if any other change is necessary

**Comment by photon149** [comment]
@Kushal997-das as of this project I don't seem to find any replicas in the GSSOC contributions.
So you can go ahead to check and merge the same.

**Comment by Kushal997-das** [comment]
@abhilipsasahoo03 Done !

**Pull request merged**
