### PR TITLE
Added Random-GIF Generator project

### LINKED ISSUE #1018: Addition of Random-GIF Generator  project
### Is your proposal related to a problem? Please describe.

 It is a web application using React framework to generate and display random GIFs based on user preferences.
It Utilized the GIPHY API to fetch random GIFs in real-time.

### Add any other context or screenshots about the proposal request here.

_No response_

### PR DESCRIPTION
**Pull request by StutiRajput07**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes I have read the contributing guidelines.

### Description

It is a web application using React framework to generate and display random GIFs based on user preferences. It
utilized the GIPHY API to fetch random GIFs in real-time.

Here are the screenshots of my project
image
image

Fixes #1018 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@StutiRajput07  Add `readme.md` file .

**Comment by StutiRajput07** [comment]
@Kushal997-das Made changes

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@StutiRajput07 

Try to add only one folder under this add all files , and `readme.dm` file as well

**Comment by StutiRajput07** [comment]
@Kushal997-das  I made the changes , updated  readme.md file of project as well.

**Pull request closed without merging**
