### PR TITLE
Java Project

### PR DESCRIPTION
**Pull request by gamana29**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #issue_no

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by gamana29** [comment]
"Thrilled to contribute and collaborate on this project! Looking forward to learning and adding value."

**Comment by gamana29** [comment]
"Thrilled to contribute and collaborate on this project! Looking forward to learning and adding value."

**Comment by aimanrazia** [comment]
its great for contributing this!

**Comment by gamana29** [comment]
I recently made a contribution to the project, specifically in the Java codebase, and as I am new to open-source contributions, I would appreciate any feedback or guidance regarding the current status of my contribution.
Could you kindly provide an update on its progress, and let me know if there are any additional steps I need to take to ensure its successful integration?
Thank you for your time and support. I look forward to contributing further!

**Comment by Kushal997-das** [comment]
> gamana29
Hello @gamana29, I’m not clear on your contributions. Are they related to my project? Feel free to reach out to me on LinkedIn.

**Comment by Kushal997-das** [comment]
> gamana29
Hello @gamana29, I’m not clear on your contributions. Are they related to my project? Feel free to reach out to me on LinkedIn.

**Comment by Kushal997-das** [comment]
> > Hello @gamana29, I’m not clear on your contributions. Are they related to my project? Feel free to reach out to me on LinkedIn.
> > Hello @Kushal997-das ,
> > I’ve added my project to your repository as a contribution. This is my first time contributing to a project, so I’m excited to learn and collaborate. Please let me know if any adjustments are needed, and I’d be happy to make changes or improve based on your feedback. Looking forward to working together!

Kindly mention link where you did contribute

**Comment by gamana29** [comment]
https://github.com/Kushal997-das/Project-Guidance/pull/1334/files

**Pull request closed without merging**
