### PR TITLE
Added React Calculator

### LINKED ISSUE #936: React based Calculator in web dev basic
hey there, i would like to add this in the repo can you assign it to me. i would give proper inputs and outputs with installation guide. 
A simple yet useful calculator that would make calc easy.
kindly assign it to me under hacktoberfest.

### PR DESCRIPTION
**Pull request by Balajithegr8**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

yes i have read and worked accordingly.

### Description

Hey there, I have added a calculator in web dev basic using react framework. its easy to use and user friendly.
I have added readme for the file and explained its usage.

Fixes #936 

### Checklist

- [ yes ] I've read the contribution guidelines.
- [ yes ] I've checked the issue list before deciding what to submit.
- [ yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

No.

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Balajithegr8 Hello Deploy the project and add the link in `readme.md` file.

**Comment by Balajithegr8** [comment]
Hey there, I have updated the readme and the deployed link is present in it.

**Review by Kushal997-das — APPROVED** [review]

**Comment by Kushal997-das** [comment]
@Balajithegr8 Is it under hecktoberfest 23 ?

**Comment by Balajithegr8** [comment]
@Kushal997-das yes, its under hacktoberfest 23

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
