### PR TITLE
Atom

### LINKED ISSUE #712: Atom
### Is your feature request related to a problem? Please describe.

An animation of an atom made using HTML5 , CSS3 .

https://user-images.githubusercontent.com/91176055/170092964-0b9ba0d3-44e6-4b9f-9f20-bce28c1440a7.mp4

### Describe the solution you'd like.

I hv made the project.

### Describe alternatives you've considered.

n/a

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by srinjoy-26**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

### Animated atom

https://user-images.githubusercontent.com/91176055/170321141-d96ddbaf-7a30-44c3-9947-b9d878552aa8.mp4

(Write your answer here.)

Fixes #712 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by photon149 — CHANGES_REQUESTED** [review]
@srinjoy-26 Please update your readme file

**Comment by srinjoy-26** [comment]
> @srinjoy-26 Please update your readme file

What kind of updates

**Comment by photon149** [comment]
@srinjoy-26 Add output ss of your work in your readme file

**Comment by srinjoy-26** [comment]
> @srinjoy-26 Add output ss of your work in your readme file

done @photon149

**Review by photon149 — APPROVED** [review]
@srinjoy-26 Great 👍🏻 
Approved from my end.
@Kushal997-das @prakhar3062 have a look

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
