### PR TITLE
added garden planner website

### LINKED ISSUE #1428: Garden Planning Website
# Project-Guidance! 🎊🎈

### Welcome! 🎉
Thank you for opening an issue! Your contributions help us improve the project. If you find this repository useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 

The Garden Planner website is an interactive tool designed for users to create and visualize their ideal garden layout. Users can drag and drop various plants into a grid to plan their garden space while tracking the total cost based on the selected plants. The site allows for saving and loading garden layouts, making it easy to manage and modify designs over time. With a user-friendly interface and responsive design, it aims to enhance the gardening experience for both beginners and enthusiasts.

### 🔍 Priority Level
- [x] High
- [x] Medium
- [ ] Low

### 🏷️ Initiative Participation *(Required)*

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### PR DESCRIPTION
**Pull request by ananyag309**
solved #1428 

- [x] YES
- [ ] NO

### 📝 Description 

The Garden Planner website is an interactive tool designed for users to create and visualize their ideal garden layout. Users can drag and drop various plants into a grid to plan their garden space while tracking the total cost based on the selected plants. The site allows for saving and loading garden layouts, making it easy to manage and modify designs over time. With a user-friendly interface and responsive design, it aims to enhance the gardening experience for both beginners and enthusiasts.

### 🏷️ Initiative Participation *(Required)*

This pull request is associated with the following initiative. Please choose the one you are contributing to:

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Comment by ananyag309** [comment]
@Kushal997-das please review and merge it

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Hi @ananyag309,

I hope this message finds you well. I’m experiencing some issues with the Save Layout, Load Layout, and Download Layout as Image features; they don’t seem to be functioning as expected. It appears that there might be a problem with the project, as it doesn't work as described in the readme.md file.

I’ve attached an image for your reference. Could you please take a look? If everything is working on your end, I would appreciate it if you could provide a working video demonstration in this PR.



check_1548

Thank you!

**Comment by ananyag309** [comment]
https://www.loom.com/share/63af9ee04cfd4383b7dca9b3f8273348?sid=97c8d627-2348-4e72-bcdb-15a6300a26af

working video

**Comment by ananyag309** [comment]
@Kushal997-das i have fixed all changes - when you will click on save a json file will be downloaded and if you want to load the same layout just select the respective json file, and the download as image is also working properly. please review and merge it

**Review by Kushal997-das — APPROVED** [review]

**Comment by ananyag309** [comment]
@Kushal997-das thank you for merging but please add level label too

**Pull request merged**
