### PR TITLE
Mobile Chat Application

### LINKED ISSUE #641: Mobile Chat application
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes I have read it.

- I want to add new a new app which is chatting application which lets users chat with each other at any place 

### Add any other context or screenshots about the proposal request here.

- It is a full fledged application made in flutter with backend part as well, google cloud firestore is used as database.
<p align="center">

</p>

### PR DESCRIPTION
**Pull request by Rahul2570089**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

Chatting application made in flutter used to send messages to other person. It is full fledged applicaiton front-end and back-end (google cloud firestore) integrated.

Fixes #641 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

None

### CODE REVIEW

**Review by photon149 — CHANGES_REQUESTED** [review]
@Rahul2570089 Nicely done 👍🏻 Though just one minor change , rename the directory name to as "Chat Application" rather than Chat-App Master

**Comment by Rahul2570089** [comment]
Okay 👍

**Comment by Rahul2570089** [comment]
Changes done !

**Review by photon149 — APPROVED** [review]
@Rahul2570089 Great
@Kushal997-das @prakhar3062 have a look

**Review by Kushal997-das — APPROVED** [review]
@Rahul2570089 Nice work

**Comment by Kushal997-das** [comment]
@prakhar3062 Have a look

**Pull request merged**
