### PR TITLE
Added Discord Clone files

### LINKED ISSUE #395: Add Discord App Page Clone
### Is your feature request related to a problem? Please describe.

I would like to add a Discord App Page clone that's responsive like the one on desktop machines along with its animations. Example is presented in the screenshot (trimmed due to connections privacy)

### Describe the solution you'd like.

I'm going to make use of:
* HTML
* CSS
* Bootstrap 5

### Describe alternatives you've considered.

Null

### Add any other context or screenshots about the feature request here.

image

Issue made under GSSoC'22 contributions.

### PR DESCRIPTION
**Pull request by XZANATOL**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

- [x] Yes

### Description

Added a Discord App Page clone that's responsive like the one on desktop machines along with its animations.
Fixes #395 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #395 
PR made under GSSoC'22 contributions.

### CODE REVIEW

**Review by photon149 — CHANGES_REQUESTED** [review]
@XZANATOL Please attach a README  file.

**Comment by XZANATOL** [comment]
@photon149 Done.

**Review by photon149 — APPROVED** [review]
@XZANATOL Great Work.
@Kushal997-das @prakhar3062 Have a look

**Review by Kushal997-das — APPROVED** [review]
@XZANATOL great job !!

**Pull request merged**
