### PR TITLE
added Isl translator project

### LINKED ISSUE #817: Title: Audio to Indian Sign Language translation
### Is your feature request related to a problem? Please describe.

Yes, it is a NLP based project which comes under AI.

### Describe the solution you'd like.

I will use Pyaudio for converting voice input into text and various NLP techniques to for processing the language.
Now the words is looked up in database and the videos of particular word is shown to the user

### Describe alternatives you've considered.

-

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by muskan467**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

The conversion of spoken or written English language into Indian sign language is the motive of this project.

Fixes #817 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#817

### CODE REVIEW

**Comment by muskan467** [comment]
What changes I have to do in this @Kushal997-das ?

**Comment by Kushal997-das** [comment]
> What changes I have to do in this @Kushal997-das ?

I haven't seen your PR as there was already one PR exits with your user name so i put on hold this PR will check this and provide you Update .

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@muskan467 Please add good image in `readme.md` file.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@muskan467 Not a proper image that you have added also add this project under basic folder .

**Comment by muskan467** [comment]
@Kushal997-das this is what the project looks like after working. 
OK I'll add it in basic folder

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@muskan467  Hello please write a small description about Isl i mean what's the full from and write it down in `readme.md` file

**Review by Kushal997-das — APPROVED** [review]
@muskan467 Great 👍🏻

**Pull request merged**
