### PR TITLE
Added claymorphic profile card

### LINKED ISSUE #472: Claymorphic profile card
### Is your feature request related to a problem? Please describe.

I want to add a new project to the web - development . Its a claymorphic profile card.

### Describe the solution you'd like.

I want to add a new project to the web - development . Its a claymorphic profile card.

### Describe alternatives you've considered.

No alternatives.

### Add any other context or screenshots about the feature request here.

Screenshot 2022-04-02 172627

### PR DESCRIPTION
**Pull request by srinjoy-26**
Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
Yes I have read the Contributing Guidelines.

Description
 This is a simple profile card with claymorphism effect.
Fixes #472 

Checklist
 I've read the contribution guidelines.
 I've checked the issue list before deciding what to submit.
 I've edited the README.md and link to my code.
Related Issues or Pull Requests
issue #472 

[Contribution made under GSSoC 22']

### CODE REVIEW

**Comment by photon149** [comment]
@srinjoy-26 Please follow PR making guidelines and template to make PRs

**Comment by srinjoy-26** [comment]
> @srinjoy-26 Please follow PR making guidelines and template to make PRs

Like the format of presenting the PR Is wrong ? 
Rest every thing in the project addition is ok?

**Comment by photon149** [comment]
@srinjoy-26 Yes , you can check other PR formats , how they have provided with the formatting.

**Comment by srinjoy-26** [comment]
> @srinjoy-26 Yes , you can check other PRs , how they have provided with the formatting.

please check now

**Review by photon149 — APPROVED** [review]
Looks good to me.
@Kushal997-das have a look

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
