### PR TITLE
Added A Chat Application Using Django

### PR DESCRIPTION
**Pull request by Monalisa-2000**
**### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)?**
Yes, I have gone through the contributing guidelines.

This contribution is part of GirlScript Summer of Code 2022. This is a Web-based Chat application using the Django framework and python backend.

### **Checklist**
 I've read the contribution guidelines.
 I've checked the issue list before deciding what to submit.
 I've edited the README.md and link to my code.

**### Related Issues or Pull Requests**

django 1
django 2
django 3
django 4
django 5

### CODE REVIEW

**Comment by Kushal997-das** [comment]
@Monalisa-2000 There is no file please check your PR .

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Check your PR

**Comment by Monalisa-2000** [comment]
Okay sure can i resubmit it by 28th please from today my exams got started please till that can i get time?

**Comment by Kushal997-das** [comment]
> Okay sure can i resubmit it by 28th please from today my exams got started please till that can i get time?

Yes @Monalisa-2000 Today is the last date to submit.

**Comment by Monalisa-2000** [comment]
Please sir, open it I've completed the project the fault was just that i added that in a format of zip and as I mentioned yesterday itself my exams got ended... Plz a chance of today only sir?

**Comment by Monalisa-2000** [comment]
https://github.com/Monalisa-2000/Project-Guidance/tree/main/Web%20Development/Advanced

I've uploaded it ...hopefully now it's viewable. THANK YOU!

**Comment by Kushal997-das** [comment]
@Monalisa-2000 You just coping everything from the YT videos . Sorry we nit gonna accept this . Thank you .

**Pull request closed without merging**
