### PR TITLE
Added Spotify Landing Page Clone

### LINKED ISSUE #184: Add custom Spotify Landing Page Clone
## 🚀 Feature

I'm Abhilipsa Sahoo and I'm a GSSOC'22 Contributor. I'd like to add a Spotify landing page clone under the Basic Web Development Category. 

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes, I have read the contribution guidelines. 

## Motivation

I built this project as a hands-on practice on HTML and CSS

## Pitch

Landing pages lead customers to a specific product, service or offer and encourage them to take action. This minimalistic landing page can encourage beginners to get a hands-on experience of HTML and CSS which they can later modify and use it for Spotify Clone App.

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes. 

### Description

Adds Spotify Landing Page Clone project under Web Development (Basic) category. 

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Closes #184

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
Hi @Kushal997-das I think there's a minute confusion. I submitted Instagram Login Page clone to two repositories before it was announced that it was unacceptable (also because I had seen many other participants doing the same). However, I haven't submitted Spotify Landing Page Clone to any other repository. Please let me know why it's marked duplicate.

**Comment by Kushal997-das** [comment]
@abhilipsasahoo03 

[Instagram login page ](https://github.com/khushi-purwar/WebDev-ProjectKart/pull/411)

[this one also ](https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/355)

see @abhilipsasahoo03 We are stared checking all PR's and you won't believe people having more than 10+ duplicate PR. 
In my repo i started checking all PR's and if i found any duplicate things then i mark it as `spam` or `duplicate` .
And yeah this it was my mistake your `spotify landing page` don't exits in other repo so i gonna add the `GSSOC22` level don't worry .

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 
> 
> [Instagram login page ](https://github.com/khushi-purwar/WebDev-ProjectKart/pull/411)
> 
> [this one also ](https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/355)
> 
> see @abhilipsasahoo03 We are stared checking all PR's and you won't believe people having more than 10+ duplicate PR. 
> In my repo i started checking all PR's and if i found any duplicate things then i mark it as `spam` or `duplicate` .
> And yeah this it was my mistake your `spotify landing page` don't exits in other repo so i gonna add the `GSSOC22` level don't worry . 

Thank you so much. I was misguided. But, I'll make sure that won't happen again.

**Comment by Kushal997-das** [comment]
@abhilipsasahoo03 No problem keep contribute :)

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 No problem keep contribute :) 

Well, I was curious if y'all are going to take any action against those with 10+ Duplicate PR's?

**Comment by Kushal997-das** [comment]
@abhilipsasahoo03 Actually he opened more than 56+ PR's over multiple repos. and i my repo he opened more than 10+ PR's and except one all are duplicate .

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 Actually he opened more than 56+ PR's over multiple repos. and i my repo he opened more than 10+ PR's and except one all are duplicate .

Okay now I get it why he's on top of the leaderboard with so many PR's

**Comment by Kushal997-das** [comment]
@abhilipsasahoo03 I don't know about other Project-admins but if i found and duplicate PR in my repo so i mark it as `spam` .
Anyways you have 2 duplicate PR one in my repo and other one in other admin repo please make sure don't do this in further .

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 I don't know about other Project-admins but if i found and duplicate PR in my repo so i mark it as `spam` . Anyways you have 2 duplicate PR one in my repo and other one in other admin repo please make sure don't do this in further .

Yes, I'll keep that in mind. Thank you. Also, Calculator in Java is my fresh PR too, so you can merge it without any doubt.

**Pull request merged**
