### PR TITLE
add chatbot

### LINKED ISSUE #1593: Title: add chatbot integration to website
### Initiative (Required)

GSSoC 2024 Extd 🚀

### Is your feature request related to a problem? Please describe.

Add Chatbot Feature to Enhance User Experience

### Describe the solution you'd like.

Add Chatbot Feature to Enhance User Experience

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by amanver45**
#1593

# Project-Guidance! 🎊🎈

### Welcome! 🎉

Thank you for visiting our repository! We're excited to have you here. If you find this project useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 

add chatbot
Screenshot 2024-11-04 233357
Screenshot 2024-11-04 233436

### 🏷️ Initiative Participation *(Required)*

This pull request is associated with the following initiative. Please choose the one you are contributing to:

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Comment by amanver45** [comment]
@Kushal997-das   check pr

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@amanver45 Kindly , deploy the project and send live link here.

**Comment by amanver45** [comment]
@Kushal997-das  ok

**Comment by amanver45** [comment]
https://6729a942864776073628d880--animated-empanada-ce5f3d.netlify.app/ @Kushal997-das

**Review by Kushal997-das — APPROVED** [review]

**Comment by amanver45** [comment]
@Kushal997-das sir lvl 1  I think it's lvl 3 because in other gssoc repo chathot  got lvl 3

**Pull request merged**
