### PR TITLE
Resolving issue #222, addding a beginner Friendly Project using Python and MySQL

### LINKED ISSUE #222: Beginner Friendly Project using Python and MySQL
## 🚀 Feature

I have seen people struggling to find beginner-friendly projects in their initial days, So I suggest adding one such project using Pyhton ad MySQL, which is basically a student assessment card for term exams that takes help of  a true backend and yields a structured report based on multiple options provided.

Can I work on this issue as a part of GSSoC'22 @Kushal997-das ??

### PR DESCRIPTION
**Pull request by AnIkeT126**
### Description

This PR consists of a folder containing the code and a readme having output screenshots pushed into the folder as mentioned in the contributing.md file

Fixes #222 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This PR is  an updated version of #255

### CODE REVIEW

**Review by photon149 — COMMENTED** [review]
@AnIkeT126 Please rename your PR in accordance to your Issue Raised.

**Comment by AnIkeT126** [comment]
@photon149 I have changed the name of the PR.

**Review by photon149 — APPROVED** [review]
Approved from my end.
Over to you @prakhar3062

**Review by prakhar3062 — APPROVED** [review]
@Kushal997-das  approved from my end

**Review by Kushal997-das — APPROVED** [review]
LGTM 👍

**Pull request merged**
