### PR TITLE
Added Parallex Web Design

### LINKED ISSUE #364: Adding Parallex Web Design Using HTML,CSS
### Is your feature request related to a problem? Please describe.

A website that showcases Parallex Web Design

### Describe the solution you'd like.

A website that works on parallex design effect on basis of css and scroll trigger

### Describe alternatives you've considered.

No alternatives

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by rajprem4214**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

### Description

A Parallex Web Design with help of HTML, CSS, JS.

Fixes #364 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

N/A

### CODE REVIEW

**Review by photon149 — COMMENTED** [review]
@rajprem4214 Please add a README file to the folder along with output SS.

**Comment by rajprem4214** [comment]
> @rajprem4214 Please add a README file to the folder along with output SS.

made required changes

**Review by photon149 — CHANGES_REQUESTED** [review]
@rajprem4214 Move demo.png to Images folder as well.

**Comment by rajprem4214** [comment]
> @rajprem4214 Move demo.png to Images folder as well.

done the same.

**Review by photon149 — APPROVED** [review]
Approved from my end.
@Kushal997-das @prakhar3062 have a look

**Review by prakhar3062 — APPROVED** [review]

**Review by photon149 — APPROVED** [review]
Looks good to me.
@Kushal997-das Please check and merge the same.

**Comment by Kushal997-das** [comment]
@rajprem4214 We removed the tags because you added same project in other repos as well.

**Pull request merged**
