### PR TITLE
Resolving issue #222 as a part of GSSoC'22

### LINKED ISSUE #222: Beginner Friendly Project using Python and MySQL
## 🚀 Feature

I have seen people struggling to find beginner-friendly projects in their initial days, So I suggest adding one such project using Pyhton ad MySQL, which is basically a student assessment card for term exams that takes help of  a true backend and yields a structured report based on multiple options provided.

Can I work on this issue as a part of GSSoC'22 @Kushal997-das ??

### PR DESCRIPTION
**Pull request by AnIkeT126**
### Description

This PR consists of a folder containing the code and a readme having output screenshots.

Fixes #222  

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This PR is  an updated version of #234

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@Kushal997-das can you check this now, I have made all the necessary changes in the PR.

**Comment by AnIkeT126** [comment]
@Kushal997-das can you once check this?

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@AnIkeT126 please read the contributing guidelines carefully then Send the PR .

**Comment by AnIkeT126** [comment]
@Kushal997-das I did read the guidelines and followed all the steps mentioned there.
There is no such project that exists like this one with the amalgamation of python and MySQL.
I have created the folder with the name of the project and have sent the same in PR.
I have not added any license.
I am not really understanding what am I expected to do, can you please clear up the air on that?

**Comment by Kushal997-das** [comment]
> @Kushal997-das I did read the guidelines and followed all the steps mentioned there. There is no such project that exists like this one with the amalgamation of python and MySQL. I have created the folder with the name of the project and have sent the same in PR. I have not added any license. I am not really understanding what am I expected to do, can you please clear up the air on that?

@AnIkeT126 Already there are folders present so you no need to add another folder , make sure you add your project under domain like webdevelopment , machine learning ,desktop application . I hope it clears and for  more info visit `Contributing.md` file

**Pull request closed without merging**
