### PR TITLE
Flutter Catalog App

### LINKED ISSUE #393: Add flutter Catalog App
## Application: Catalog App

Catalog App is a demo version of an e-commerce application where one can purchase items.

## Project Level :

Intermediate

## Tech Stack :

- Flutter(2.8.1)
- Dart

## Screenshot :

<p align="center">

<p>

## Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)?
Yes

### PR DESCRIPTION
**Pull request by SomyaRanjanSahu**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

## Application: Catalog App

Catalog App is a demo(UI) version of an e-commerce application where one can purchase items.

Fixes #393

## Project Level :

Intermediate

## Tech Stack :

- Flutter(2.8.1)
- Dart

## Screenshot :

<p align="center">

<p>

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Comment by SomyaRanjanSahu** [comment]
@Kushal997-das Kindly review this PR brother.

**Review by Kushal997-das — APPROVED** [review]

**Comment by Kushal997-das** [comment]
@photon149 have a look !!

**Review by photon149 — APPROVED** [review]
@SomyaRanjanSahu Great UI.
Approved from my end.

**Review by prakhar3062 — APPROVED** [review]
@SomyaRanjanSahu nice work

**Pull request merged**
