### PR TITLE
fix a bug when the user enters a leap year (issue #314) as a part of  GSSoC22

### LINKED ISSUE #314: Bug when the user enters a leap year in Desktop Application/Basic/C++/Calender
## 🐛 Bug Report

When the user enters a leap year as 2020 , month 2 
this appears : 
image

instead of this : 
image

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
Yes , of course 
Give me a chance to contribute under GSSOC'22

### PR DESCRIPTION
**Pull request by salahashraf253**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Yes, of course.)

### Description

fixing the bug which will occur when the user enters a leap year 

Fixes #314

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

Give me a chance to contribute under GSSOC'22

### CODE REVIEW

**Comment by salahashraf253** [comment]
@Kushal997-das , kindly check this pull request .

**Comment by Kushal997-das** [comment]
@salahashraf253 Can you please provide gif of what exactly you fixed ?

**Comment by salahashraf253** [comment]
program after modification 
Screenshot 2022-03-09 145312

program before modification
Screenshot 2022-03-09 145629

**Review by Kushal997-das — APPROVED** [review]

**Comment by Kushal997-das** [comment]
@salahashraf253 Great 👍

**Pull request merged**
