### PR TITLE
Handwritten Digit Recognizer Using ANN

### LINKED ISSUE #507: Title: Handwritten digit recognizer
### Is your feature request related to a problem? Please describe.

yes, it comes under machine learning and data science section.

### Describe the solution you'd like.

I will made a model that will predict the digit using the handwritten image already given.

### Describe alternatives you've considered.

Will implements different models to predict accuracy.

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by AyushJain001**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

I have made a project that recognizes the digit number based on inputed image data. Used neural network to train and predict the result. 

Fixes #507

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

accuracy

### CODE REVIEW

**Comment by AyushJain001** [comment]
Kindly review and merge my code and suggest any improvements if needed.

**Review by photon149 — APPROVED** [review]
@AyushJain001 Nicely Done.
No Duplicity ✅ 
Approved from my end.
@Kushal997-das @prakhar3062 over to you.

**Review by prakhar3062 — APPROVED** [review]

**Review by Kushal997-das — APPROVED** [review]

**Comment by AyushJain001** [comment]
@Kushal997-das may i know that was that error from my end ..so that I can rectify soon.

**Comment by Kushal997-das** [comment]
@AyushJain001 What's error you are talking about ?

**Comment by AyushJain001** [comment]
> @AyushJain001 What's error you are talking about ?

Actually some checks were not passed so initially I thought It was something from my end. Anyway  You may proceed for merging it sounds good

**Pull request merged**
