### PR TITLE
Updated  Readme.md #299 #331

### PR DESCRIPTION
**Pull request by AnonymousCodes911**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
Yes
### Description

Added Readme.md with final fixes: 
-fixed the gif link
-made the readme more presentable
-made a separate folder for the same [Here](https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application/Basic/Python) 
 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixed the issues that were mentioned under PRs #299, and corrected the following issues that were raised by @Kushal997-das

### CODE REVIEW

**Comment by Kushal997-das** [comment]
@AnonymousCodes911 You have already one open PR please close that one.

**Comment by Kushal997-das** [comment]
@AnonymousCodes911 Please mention the issue that you fixes.

**Comment by AnonymousCodes911** [comment]
@Kushal997-das , updated the initial comment, thank you!

**Comment by Kushal997-das** [comment]
> @AnonymousCodes911 Please mention the issue that you fixes.

Mention the issue number that you fixes!!

**Comment by AnonymousCodes911** [comment]
-Added Readme.md with final fixes,
-fixed the gif link
-made the readme more presentable

fixed #299 #331

**Comment by Kushal997-das** [comment]
> -Added Readme.md with final fixes, -fixed the gif link -made the readme more presentable
> 
> fixed #299 #331

> ### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
> Yes
> 
> ### Description
> Added Readme and GIF Fixes #331
> 
> ### Checklist
> * [x]  I've read the contribution guidelines.
> * [x]  I've checked the issue list before deciding what to submit.
> * [x]  I've edited the `README.md` and link to my code.
> 
> ## Related Issues or Pull Requests
> Added Readme.md with final fixes, -fixed the gif link -made the readme more presentable

Man add here what you are fixing , fixing means issue only not PR .

**Comment by AnonymousCodes911** [comment]
@Kushal997-das, I hope this serves the purpose I have updated the initial comment, sorry for the inconvenience caused!

> ### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
> Yes
> 
> ### Description
> Added Readme.md with final fixes: -fixed the gif link -made the readme more presentable -made a separate folder for the same [Here](https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application/Basic/Python)
> 
> ### Checklist
> * [x]  I've read the contribution guidelines.
> * [x]  I've checked the issue list before deciding what to submit.
> * [x]  I've edited the `README.md` and link to my code.
> 
> ## Related Issues or Pull Requests
> Fixed the issues that were mentioned under PRs #299 and #331, and corrected the following issues that were raised by @Kushal997-das

**Comment by Kushal997-das** [comment]
@AnonymousCodes911 Don't you understand what i'm trying to say , i said you have to mention the issue number that you fixes , like in your case the issue number is #299

**Comment by AnonymousCodes911** [comment]
Thats what  wrote there right? #299 and #331, where exactly i have to write that please be specific now, thankyou

**Comment by Kushal997-das** [comment]
> Thats what wrote there right? #299 and #331, where exactly i have to write that please be specific now, thankyou

#331 you should remove since #331 it is a PR not issue . NO need to mention  Issue and PR .

Your issue number- 299 - Mention this only .
Closed PR number- 331 - Remove this one.

**Comment by AnonymousCodes911** [comment]
@Kushal997-das  is it fine now? 
sorry for the inconvenience and thank you for being patient!

**Review by Kushal997-das — APPROVED** [review]
@photon149 check this !

**Review by photon149 — APPROVED** [review]
Looks fine to me.
@Kushal997-das merge the same in case of no conflicts.

**Pull request merged**
