### PR TITLE
TicTacToe Game

### LINKED ISSUE #415: TicTacToe Android ( Kotlin )
## Application: Tic-Tac-Toe

Tic-Tac-Toe App is a basic level android project as a gaming application where one can play along with his friend.

## Project Level :

Basic

## Tech Stack :

- Android Studio
- Kotlin (203-1.6.10-release-923-AS7717.8)

## Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)?
Yes

## Screenshot :

<p align="center">

<p>

### PR DESCRIPTION
**Pull request by iyashkr**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

Tic-Tac-Toe App is a basic level android project as a gaming application where one can play along with his friend.

Fixes #415

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Screenshot :

<p align="center">

<p>

### CODE REVIEW

**Comment by iyashkr** [comment]
@Kushal997-das kindly review this pr.

**Review by Kushal997-das — COMMENTED** [review]
@iyashkr Is this is a android app ? using `kotlin` language .

**Comment by iyashkr** [comment]
@Kushal997-das yes it's an android app using Kotlin as the programming language

**Review by Kushal997-das — APPROVED** [review]
@iyashkr Good 👍 

LGTM 💯 

@photon149 have  a look !

**Comment by photon149** [comment]
Looks good to me.
@prakhar3062 have a look.

**Review by photon149 — APPROVED** [review]
Approved from my end.
@Kushal997-das

**Review by prakhar3062 — APPROVED** [review]

**Pull request merged**
