### PR TITLE
Esports Website

### LINKED ISSUE #634: NEW project
### Is your feature request related to a problem? Please describe.

It is a new web development project with basic frontend completed. It depicts the landing page of an esports company.

### Describe the solution you'd like.

I would like to add it to the repo.

### Describe alternatives you've considered.

With this project as part of a repo here, it can be developed much more.

### Add any other context or screenshots about the feature request here.

image

### PR DESCRIPTION
**Pull request by shrutiverma13**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes.

### Description

Added a new web development project, a website on esports. A catchy landing page with esports visuals, semantic code and image carousals.

Fixes #634

### Checklist

- [x] I've read the contribution guidelines.

- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This PR is for the same.

### CODE REVIEW

**Comment by photon149** [comment]
@shrutiverma13 Please correctly mention the issue number , there is a typo

**Comment by shrutiverma13** [comment]
> @shrutiverma13 Please correctly mention the issue number , there is a typo

done

**Review by photon149 — CHANGES_REQUESTED** [review]
@shrutiverma13 a few changes need to be done.
- Give a more appropriate PR title "ESports Website"
- Create a README file for your project.
- Put all the images in a particular folder

**Comment by shrutiverma13** [comment]
> @shrutiverma13 a few changes need to be done.
> 
> * Give a more appropriate PR title "ESports Website"
> * Create a README file for your project.
> * Put all the images in a particular folder

done, please review

**Review by photon149 — APPROVED** [review]
@shrutiverma13 Good Work
Approved.
@Kushal997-das have a look

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
