### PR TITLE
Food Menu cart

### LINKED ISSUE #842: Title: JS Shopping Cart
## Adding a new basic web development project: JS Shopping Cart

A simple one-page shopping cart website built using HTML, CSS, JavaScript, and jQuery. The website features a user-friendly interface for adding items to the cart. The total cost is automatically calculated and displayed on the page as items are added. The website uses JavaScript and jQuery to update the cart and calculate the total cost dynamically.

### Add any other context or screenshots about the proposal request here.

sc1

sc2

### PR DESCRIPTION
**Pull request by manisha-nair28**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description
A simple one-page shopping cart website built using HTML, CSS, JavaScript, and jQuery. The website features a user-friendly interface for adding items to the cart. As items are added, the total cost is automatically calculated and displayed on the page. The website uses JavaScript and jQuery to update the cart and calculate the total cost dynamically.

Fixes #842

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue no #842

### CODE REVIEW

**Review by Kushal997-das — COMMENTED** [review]
@manisha-nair28 Why the name is JS shopping card ?

**Comment by manisha-nair28** [comment]
@Kushal997-das It's a shopping Cart. Should I change it to 'Food menu cart'??

**Comment by Kushal997-das** [comment]
@manisha-nair28 Yes please change it

**Comment by manisha-nair28** [comment]
@Kushal997-das done

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Not a good description , please write it n professional way . Do not mention any techs in description .

Description

**Comment by manisha-nair28** [comment]
@Kushal997-das Done. Please Check

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
