### PR TITLE
Contact Page Basic Terminologies rectified

### PR DESCRIPTION
**Pull request by Ankit-kumar-khatri**
Got eyes upon some of the basic terminologies in the application which was supposed to be rectified .
I hope we will be contributing to this project for sure  . Thanks for sharing this project .

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Ankit-kumar-khatri Hello Kindly open the issue first then Create a PR  for better understanding follow [this](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) one.

**Comment by Ankit-kumar-khatri** [comment]
PR is already opened for this issue ?

**Comment by Kushal997-das** [comment]
#894

**Review by Kushal997-das — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
