### PR TITLE
Added Expense Tracker App

### PR DESCRIPTION
**Pull request by Sulagna-Dutta-Roy**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #issue_no
#519 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
I've added the project in the web development Intermediate section.

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly review my PR. Please tell any changes needed for it

**Review by Kushal997-das — APPROVED** [review]
@photon149 Have a look .

**Comment by Kushal997-das** [comment]
@photon149

**Review by photon149 — APPROVED** [review]
@Sulagna-Dutta-Roy Good Work
No Duplicity ✔️ 
Approved from my end.
@Kushal997-das Please review and merge once .

**Pull request merged**
