### PR TITLE
Indian Flag using python

### PR DESCRIPTION
**Pull request by sakshigupta08**

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@sakshigupta08 Please first fetch from original repo then send PR.

**Comment by Kushal997-das** [comment]
> @sakshigupta08 Please first fetch from original repo then send PR.

See you don't have recent update repo with you.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Fetch first :)

**Review by SamarpanCoder2002 — CHANGES_REQUESTED** [review]
Please delete the python/basic folder under project guidance...... That mentioned in picture....

**Review by SamarpanCoder2002 — CHANGES_REQUESTED** [review]
Pls add a gif file or image in readme of the indian flag project  ......   This will help visitors to understand about your project

**Review by SamarpanCoder2002 — CHANGES_REQUESTED** [review]
Please add gif or image or video in readme file of your project ..... (Gif or image recommended due to smaller size)..... Pls make changes here

**Comment by TawfikYasser** [comment]
Hi @sakshigupta08 

I can help you if you still stuck

If you still have a problem with fetching the repository:

* After forking it, Open CMD or git bash and type : `git clone <forked-repo-link>`
* then cd to the repository directory and type: `git remote add upstream <original-repo-link>`
* then type : `git fetch upstream`
* then type: `git merge upstream/main`

After that make your changes and push them and open a PR.

I hope this helps you @sakshigupta08 

If I am wrong, please correct me @Kushal997-das  @SamarpanCoder2002 

Thanks

**Comment by Kushal997-das** [comment]
> Hi @sakshigupta08
> 
> I can help you if you still stuck
> 
> If you still have a problem with fetching the repository:
> 
> * After forking it, Open CMD or git bash and type : `git clone <forked-repo-link>`
> * then cd to the repository directory and type: `git remote add upstream <original-repo-link>`
> * then type : `git fetch upstream`
> * then type: `git merge upstream/main`
> 
> After that make your changes and push them and open a PR.
> 
> I hope this helps you @sakshigupta08
> 
> If I am wrong, please correct me @Kushal997-das @SamarpanCoder2002
> 
> Thanks

@TawfikYasser 👍

**Comment by Kushal997-das** [comment]
Are you gonna change this ? @sakshigupta08

**Comment by TawfikYasser** [comment]
Hi @Kushal997-das ,Can I help @sakshigupta08 by uploading the project?

**Comment by sakshigupta08** [comment]
> Hi @Kushal997-das ,Can I help @sakshigupta08 by uploading the project?

Yes please

**Comment by TawfikYasser** [comment]
> > Hi @Kushal997-das ,Can I help @sakshigupta08 by uploading the project?
> 
> Yes please

Okay i will do that tomorrow @sakshigupta08

**Comment by Kushal997-das** [comment]
> Hi @Kushal997-das ,Can I help @sakshigupta08 by uploading the project?

No because if you help then she is unable to learn the things like how to do work in open source. 
What project guidance motive is we want to help people in open source and also help them by providing projects ideas as well. 
I hope it make sense. 
P. S. You can tell her what to do but you can't do her work.

**Comment by TawfikYasser** [comment]
Okay @Kushal997-das Thanks

**Pull request closed without merging**
