### PR TITLE
sticky notes added 

### LINKED ISSUE #343: New Simple Project - STICKY NOTES
## 🚀 Feature
A simple project using HTML, CSS, JavaScript which allows users to add their to-dos , and  they can delete one when done with their task.

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
Yes
## Pitch
Useful for people, they can add the task and delete it on completion.

### PR DESCRIPTION
**Pull request by isha614**
Fixes #343

### CODE REVIEW

**Comment by photon149** [comment]
@isha614 Please follow the Template to create the PR.
Also , do the following changes :
- Add Comments to your code
- Attach a README file , with output SS in the same folder

**Comment by Kushal997-das** [comment]
@isha614Are you going to do the changes ? Or else your PR will close .

**Comment by isha614** [comment]
> @isha614Are you going to do the changes ? Or else your PR will close .

Yes I will do it today. sorry for being late

**Comment by Kushal997-das** [comment]
@isha614 Did you opened new PR for same project  #406 ?

**Comment by isha614** [comment]
> @isha614 Did you opened new PR for same project #406 ?

It was already opened, when you told changes to be done it was with that #406 PR

**Comment by isha614** [comment]
> > > @isha614 Did you opened new PR for same project #406 ?
> > 
> > 
> > It was already opened, when you told changes to be done it was with that #406 PR
> 
> Then close this one from your side .

I have closed that.

**Comment by Kushal997-das** [comment]
@isha614 You should close the PR but not the new one as this PR #384 is old one so close this one make sense ?

**Comment by Kushal997-das** [comment]
#406 reopen this .

**Pull request closed without merging**
