### PR TITLE
Medical Charges Analysis for Smokers and Non-smokers

### PR DESCRIPTION
**Pull request by suy1968**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Medical Charges Analysis for Smokers and Non-smokers

### Description

This Data analysis and data visualization project consists of the fact that the average medicine charges can be changed for smokers and non-smokers.
### Conclusion :
1.The impact of smoking on medical care use was examined in a 30-month prospective population-based cohort study in Japan (N = 43 408).

2.Male smokers incurred 11% more medical costs than ‘never smokers’ but for female smokers and never smokers the costs were almost the same.

3.This difference was mainly attributable to the increased use of inpatient medical care among smokers, especially in males, where per month cost of inpatient care was 33% higher in smokers.

### Checklist

- [x] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#169

### CODE REVIEW

**Comment by suy1968** [comment]
Please check @SamarpanCoder2002 @Kushal997-das

**Review by SamarpanCoder2002 — APPROVED** [review]
LGTM  @suy1968 ... you can merge @Kushal997-das ....

**Comment by Kushal997-das** [comment]
> LGTM @suy1968 ... you can merge @Kushal997-das ....



> LGTM @suy1968 ... you can merge @Kushal997-das ....

Thanks @SamarpanCoder2002

**Comment by abhisheks008** [comment]
@Kushal997-das  this project is copied from the following project, even the README.md file is barely copied. The documentation, codebase and even the images the copied from the following project which was uploaded way back in October, 2020.

Main project repository : https://github.com/abhisheks008/Medicine-Charges-for-Smokers-and-Non-Smokers-Analysis

This is really against the ethics of Open Source. PA please take a look into that:)

**Comment by Kushal997-das** [comment]
> @Kushal997-das this project is copied from the following project, even the README.md file is barely copied. The documentation, codebase and even the images the copied from the following project which was uploaded way back in October, 2020.
> 
> Main project repository : https://github.com/abhisheks008/Medicine-Charges-for-Smokers-and-Non-Smokers-Analysis
> 
> This is really against the ethics of Open Source. PA please take a look into that:)

Sorry for the inconvenienced cost . Yes this is against the ethics . Gonna delete this and in future we never accept these types of folks PR . Thanks for the info. 👍

**Comment by abhisheks008** [comment]
Thanks for the needful work! 👍

**Comment by Kushal997-das** [comment]
> Thanks for the needful work! 👍

@abhisheks008 Done 👍

**Comment by Kushal997-das** [comment]
@suy1968 Don't send again PR here , this is the warning from our side. You just spoil developer community nothing else .

**Pull request merged**
