### PR TITLE
Contact Form

### PR DESCRIPTION
**Pull request by UG-SEP**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

Added the Contact Form Project which is basically Form Validation in Web Development/Basic Folder

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

closes: #178 
Hope so everything is perfect😊

### CODE REVIEW

**Comment by UG-SEP** [comment]
@SamarpanCoder2002, @Kushal997-das 
Please review it

**Review by SamarpanCoder2002 — CHANGES_REQUESTED** [review]
You are 7 commits behind the main. Fetch it and make it even. @UG-SEP

**Review by Kushal997-das — APPROVED** [review]
@UG-SEP Cool 💯

**Comment by UG-SEP** [comment]
@Kushal997-das 
Please add Hacktoberfeast-accepted as it is under hacktoberfeast
Thanks

**Pull request merged**
