### PR TITLE
project count updated

### LINKED ISSUE #278: Project Counting !!
**Update the project counting !!**

InkedBug1_LI

### PR DESCRIPTION
**Pull request by itsAftabAlam**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

Project count updated

Fixes #278 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

### CODE REVIEW

**Comment by itsAftabAlam** [comment]
i hope this fixes the issue

**Comment by Kushal997-das** [comment]
> i hope this fixes the issue

No project count flase it's more than 76 projects please check carefully

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@itsAftabAlam

**Comment by itsAftabAlam** [comment]
i rechecked again and even counted latest commit, it still goes to a total of 80

**Comment by Kushal997-das** [comment]
> @Kushal997-das i rechecked again and even counted latest commit, it still goes to a total of 80

Then changes to recent update .

**Comment by itsAftabAlam** [comment]
@Kushal997-das project count updated to it's latest

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
