### PR TITLE
Feat: Code Enhancements

### PR DESCRIPTION
**Pull request by TawfikYasser**
Hi

This PR to add some code enhancements for `Hotel Reservation System` project.

Thanks.

### CODE REVIEW

**Review by Kushal997-das — APPROVED** [review]
Great @TawfikYasser Send PR again.

**Comment by TawfikYasser** [comment]
I think it is now synced with original @Kushal997-das

**Comment by Kushal997-das** [comment]
@TawfikYasser it's says "This branch is 7 commits behind Kushal997-das:main."

**Comment by TawfikYasser** [comment]
I don’t know what is the problem, Before i open a PR, I have sync the repo to be sure it fetched.

**Comment by TawfikYasser** [comment]
Okay You can close the PR and I will open one again

**Pull request closed without merging**
