### PR TITLE
Added Weather Forecast web app (Made using React) and OpenAI Voice Chat Bot

### PR DESCRIPTION
**Pull request by Mysterious786**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #issue_no

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by Mysterious786** [comment]
please view it

**Comment by Kushal997-das** [comment]
@Mysterious786 Will check

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Mysterious786  Project should be added in same folder if it's web development project and add it on that folder and if it's ML or AI project then add it on their respective folders.

**Comment by Mysterious786** [comment]
Done Please view it

**Review by Kushal997-das — COMMENTED** [review]
@Mysterious786 Don't you understand what i'm saying check my message once carefully then send PR

**Pull request closed without merging**
