### PR TITLE
Travel management

### LINKED ISSUE #713: Travel Management System
### Is your proposal related to a problem? Please describe.

Travel Management System
- book hotel
- book trip

### Add any other context or screenshots about the proposal request here.

_No response_

### PR DESCRIPTION
**Pull request by DragonUncaged**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #713

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by photon149 — APPROVED** [review]
@DragonUncaged Nice work .
Approved.
@Kushal997-das @prakhar3062

**Comment by Kushal997-das** [comment]
@DragonUncaged Is this a website ? or a desktop application

**Comment by DragonUncaged** [comment]
> @DragonUncaged Is this a website ? or a desktop application

Website

**Comment by Kushal997-das** [comment]
> > @DragonUncaged Is this a website ? or a
> 
> it is Website.
> 
> So i will add it in advanced web development

So why you add this one in desktop ? 
No just add this one under intermediate(web development)

**Comment by DragonUncaged** [comment]
> > > @DragonUncaged Is this a website ? or a
> > 
> > 
> > it is Website.
> > So i will add it in advanced web development
> 
> So why you add this one in desktop ? No just add this one under intermediate(web development)

Added

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
