### PR TITLE
Project JTM Added

### PR DESCRIPTION
**Pull request by TawfikYasser**
Hi,

This PR associated with issue #70

I hope this helps other developers

Thanks

### CODE REVIEW

**Review by SamarpanCoder2002 — CHANGES_REQUESTED** [review]
Your folder is locked..not opening..actually, you initialized git in this folder...don't worry, copy file contents from this folder to the other folder and delete this folder...Do that locally and push it to the remote and then make a pull request...

**Comment by TawfikYasser** [comment]
> Your folder is locked..not opening..actually, you initialized git in this folder...don't worry, copy file contents from this folder to the other folder and delete this folder...Do that locally and push it to the remote and then make a pull request...

Okay, I can not understand why this happened really!
I’m trying to fix it.

**Comment by SamarpanCoder2002** [comment]
> > Your folder is locked..not opening..actually, you initialized git in this folder...don't worry, copy file contents from this folder to the other folder and delete this folder...Do that locally and push it to the remote and then make a pull request...
> 
> Okay, I can not understand why this happened really!
> I’m trying to fix it.

As I say...just follow the steps....this is happening due to the initialization of git in that folder...copy contents to another folders to fix that bug..

**Comment by TawfikYasser** [comment]
Okay @SamarpanCoder2002  Change done.

Sorry for the error

**Comment by SamarpanCoder2002** [comment]
> Okay @SamarpanCoder2002 Change done.
> 
> Sorry for the error

Not a problem at all...It also happens to me many times...Thanks for your time..

**Comment by TawfikYasser** [comment]
> > Okay @SamarpanCoder2002 Change done.
> > Sorry for the error
> 
> Not a problem at all...It also happens to me many times...Thanks for your time..

:) @SamarpanCoder2002

**Review by SamarpanCoder2002 — COMMENTED** [review]
Looks good to me...your projects really inspire us...Thanks for your interest..

**Comment by TawfikYasser** [comment]
> Looks good to me...your projects really inspire us...Thanks for your interest..

Thanks a lot. :)

**Pull request merged**
