### PR TITLE
Added ATS SCORE RECOGNIZER

### LINKED ISSUE #1514: Custom Issue Report Add ATS-SCORE-RECOGNIZER Project to Web Development Section
# Project-Guidance! 🎊🎈

### Welcome! 🎉
Thank you for opening an issue! Your contributions help us improve the project. If you find this repository useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

Copy code
### Issue Title
Add ATS-SCORE-RECOGNIZER Project to Web Development Section

### Description
I would like to propose adding the **ATS-SCORE-RECOGNIZER** project to the web development section as an intermediate-level project.

### Project Overview
The ATS Score Recognizer is a tool designed to automatically extract and recognize scores from various documents, such as resumes and job applications. It leverages advanced optical character recognition (OCR) and machine learning techniques to streamline the recruitment process by providing accurate score extraction.

### Technologies Used
- **Python**: The core language used for development.
- **Flask/Django** (if applicable): For web framework.
- **OpenCV/Pytesseract** (if applicable): For OCR capabilities.
- **HTML/CSS/JavaScript**: For the frontend interface.

### Features
- **OCR Capabilities**: Utilizes state-of-the-art OCR to read text from images and PDFs.
- **Score Extraction**: Efficiently identifies and extracts relevant scores from documents.
- **User-Friendly Interface**: Easy-to-use interface for uploading documents and viewing results.
- **Multi-Format Support**: Works with multiple document formats including PDF, JPEG, and PNG.

### 🔍 Priority Level
- [ ] High
- [x] Medium
- [ ] Low

### 🏷️ Initiative Participation *(Required)*

- [x] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [] ❄️ Script Winter of Code (SWoC)
- [] ⛄ Winter of Blockchain (WoB)
- [x] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### 💬 Next Steps:

You can expect a response within [4 days].

### PR DESCRIPTION
**Pull request by Baig-fatema**
# Project-Guidance! 🎊🎈

### Welcome! 🎉

Thank you for visiting our repository! We're excited to have you here. If you find this project useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### Related Issue
Resolves #1514 - Added ATS SCORE RECOGNIZER functionality

### Description
This pull request introduces the ATS Score Recognizer feature, which enhances our application's ability to interpret and evaluate ATS scores from various input formats. This addition aims to streamline the user experience for applicants and recruiters alike.

### Key Features
- **Score Parsing**: The recognizer can accurately parse ATS scores from both plain text and JSON formats.
- **Error Handling**: Robust error handling to manage unexpected input scenarios.
- **Unit Tests**: Comprehensive tests added to ensure reliability and accuracy of the score recognition process.

### Implementation Details
- Created a new module `ats_score_recognizer.py` responsible for the core functionality.
- Updated the existing `utils.py` to include helper functions that support the new feature.
- Modified the main application flow to integrate the ATS Score Recognizer seamlessly.

### Testing
- Unit tests have been added to `test_ats_score_recognizer.py` to validate the new feature.
- Manual testing performed to ensure proper integration and functionality across different use cases.

### Documentation
- Updated the README.md to include instructions on using the ATS Score Recognizer.
- Added a new section in the documentation regarding the supported formats and examples.

### Additional Notes
- Please review the implementation and test coverage.
- Feedback on the user experience of the new feature is highly appreciated.

### Checklist
- [x] Code is clean and follows project conventions.
- [x] Unit tests have been added.
- [x] Documentation has been updated.
- [x] Linked issue is referenced.

---

Thank you for considering this pull request!

### 🏷️ Initiative Participation *(Required)*

This pull request is associated with the following initiative. Please choose the one you are contributing to:

- [x] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [x] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [x] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Comment by Baig-fatema** [comment]
@Kushal997-das i request to please review it and add label Hacker to be fest and level 2.

**Comment by Baig-fatema** [comment]
1. @Kushal997-das  I request you to please Review it.
2. Merge it.
4. Add Labels:

- level2
- gssoc-etd 
- hacker to be fest

**Comment by Baig-fatema** [comment]
@Kushal997-das  Please Review it.

**Review by Kushal997-das — COMMENTED** [review]
Hi @Baig-fatema,

I noticed that a similar issue was created in another repository, which seems to violate our established rules. I wanted to bring this to your attention for your reference.

Thanks for understanding!

**Pull request closed without merging**
