### PR TITLE
Added Markdown Previewer

### LINKED ISSUE #1129: Markdown Previewer
I would like to add under Web Development, Markdown Previewer which takes the markdown code and renders HTML element. Please assign me this under GSSOC'2024

### PR DESCRIPTION
**Pull request by AmrutaJayanti**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

### Description

I added `Markdown Previewer`

Fixes #1129 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

N/A

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@AmrutaJayanti, please make the following changes:

Deploy the project and then add the hosted link in the readme.md file.
Update the project name in the main readme.md file [here](https://github.com/Kushal997-das/Project-Guidance/blob/main/Web%20Development/README.md).

**Comment by AmrutaJayanti** [comment]
@Kushal997-das I have made the changes. Please approve

**Comment by AmrutaJayanti** [comment]
@Kushal997-das I updated my JS .

Screenshot 2024-06-19 141739

My Markdown Previewer now can handle tables ,images ,links .

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@AmrutaJayanti Hi, update the things in your deploy [link](https://markdown-kohl.vercel.app/)

**Comment by AmrutaJayanti** [comment]
@Kushal997-das I have updated the link.

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
