### PR TITLE
E-Commerce Fashion Website

### LINKED ISSUE #582: E-Commerce Website
### Is your feature request related to a problem? Please describe.

I want to an E-Commerce Website Project on this repo as there is nothing on it .

### Describe the solution you'd like.

I will be using HTML,CSS,JS,Bootstrap to make it. And my code will be responsive.

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

I haven't made it till now

### PR DESCRIPTION
**Pull request by Mrjoy832**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

- Yes

### Description

It's a **E-Commerce Website of Fashion Cloths** made using **HTML,CSS,JAVASCRIPT, BOOTSTRAP** . The Code is responsive and it has few number of functionalities .
- Searching Product
- Add to Cart
- About Us 
- Contact Us
- Latest Product 
- Payment Integration

Fixes #582 

### Checklist

- [X] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

I have updated main readme of Web -Dev Folder attaching Demo link of this website

https://user-images.githubusercontent.com/77873383/166175505-9d3246db-ec62-4130-a518-6c21cadb1f62.mp4

### CODE REVIEW

**Comment by Mrjoy832** [comment]
@Kushal997-das , Hey.. I am contributing to this project for 1st time , please check the PR and I also updated Readme of Web-Dev with working Link of this Website

**Review by photon149 — CHANGES_REQUESTED** [review]
@Mrjoy832 Nicely done.
Though you also need to attach a README file within your project , which explains a little bit about your project alongside output SS/vdo/gif.
Please do these changes and revert.

**Comment by Mrjoy832** [comment]
> @Mrjoy832 Nicely done.
> Though you also need to attach a README file within your project , which explains a little bit about your project alongside output SS/vdo/gif.
> Please do these changes and revert.

I also add another readme into my project folder please check that

**Review by photon149 — APPROVED** [review]
Yup , fair enough my bad.
Though just a suggestion , from future onwards , create subfolders in your directory , so as for easy navigation and code understanding for you as well as a third person's perspective who might look at your code.
No Duplicity ✅ 
Approved from my end.
@Kushal997-das @prakhar3062 over to you.

**Comment by Mrjoy832** [comment]
> Yup , fair enough my bad. Though just a suggestion , from future onwards , create subfolders in your directory , so as for easy navigation and code understanding for you as well as a third person's perspective who might look at your code. No Duplicity ✅ Approved from my end. @Kushal997-das @prakhar3062 over to you.

Okay I will do so from next time

**Comment by Mrjoy832** [comment]
@Kushal997-das, Kindly check it

**Review by prakhar3062 — APPROVED** [review]

**Comment by Mrjoy832** [comment]
> @Kushal997-das, Kindly check it

@photon149  when it will be checked by others ? 🙃

**Review by Kushal997-das — APPROVED** [review]

**Comment by Kushal997-das** [comment]
> @Kushal997-das, Kindly check it

Done.

**Pull request merged**
