### PR TITLE
Update Desktop Application README.md

### PR DESCRIPTION
**Pull request by TawfikYasser**
Add the Notification REST API Project

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Please add one image or gif @TawfikYasser

**Comment by TawfikYasser** [comment]
> Please add one image or gif @TawfikYasser

Okay

**Comment by TawfikYasser** [comment]
@Kushal997-das  Done

**Comment by Kushal997-das** [comment]
> > Please add one image or gif @TawfikYasser
> 
> Okay

@SamarpanCoder2002  @TawfikYasser  If we remove the gif or images from desktop application it's better ,see the drawback of adding gif in [This readme file ](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md) are : 

1. All gif or images size are not same .
2. Few contributor are not adding gif or images.
3. When already gif or images are present then i think no need to add gif or images in [this](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md)
4. Without gif or images it's better for readable purpose .

**Comment your opinions guys !**

**Comment by TawfikYasser** [comment]
> > > Please add one image or gif @TawfikYasser
> > 
> > 
> > Okay
> 
> @SamarpanCoder2002 @TawfikYasser If we remove the gif or images from desktop application it's better ,see the drawback of adding gif in [This readme file ](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md) are :
> 
> 1. All gif or images size are not same .
> 2. Few contributor are not adding gif or images.
> 3. When already gif or images are present then i think no need to add gif or images in [this](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md)
> 4. Without gif or images it's better for readable purpose .
> 
> **Comment your opinions guys !**

I’m totally agree with you, [This File](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md) doesn’t need images or gifs, I think it’s better without images or gifs. @Kushal997-das

**Comment by Kushal997-das** [comment]
> > > > Please add one image or gif @TawfikYasser
> > > 
> > > 
> > > Okay
> > 
> > 
> > @SamarpanCoder2002 @TawfikYasser If we remove the gif or images from desktop application it's better ,see the drawback of adding gif in [This readme file ](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md) are :
> > 
> > 1. All gif or images size are not same .
> > 2. Few contributor are not adding gif or images.
> > 3. When already gif or images are present then i think no need to add gif or images in [this](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md)
> > 4. Without gif or images it's better for readable purpose .
> > 
> > **Comment your opinions guys !**
> 
> I’m totally agree with you, [This File](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md) doesn’t need images or gifs, I think it’s better without images or gifs. @Kushal997-das

Yes true @TawfikYasser 👍🏻  @SamarpanCoder2002 Wait for his opinion .

**Review by Kushal997-das — APPROVED** [review]
:)

**Comment by SamarpanCoder2002** [comment]
> > > Please add one image or gif @TawfikYasser
> > 
> > 
> > Okay
> 
> @SamarpanCoder2002 @TawfikYasser If we remove the gif or images from desktop application it's better ,see the drawback of adding gif in [This readme file ](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md) are :
> 
> 1. All gif or images size are not same .
> 2. Few contributor are not adding gif or images.
> 3. When already gif or images are present then i think no need to add gif or images in [this](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md)
> 4. Without gif or images it's better for readable purpose .
> 
> **Comment your opinions guys !**

Okay..no prb, I will remove gifs or images under readme of desktop application

**Pull request merged**
