### PR TITLE
Covid-19 Timeseries Analysis with multiple model

### LINKED ISSUE #193: Covid-19 Timeline Analysis with multiple model
## 🚀 Feature

We can use different Timeline model so that to get multiple model usage .

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

## Motivation
I would like to work on this under GSSOC'22
It helps to learn and guide about various model use in timeline analysis .

## Pitch

Covid-19 third wave analysis using multiple models to test which one suits the best among the all . Basically to find the best model.

### PR DESCRIPTION
**Pull request by shivam-s16**
Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)?
Yes

Fixes #193

Description
We can use different Timeline models to get multiple model usage.

Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

Related Issues or Pull Requests
Covid-19 third wave analysis using multiple models to test which one suits the best among them all. Basically to find the best model.

### CODE REVIEW

**Comment by shivam-s16** [comment]
@Kushal997-das Sir I am resenting the pull request please check it and if there is some correction please let me know.
Thank you

**Comment by prakhar3062** [comment]
Make title of pr similar to your title of project

**Review by prakhar3062 — APPROVED** [review]
@photon149 okay from my side

**Review by Kushal997-das — APPROVED** [review]
@shivam-s16 LGTM 👍 
@photon149 over to you !!

**Review by photon149 — APPROVED** [review]
Approved from my end.
@Kushal997-das please merge the same in case of no conflicts.

**Pull request merged**
