### PR TITLE
Adding React E-Commerce App

### LINKED ISSUE #772: Title: React E-Commerce App
### Is your proposal related to a problem? Please describe.

 Add a React E-Commerce App for Watches-iiwotshi 

### Add any other context or screenshots about the proposal request here.

_No response_

### PR DESCRIPTION
**Pull request by ARCHITABHATTAD**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

### Description

This is an React  E-Commerce Application made with react framework.
There are various components in the application and the data for the same is stored in data.jsx

Additional dependencies:
1. Yarn
2. Yarn styled components
3. Yarn material-ui/icons

Fixes #772

### Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Reference Images
Screenshot 2023-01-22 215043
Screenshot 2023-01-22 215128
Screenshot 2023-01-22 215152
Screenshot 2023-01-22 215212
Screenshot 2023-01-22 215248
Screenshot 2023-01-22 215317
Screenshot 2023-01-22 215414
Screenshot 2023-01-22 215442
Screenshot 2023-01-22 215519
Screenshot 2023-01-22 215557
Screenshot 2023-01-22 215643

### CODE REVIEW

**Comment by ARCHITABHATTAD** [comment]
@Kushal997-das Sir can you review and merge my PR. Thankyou!

**Comment by Kushal997-das** [comment]
> @Kushal997-das Sir can you review and merge my PR. Thankyou!

Will check

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@ARCHITABHATTAD Kindly add deployment link in the readme.md file also attach the images in `readme.md` file

**Comment by ARCHITABHATTAD** [comment]
@Kushal997-das sir I have made the required changes in readme.md....please review the PR

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@ARCHITABHATTAD Please add the deploy link of this project .

**Comment by ARCHITABHATTAD** [comment]
@Kushal997-das I have already added the deployment link as well

**Comment by ARCHITABHATTAD** [comment]
https://iiwotshi.netlify.app/

**Review by Kushal997-das — APPROVED** [review]
@ARCHITABHATTAD Great work !

**Comment by ARCHITABHATTAD** [comment]
Thankyou!! @Kushal997-das

**Pull request merged**
