### PR TITLE
Space War Game

### LINKED ISSUE #656: Space War Game using python
### Is your feature request related to a problem? Please describe.

It Is a space war game

### Describe the solution you'd like.

Tech Stack:
Python

### Describe alternatives you've considered.

I am a contributor under GSSoC 2022.

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by iamrahulmahato**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

It Is a space war game

Fixes #656

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Review by photon149 — CHANGES_REQUESTED** [review]
@iamrahulmahato 2 minor changes required
- Give a more appropriate title to the PR "Space War Game"
-  In your readme file an Image isnt loading please correct it
image

**Comment by iamrahulmahato** [comment]
@photon149 all changes done

**Review by photon149 — APPROVED** [review]
@iamrahulmahato Great 👍🏻 
@Kushal997-das @prakhar3062 have a look

**Review by Kushal997-das — APPROVED** [review]
LGTM 💯

**Pull request merged**
