### PR TITLE
Added Password Generator and Manager Project

### PR DESCRIPTION
**Pull request by smv1999**
Hello @Kushal997-das ! I have added "Password Generator and Manager" project in the Desktop Application category and inside the Python directory. Happy to contribute !

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@smv1999 you added this project under advance. But at the same time i don't think so that this project  would be under advance .

**Comment by smv1999** [comment]
> @smv1999 you added this project under advance. But at the same time i don't think so that this project would be under advance .

Okay. Should I add this under Intermediate then?

**Comment by Kushal997-das** [comment]
> > @smv1999 you added this project under advance. But at the same time i don't think so that this project would be under advance .
> 
> Okay. Should I add this under Intermediate then?

Yes ✔

**Comment by smv1999** [comment]
> > > @smv1999 you added this project under advance. But at the same time i don't think so that this project would be under advance .
> > 
> > 
> > Okay. Should I add this under Intermediate then?
> 
> Yes ✔

I have made the changes, Please have a look @Kushal997-das !

**Review by Kushal997-das — APPROVED** [review]
Looks good to me:)

**Pull request merged**
