### PR TITLE
Tree Structure Added

### PR DESCRIPTION
**Pull request by TawfikYasser**
Hi

This PR for the tree structure

I hope you like it.

Thanks

### CODE REVIEW

**Review by SamarpanCoder2002 — CHANGES_REQUESTED** [review]
Only Add Project name along with hyperlink under the folder name...Otherwise, it looks congested

**Comment by SamarpanCoder2002** [comment]
> Only Add Project name along with hyperlink under the folder name...Otherwise, it looks congested

**Comment by Kushal997-das** [comment]
Awesome job @TawfikYasser but as @SamarpanCoder2002 said if you add only project name this gonna be more readable and yeah please add the hyperlink as well.

**Comment by TawfikYasser** [comment]
Okay @SamarpanCoder2002 , @Kushal997-das  I will do that, But I think not today because I don’t have enough time today.

**Comment by SamarpanCoder2002** [comment]
> Okay @SamarpanCoder2002 , @Kushal997-das I will do that, But I think not today because I don’t have enough time today.

Not a problem at all..I will try this...with taking some time,,,

**Pull request closed without merging**
