### PR TITLE
add switch between currencies in currency convertor  

### LINKED ISSUE #379: Title: add a new feature in currency convertor project as part of GSSoC'22
### Is your feature request related to a problem? Please describe.

no 

### Describe the solution you'd like.

I want to switch button to switch the currency instead of changing it manually.
project link : https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application/Basic/Java/currency-converter

### Describe alternatives you've considered.

image

the switch button that I will develop it 

### Add any other context or screenshots about the feature request here.

I am participating in gssoc'22. please assign this to me.

### PR DESCRIPTION
**Pull request by salahashraf253**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description
add new a feature in the project which is switching from and to currency  

Fixes #379

### Checklist

- [ x] I've read the contribution guidelines.
- [ x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
related issue #379 
(Write your answer here.)

### CODE REVIEW

**Comment by Kushal997-das** [comment]
@salahashraf253 Please delete all unwanted files !!

**Comment by salahashraf253** [comment]
@Kushal997-das  kindly , check the pull request again . there is no unwanted files

**Comment by Kushal997-das** [comment]
@salahashraf253 Still there is .

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
.idea folder is required for this project ?

**Comment by Kushal997-das** [comment]
You are just updating this project so don't add unwanted files , after all requires changes please tell me or else not .

**Comment by salahashraf253** [comment]
@Kushal997-das idea folder is the libraries required to run the project

**Comment by Kushal997-das** [comment]
@salahashraf253 You are fixing one error just work on this no need to add extra file leave as it just do change in the main project file.

**Comment by salahashraf253** [comment]
@Kushal997-das ok , the idea file has just been deleted .
please check the pull request again .

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@salahashraf253 Please send me the output of it what i mean after running programming make one gif or mp4 video and send it here.

**Comment by salahashraf253** [comment]
https://user-images.githubusercontent.com/73083810/158068379-89f9733d-3775-4d30-86d9-a21a146302e5.mp4

that's it .

**Comment by salahashraf253** [comment]
@Kushal997-das

**Review by Kushal997-das — APPROVED** [review]

**Comment by Kushal997-das** [comment]
@salahashraf253 Great 💯

**Pull request merged**
