### PR TITLE
Atm machine

### LINKED ISSUE #510: ATM using PYTHON & MYSQL
### Is your feature request related to a problem? Please describe.

Create an ATM-like setup using Python and MySQL

### Describe the solution you'd like.

Create an ATM-like setup using Python and MySQL

### Describe alternatives you've considered.

None as Such

### Add any other context or screenshots about the feature request here.

None as Such

### PR DESCRIPTION
**Pull request by AnIkeT126**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes
I thought to take a realistic topic so
that I can implement it in a better and more understandable way. ATM is to help people in managing bank activities without
visiting bank and in a safe, secured manner. With this in mind, I
chose to make a project on ATMs with works similar to real-world ATMs.

### Description

Fixes #510  

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This is related to issue #510 and is a modified version of the PR #559

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@Kushal997-das please review this PR, relating to issue #510

**Comment by AnIkeT126** [comment]
@Kushal997-das please review this PR, relating to issue #510 and an update on #559, and merge this upon finding it correct.

**Review by Kushal997-das — APPROVED** [review]
@photon149 have a look .

**Review by photon149 — APPROVED** [review]
@AnIkeT126 Great
Looks good to me.
@Kushal997-das @prakhar3062 have a look

**Comment by AnIkeT126** [comment]
> @AnIkeT126 Great Looks good to me. @Kushal997-das @prakhar3062 have a look

thanks @Kushal997-das, @photon149 has approved this PR, can you please merge this.

**Pull request merged**
