### PR TITLE
Added teams clone files

### LINKED ISSUE #435: Teams Page Clone
### Is your feature request related to a problem? Please describe.

I would like to add a clone of one of microsoft teams pages (the page where groups are listed)

### Describe the solution you'd like.

The page should:
- be responsive as in the desktop web app.
- have light and dark mode supported.
- make use of HTML / CSS / Bootstrap 5.

### Describe alternatives you've considered.

None

### Add any other context or screenshots about the feature request here.

Issue made under GSSoC'22 contributions.

### PR DESCRIPTION
**Pull request by XZANATOL**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

- [x] Yes

### Description

Added a clone of one of microsoft teams pages (the page where groups are listed)

Fixes #435 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue: #435 
PR made under GSSoC'22 contributions

### CODE REVIEW

**Review by photon149 — CHANGES_REQUESTED** [review]
@XZANATOL Please Correct your README file.
image

**Comment by XZANATOL** [comment]
@photon149 Done.

**Review by photon149 — APPROVED** [review]
Looks good to me.
@Kushal997-das have a look.

**Review by Kushal997-das — APPROVED** [review]
LGTM 👍

**Pull request merged**
