### PR TITLE
Request to merge my project 

### PR DESCRIPTION
**Pull request by UG-SEP**
Hey Kushal I am Ujjwal. I created my Paint With UG project and want to contribute in your repos and follow the all rules in contributing.md so it my request to merge my request

### CODE REVIEW

**Comment by UG-SEP** [comment]
Please merge my request

**Comment by TawfikYasser** [comment]
Hi @UG-SEP Keep the great work, Please wait for reviewing the project.
Thanks.

**Comment by SamarpanCoder2002** [comment]
> Please merge my request

As you use the C++ file in your project...pls insert your project under C++ Folder, not in C......

**Comment by UG-SEP** [comment]
request to merge prject

**Review by SamarpanCoder2002 — COMMENTED** [review]
Your Project is really awesome... We are pleased to have you...expecting more projects from you....One thing...If the upstream commit is ahead of your commit in that repo....at first fetch from upstream and then if required make a pull request to contribute more...

**Review by Kushal997-das — COMMENTED** [review]
@UG-SEP Cool 👍

**Pull request merged**
