### PR TITLE
Adding Customer Churn Prediction Model

### PR DESCRIPTION
**Pull request by Stuti333**
# Project-Guidance! 🎊🎈

### Welcome! 🎉

Thank you for visiting our repository! We're excited to have you here. If you find this project useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 

Added a new model: customer churn prediction which compares the performance of 3 algorithms and create a model with the best algorithm with highest accuracy

### 🔧 Fixes #issue_no *(Required)*

#1561 

### 🏷️ Initiative Participation *(Required)*

This pull request is associated with the following initiative. Please choose the one you are contributing to:

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Stuti333 Please update your project [here](https://github.com/Kushal997-das/Project-Guidance/blob/main/Machine%20Learning%20and%20Data%20Science/README.md) and consider adding some images to your README.md file.

**Comment by Stuti333** [comment]
I have made the required changes kindly review it

**Comment by Kushal997-das** [comment]
@Stuti333 [update](https://github.com/Stuti333/Project-Guidance/tree/feature/Stuti/Machine%20Learning%20and%20Data%20Science#level-2-intermediate-)

**Comment by Stuti333** [comment]
@Kushal997-das Sorry for this mistake I have updated README file

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
