### PR TITLE
Added project live codepen Editor

### LINKED ISSUE #1017: Adding live codepen Editor project
### Description

A responsive website for Live Editor like Codepen, which helps developer to build a website, build test
cases to learn and debug.It reflects the live changes made during the development of a website in real-time, incorporating HTML, CSS, and JavaScript code updates.

### PR DESCRIPTION
**Pull request by Arpcoder**
This closes #1017

### CODE REVIEW

**Comment by Arpcoder** [comment]
Please review this @Kushal997-das

**Comment by ghsharma** [comment]
@Arpcoder , I’ve reviewed your code and noticed a few areas that need improvement. Here are the details:

Specific issues and suggestions :
1. Dead code files shall be removed.
2. Have a clear and organized repository structure.
3. Web development project should be deployed and the link should be provided in the readme file for inspection.
5. Also add images of the project in the readme file.

**Comment by Arpcoder** [comment]
> @Arpcoder , I’ve reviewed your code and noticed a few areas that need improvement. Here are the details:
> 
> Specific issues and suggestions :
> 
> 1. Dead code files shall be removed.
> 2. Have a clear and organized repository structure.
> 3. Web development project should be deployed and the link should be provided in the readme file for inspection.
> 4. Also add images of the project in the readme file.

Which level label you will give to this issue?

**Comment by Kushal997-das** [comment]
@Arpcoder First fix the things what [ghsharma](https://github.com/ghsharma) said , before bothering about level.

**Comment by Arpcoder** [comment]
> @Arpcoder First fix the things what [ghsharma](https://github.com/ghsharma) said , before bothering about level.

Done

**Review by Kushal997-das — COMMENTED** [review]
See the output is not showing properly. Try to fix that out.

see the output

**Comment by Arpcoder** [comment]
> See the output is not showing properly. Try to fix that out.
> 
> see the output

Its already fixed.. If you refresh it, it will work properly... But leave now.

**Pull request closed without merging**
