### PR TITLE
Emotion + Pose detection completed

### LINKED ISSUE #632: Emotion + Body Posture Detection
### Is your feature request related to a problem? Please describe.

Yes, since this would incorporate the concept of Computer Vision, Machine Learning as well as Deep-Learning and this would come under the Category of ```Artificial Intelligence```

### Describe the solution you'd like.

I would like to use the following libraries:
- OpenCV: Computer Vision
- MediaPipe: Posture Detection
- DeepFace: Emotion Detection

So basically in posture detection and emotion detection it will first recognize the full body as well as face and draw 32 key points all over the body and these key points are connected according to the weights (same as graph data-structures)

### Describe alternatives you've considered.

The other alternative could be using Tensorflow and OpenCV

### Emotion Detection
img1

### Posture Detection
img2

### PR DESCRIPTION
**Pull request by Kumar-laxmi**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)
Yes, I have read it

### Description
It can be used to check for violence in any area with the help of CCTV Cameras. Violence is an urgent public health problem. From infants to the elderly, it affects people in all stages of life and can lead to a lifetime of physical, emotional, and economic problems.

(Write your answer here.)

Fixes #632 

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by photon149 — APPROVED** [review]
@Kumar-laxmi Looks good.
Approved from my end.
@Kushal997-das @prakhar3062 have a look

**Comment by Kumar-laxmi** [comment]
@Kushal997-das pls review this PR

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Kumar-laxmi Your `.DS_store` file present in multiple so delete this .
secondly this project should under in basic section of Artificial intelligence.

**Comment by Kumar-laxmi** [comment]
ok

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi Your `.DS_store` file present in multiple so delete this . secondly this project should under in basic section of Artificial intelligence.

@Kushal997-das I have done the required changes, pls review this PR

**Comment by Kumar-laxmi** [comment]
@photon149 Pls merge this PR if it is ok.....

**Review by Kushal997-das — APPROVED** [review]
LGTM 💯 

@photon149 have a look !

**Pull request merged**
