### PR TITLE
Added Selenium Automated game playing bot

### PR DESCRIPTION
**Pull request by PiyushBagde**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #issue_no

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Addressign issue #1160

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Hi , @PiyushBagde Add your project name [here](https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application#python--)

**Comment by PiyushBagde** [comment]
yes i will update name

**Comment by PiyushBagde** [comment]
I have added project in the list

**Comment by PiyushBagde** [comment]
image
 
is it the correct way to do it or it will not redirect properly after merging

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
