### PR TITLE
Online Gaming Portal Template

### LINKED ISSUE #437: Title: Add Frontend for Online Gaming Service
### Is your feature request related to a problem? Please describe.

NA

### Describe the solution you'd like.

A landing page for an online gaming portal. Made using glassmorphism design and clean UI.

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by kaustav202**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes, totally.

### Description

A frontend template of an online gaming service portal that has features like game search, activity and social media accounts  

Fixes #437 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#437

### CODE REVIEW

**Comment by photon149** [comment]
@kaustav202 Please rename your PR Title appropriately with regards to your Issue Title.

**Review by photon149 — CHANGES_REQUESTED** [review]
@kaustav202 Also , further enhance your README file.
You can look at other READMEs in the repository for reference.

**Comment by kaustav202** [comment]
Made the requested changes @photon149

**Comment by Kushal997-das** [comment]
@photon149 check .

**Comment by photon149** [comment]
@kaustav202 Looks good.
No Duplicity ✅ 
@Kushal997-das @prakhar3062 have a look.

**Review by photon149 — APPROVED** [review]
@kaustav202 Looks good.
No Duplicity ✅
@Kushal997-das @prakhar3062 have a look.

**Pull request merged**
