### PR TITLE
Added 2-digit number classification

### LINKED ISSUE #988: Title: 2 Digit Handwritten Number Recognition
### Is your feature request related to a problem? Please describe.

I want to build a model that can accurately recognize 2-digit handwritten numbers using image classification and pattern recognition. 

### Describe the solution you'd like.

I am going to load single digits from the MNIST dataset and combine them to form double digit numbers ranging from 10 to 99. In total the model is going to have 100 classes: from 0 to 99

### Describe alternatives you've considered.

This project can have a user-interactive interface where they user shows the number and the model makes the prediction. 

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by Ishita-Jena**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

I've added a 2-digit number classification project which predicts numbers between 0-99. The project has a user -friendly interface with the help of which the user can input images and get predictions. The project incorporates robust error handling to manage unexpected inputs during execution.

Fixes #988 

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Ishita-Jena Please Update your Project [here](https://github.com/Kushal997-das/Project-Guidance/blob/main/Machine%20Learning%20and%20Data%20Science/README.md)

**Comment by Ishita-Jena** [comment]
Hello, I've made the changes requested. Please check and let me know if all's good. Thank you.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Please [Look](https://github.com/Kushal997-das/Project-Guidance/blob/main/Machine%20Learning%20and%20Data%20Science/README.md) at here , Level 1 we have 25 projects , level2 we have 9 projects and level3 we have 5 projects , since your project under level2 kindly make sure Level 2 project count should be 10 and rest will be same.

**Comment by Ishita-Jena** [comment]
I've made changes to the readme file. Please check it out.

**Comment by Kushal997-das** [comment]
@Ishita-Jena In your case under basic only 23 projects though we have 25, kindly fetch this repo.

**Comment by Ishita-Jena** [comment]
I've fetched the repo. Please check it out.

**Review by Kushal997-das — APPROVED** [review]
👍🏻

**Pull request merged**
