### PR TITLE
Anime

### LINKED ISSUE #633: Title: Anime Website
### Is your feature request related to a problem? Please describe.

Yes, I found that no one actually made anything related to Anime. I can introduce Anime to this repository.

### Describe the solution you'd like.

I am making a small  Anime website using HTML and CSS only. It would be creative and good looking

### Describe alternatives you've considered.

I'll add a home page listing of all time favoritie anime and a navbar having a genre category. 

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by Adbnemesis**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

yes

### Description

Created a completely new intermediate web development website using only html and css. Its about the famous japanese anime show. It contains 3 html files all linked with each other with proper styling

Fixes #633 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

NA

### CODE REVIEW

**Comment by Adbnemesis** [comment]
@Kushal997-das I'm not able to check the checklist so I just wrote yes  in the boxes

**Review by photon149 — COMMENTED** [review]
@Adbnemesis Please add a README file with required output SS of the webpage

**Comment by Adbnemesis** [comment]
@photon149 shall I add it in my anime folder only?

**Comment by photon149** [comment]
Yes @Adbnemesis

**Comment by Adbnemesis** [comment]
@photon149  added readme file. Kindly check

**Review by photon149 — COMMENTED** [review]
@Adbnemesis Further enhance your README file and also it would be better if you put all your images in a seperate folder.
@Kushal997-das can you  please check the file location for the same.

**Comment by Adbnemesis** [comment]
@photon149  done the needful, please look at it now

**Review by photon149 — APPROVED** [review]
@Adbnemesis Nice Work 
Approved from my end .
@Kushal997-das @prakhar3062 have a look

**Comment by Adbnemesis** [comment]
@photon149 @Kushal997-das  Can you please review it a bit more soon as we are approaching the end of Gssoc'22 very soon

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
