### PR TITLE
Onclick listner on the Domains names and table of content cards

### PR DESCRIPTION
**Pull request by shubhamkumaar**
#1478 

I added an event listener.
Below you can check the video for details
https://drive.google.com/file/d/1xM5TdAYPNI8LjyVxZhIFzC22I0FP1Vl1/view?usp=sharing

241015_16h14m59s_screenshot

### CODE REVIEW

**Comment by Kushal997-das** [comment]
@shubhamkumaar Can you give me a summary of your changes? The video you shared was not very clear on the details.

**Comment by shubhamkumaar** [comment]
Before when you click on the card it open the same home page

After: Now it redirect to the github repo of the Respective domain mentioned in the card

**Comment by Kushal997-das** [comment]
@shubhamkumaar Can you please deploy the whole project and send here live link.

**Comment by shubhamkumaar** [comment]
https://shubhamkumaar.github.io/Temp/

**Comment by shubhamkumaar** [comment]
Hey any update?

**Comment by Kushal997-das** [comment]
@shubhamkumaar Logo is not working in your case. [FYR](https://gyanaprakashsahoo7853.github.io/ProjectGuidance2024/)

**Comment by shubhamkumaar** [comment]
image

Actually i have created a new repo.
that is just to show the functionality and I have not uploaded the logo.

image
This is the original localhost project.
And can also verify it in the video also.


The link I have shared is from:- https://github.com/shubhamkumaar/Temp

**Comment by Kushal997-das** [comment]
Give hosting link after fixing the bug.

**Comment by shubhamkumaar** [comment]
Now you can check on the same link.

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
