### PR TITLE
Live character app added

### PR DESCRIPTION
**Pull request by Srishtihere**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #issue_no

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Srishtihere Do the following changes : 
1. Add your project under basic folder .
2. Add the project output in your `readme.md` like the images .
3. Deploy the project and add this link in `readem.md` file .

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Srishtihere Add the description about your project in `readme.md` file , if somebody will look into it then how then can understand what's the project is all about .

**Comment by Kushal997-das** [comment]
@Srishtihere Update on this else we will close the PR .

**Comment by Srishtihere** [comment]
yeah yeah sure sorry I was caight in exams

**Review by Kushal997-das — APPROVED** [review]

**Review by Kushal997-das — APPROVED** [review]
@Srishtihere You have added same project in two different folder, for now i'm approving it but make sure not to repeat this

**Pull request merged**
