### PR TITLE
CPU Scheduler Project

### PR DESCRIPTION
**Pull request by TawfikYasser**
This PR assigned with issue #39 

I hope this project help other developers.

Thanks for @SamarpanCoder2002

### CODE REVIEW

**Comment by SamarpanCoder2002** [comment]
Your project is ok...but the problem is to Change your CPU-README.md file to only the 'README.md' file...otherwise README file will not be shown normally as like other projects...

**Comment by TawfikYasser** [comment]
Ok I will change it now.

**Comment by TawfikYasser** [comment]
I changed it.

**Comment by SamarpanCoder2002** [comment]
Please add a Gif File of your project to the README file of your project. For reference, you can check other projects' README file... This will help visitors to make a clear idea about your projects...Thanks for your time...

**Comment by TawfikYasser** [comment]
Ok I will add it.

**Comment by SamarpanCoder2002** [comment]
Thanks for your time

**Comment by TawfikYasser** [comment]
I can add image ? Is it necessary to add GIF ? Because I can not make one for now!

**Comment by SamarpanCoder2002** [comment]
Yeah, you can.... But make sure that your image strongly notifies the visitors about your project idea.....If required, you can add more than one image in the README.md file of your repo...Thanks for your kind attention

**Comment by TawfikYasser** [comment]
Okay

**Comment by SamarpanCoder2002** [comment]
Thanks for your time....

**Comment by TawfikYasser** [comment]
Thanks for your information and your time.
I will add more soon.

**Comment by SamarpanCoder2002** [comment]
After adding this all... please reply to that comment.... After checking I will definitely merge your pull request..Thank you...

**Comment by TawfikYasser** [comment]
> After adding this all... please reply to that comment.... After checking I will definitely merge your pull request..Thank you...

Sorry I can not understand you!

**Comment by SamarpanCoder2002** [comment]
If all changes are made successfully..then you can comment here... This helps me to check your project finally before merge your pull request...Thank you for your time

**Comment by TawfikYasser** [comment]
Okay all changes are made successfully. 
Thanks @SamarpanCoder2002

**Comment by SamarpanCoder2002** [comment]
> Okay all changes are made successfully.
> Thanks @SamarpanCoder2002

Let me check it out and I will merge it. Thanks for your kind time...

**Comment by TawfikYasser** [comment]
Okay take your time.

**Review by SamarpanCoder2002 — COMMENTED** [review]
Your project really very good for us...Thanks for your interest for contribute here... We are expecting more projects from you to contribute here... Thanks for your interest and time.....

**Comment by TawfikYasser** [comment]
> Your project really very good for us...Thanks for your interest for contribute here... We are expecting more projects from you to contribute here... Thanks for your interest and time.....

It’s a good experience for me.
I will contribute more soon.

Thanks for your help @SamarpanCoder2002

**Comment by SamarpanCoder2002** [comment]
> > Your project really very good for us...Thanks for your interest for contribute here... We are expecting more projects from you to contribute here... Thanks for your interest and time.....
> 
> It’s a good experience for me.
> I will contribute more soon.
> 
> Thanks for your help @SamarpanCoder2002

It's our pleasure

**Review by Kushal997-das — APPROVED** [review]
Looks good to me:)

**Comment by TawfikYasser** [comment]
Thanks @Kushal997-das

**Pull request merged**
