### PR TITLE
Contact form update

### LINKED ISSUE #247: Improve UI of Contact Form in Basic Web Development Section #GSSoc 22
Improving the UI :  
 • adding 'glassmorphism' web design to the form
 • application of vanilla
 • adding a favicon                          

Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
Yes , I have go through the contributing.md file .

## Motivation
UI/UX design of Web Apps has always been my domain of interest. My aim is to keep getting better at this.

## Pitch
Improving the UI will lead to enhanced user experience.
#GSSoc 22

### PR DESCRIPTION
**Pull request by shania-balkhi**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes, I have read it thoroughly.

### Description

• added 'glassmorphism' web design to the form.
• applied vanilla-tilt effect to the form to make the form visually attractive and playful.
• added the favicon of GSSoC so that the page appears authentic, original and complete.
• the site now seems visually attractive and user friendly!

Fixes #247

### Checklist

- [✓] I've read the contribution guidelines.
- [✓] I've checked the issue list before deciding what to submit.
- [✓] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@shania-balkhi Everything is looks correct else this [link](https://ug-sep.github.io/Contact-Form/) 
you should update your updated project link in `readme.md` file , where you can see `live now` option i'm talking about this only.

**Comment by shania-balkhi** [comment]
> @shania-balkhi Everything is looks correct else this [link](https://ug-sep.github.io/Contact-Form/) you should update your updated project link in `readme.md` file , where you can see `live now` option i'm talking about this only.

I have updated the project link now.

**Review by Kushal997-das — APPROVED** [review]
@prakhar3062 Have a look !

**Comment by Kushal997-das** [comment]
@shania-balkhi great work !

**Pull request merged**
