### PR TITLE
Railway (done Changes)

### LINKED ISSUE #660: c++ railway management System
### Is your proposal related to a problem? Please describe.

train schedule
ticket booking

### Add any other context or screenshots about the proposal request here.

_No response_

### PR DESCRIPTION
**Pull request by DragonUncaged**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #660 

### Checklist

- [x] I've read the contribution guidelines.
- [x I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
image

### CODE REVIEW

**Review by photon149 — APPROVED** [review]
@DragonUncaged Nicely Done
Approved from my end.
@Kushal997-das @prakhar3062 have a look

**Review by prakhar3062 — APPROVED** [review]

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@DragonUncaged 
1. This a not a cpp program at all this is a C-Programming so this should under C folder.
2.  This project should under Basic level .
3. You have added some `.txt` file but some has empty can you please add details if this really required or else delete these files .

**Comment by DragonUncaged** [comment]
> 

1) .cpp file extension tells that its a c plus plus.
2) As i have seen other project that stores the data in file are under intermediate level.
3) all the text file are being used for the data storage there is one file where txt encoding is different and not user readalbe directly.

**Comment by DragonUncaged** [comment]
> @DragonUncaged
> 
> 1. This a not a cpp program at all this is a C-Programming so this should under C folder.
> 2. This project should under Basic level .
> 3. You have added some `.txt` file but some has empty can you please add details if this really required or else delete these files .

.cpp file extension tells that its a c plus plus.
Done file changes
all the text file are being used for the data storage there is one file where txt encoding is different and not user readalbe directly

**Pull request merged**
