### PR TITLE
Brain Tumor detection

### PR DESCRIPTION
**Pull request by Aditijainnn**
# Project-Guidance! 🎊🎈

### Welcome! 🎉

Thank you for visiting our repository! We're excited to have you here. If you find this project useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 

Added ml trained model
image

### 🔧 Fixes #issue_no *(Required)*
#1432

### 🏷️ Initiative Participation *(Required)*

This pull request is associated with the following initiative. Please choose the one you are contributing to:

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Comment by Kushal997-das** [comment]
@Aditijainnn  Hello, please follow the rules of this event and avoid spamming by submitting one project across multiple repositories to gain points. I can point out the duplicate PR here since it has already been merged, and I don't want to negatively impact your score. I'm closing this one.

**Comment by Aditijainnn** [comment]
> @Aditijainnn Hello, please follow the rules of this event and avoid spamming by submitting one project across multiple repositories to gain points. I can point out the duplicate PR here since it has already been merged, and I don't want to negatively impact your score. I'm closing this one.

please can you remove spam tag as due to this i ambeeing dissqualified from hacktoberfest due to this please

**Comment by Aditijainnn** [comment]
> > @Aditijainnn Hello, please follow the rules of this event and avoid spamming by submitting one project across multiple repositories to gain points. I can point out the duplicate PR here since it has already been merged, and I don't want to negatively impact your score. I'm closing this one.
> 
> @Kushal997-das please can you remove spam tag as due to this i am being dissqualified from hacktoberfest please remove it this would not be repeated in future

????

**Comment by Kushal997-das** [comment]
Done

**Pull request closed without merging**
