### PR TITLE
Line Follower Robot using Arduino #996

### LINKED ISSUE #996: Title: Line Follower Robot using Arduino
### Is your proposal related to a problem? Please describe.

The primary objective of this project is to design and construct an autonomous line follower robot which is capable of navigating a predefined path that is marked with a prominent black line on a contrasting background.

I want to add this project proposal under IOT Basic level project as a GSSOC'24 contributor. @Kushal997-das 

### Add any other context or screenshots about the proposal request here.

I have prior experience in making arduino based projects.  
I am sharing an image of the prototype robot that I have made.
Screenshot 2024-05-12 164517

### PR DESCRIPTION
**Pull request by deedGhost**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)
YES

### Description

(Write your answer here.)
The primary goal of this endeavor is to create an autonomous line follower robot, capable of tracking and following a predetermined path without the need for external guidance. It is capable of navigating a path that is marked with a prominent black line on a contrasting background.
Fixes #996

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by deedGhost** [comment]
Hey @Kushal997-das
Can u please update me about me about this whether it's okay or do I need to change something?

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@deedGhost Things need to change :
1. Add your image under image folder for this you need to create a `image` folder.
2. Add output `image` under `readme.md` file.
3. Update your project under [this](https://github.com/Kushal997-das/Project-Guidance/blob/main/IOT(Internet%20of%20Things)/README.md)

**Comment by deedGhost** [comment]
@Kushal997-das please review the changes done.

**Review by Kushal997-das — APPROVED** [review]
@deedGhost Good work.

**Pull request merged**
