### PR TITLE
Customer Churn Prediction

### PR DESCRIPTION
**Pull request by SimranShaikh20**
# Project-Guidance! 🎊🎈

ISSUE NO   #1389

Hi, I am Simran Shaikh. my contribution to open source project for Customer Churn Prediction the most important topic that show that why  the process of analyzing data to identify which customers are likely to cancel a company's products or services .

Here is the screenshots:
image
image
image
image
image
image

 
image
image
image
image

image
image

### CODE REVIEW

**Comment by NimraAslamkhan** [comment]
Hi there!
I am the Mentor of this project 
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

- Please adhere to the existing guidelines.
- No additional rules, thanks!
- Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).

Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an `invalid` label.

Looking forward to your contributions!

**Comment by SimranShaikh20** [comment]
@Kushal997-das  is there any changes ?

**Comment by Kushal997-das** [comment]
@SimranShaikh20 Kindly mention your issue number.

**Comment by SimranShaikh20** [comment]
> @SimranShaikh20 Kindly mention your issue number.

Added!

**Comment by Kushal997-das** [comment]
@SimranShaikh20  You have created an invalid PR, as your changes affect all folders. Please check and fix this; otherwise, we will have to close it.

**Pull request closed without merging**
