### PR TITLE
Added list_operations folder to Blockchain Development\Basic\Arithmetic

### LINKED ISSUE #1596: Custom Issue Report
# Project-Guidance! 🎊🎈

### Welcome! 🎉
Thank you for opening an issue! Your contributions help us improve the project. If you find this repository useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 

I am creating my own version of the `SimpleList` smart contract in this repository. This issue is to track my development and work on the functionalities provided by this contract. The goal is to implement a dynamic list management system using Solidity with features such as adding, removing, and retrieving items.

### 🔍 Priority Level
- [ ] High
- [ ] Medium
- [ ] Low

### 🏷️ Initiative Participation *(Required)*

- [x] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [x] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### 💬 Next Steps:

You can expect a response within 7 days.

### PR DESCRIPTION
**Pull request by vermu490**
# Project-Guidance! 🎊🎈

### Welcome! 🎉

Thank you for visiting our repository! We're excited to have you here. If you find this project useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 

This pull request introduces the `SimpleList` contract, a smart contract developed in Solidity for managing a dynamic list of string items on the Ethereum blockchain. The contract provides a straightforward interface for adding and removing items, as well as retrieving item counts and individual items.

Key features include:
- **Dynamic Array Storage**: The contract utilizes a private array to store a list of strings, allowing for dynamic additions and removals of items.
- **Event Logging**: Two events, `ItemAdded` and `ItemRemoved`, are emitted to log changes to the list, providing transparency and traceability.
- **Public Access**: Functions to add items, remove items by index, and retrieve both individual items and the entire list are made public, ensuring accessibility to users.
- **Safety Checks**: The contract includes checks to prevent out-of-bounds access when removing or retrieving items, enhancing security.

### 🔧 Fixes #issue_no *(Required)*

Fixes #1596 

### 🏷️ Initiative Participation *(Required)*

This pull request is associated with the following initiative. Please choose the one you are contributing to:

- [x] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [x] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Comment by vermu490** [comment]
I have done that Can you please check and let me know if any changes

**Comment by vermu490** [comment]
> Update your project [here](https://github.com/Kushal997-das/Project-Guidance/blob/main/Blockchain%20Development/README.md)


I have already done that can you please check and let me know

**Review by darkaura7000 — APPROVED** [review]

**Comment by vermu490** [comment]
can you please add the required label after merging is done

**Comment by Kushal997-das** [comment]
> Update your project [here](https://github.com/Kushal997-das/Project-Guidance/blob/main/Blockchain%20Development/README.md)

Kindly do it first.

**Comment by Kushal997-das** [comment]
@darkaura7000, please refrain from sending unnecessary messages. Continued spamming may result in a block and a report. Thank you for your understanding.

**Comment by vermu490** [comment]
> > Update your project [here](https://github.com/Kushal997-das/Project-Guidance/blob/main/Blockchain%20Development/README.md)
> 
> Kindly do it first.

But my project comes under arithmetic, what changes should I Do in that ?

**Comment by Kushal997-das** [comment]
Hi @vermu490,

Since this project already exists in our project guidance, we are closing this duplicate project. Thank you for your understanding!

Best regards,
Kushal Das

**Pull request closed without merging**
