### PR TITLE
KNN algorithm

### PR DESCRIPTION
**Pull request by ABHIGPT401**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)Yes

### Description

(Write your answer here.)
KNN algorithm

Fixes #issue_no

#425 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by photon149 — CHANGES_REQUESTED** [review]
@ABHIGPT401 Further Enhance the project .
- You can add confusion Matrix 
- Add more content in your README file

**Comment by ABHIGPT401** [comment]
Okay Sir

**Comment by ABHIGPT401** [comment]
Done , Please Check

**Review by Kushal997-das — APPROVED** [review]
@ABHIGPT401 

LGTM 💯 

@photon149 have a look !

**Review by photon149 — APPROVED** [review]
Approved from my end.
@prakhar3062 take a look

**Pull request merged**
