### PR TITLE
New Desktop Project Added - SQL [ Recruitment System ]

### PR DESCRIPTION
**Pull request by TawfikYasser**
Hi 

This PR assigned with issue #79 

For the new `SQL` project

Project description in the project README file

I hope this helps other developers

Thanks

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Looks good to me @TawfikYasser but Readme.md file should be under SQL not under the project.

**Comment by Kushal997-das** [comment]
> Looks good to me @TawfikYasser but Readme.md file should be under SQL not under the project.

Or delete the Readme.md file which is under SQL

**Comment by TawfikYasser** [comment]
Okay File Deleted

**Review by SamarpanCoder2002 — COMMENTED** [review]
Looks good to me

**Comment by Kushal997-das** [comment]
@SamarpanCoder2002 When you gonna merge any project don't forget to add levels.

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 When you gonna merge any project don't forget to add levels.

Ok...I will remember this...

**Pull request merged**
