### PR TITLE
Connect 4 Game

### LINKED ISSUE #453: Title: Add Connect 4 Game
### Is your feature request related to a problem? Please describe.

I have made a Connect 4 Game in Java using the JavaFX library.

### Describe the solution you'd like.

The program is made in Java using the JavaFX library and is extensively based on an object-oriented programming approach.

### Describe alternatives you've considered.

I have used the JavaFX library for building the layout but the same output can also be achieved using the Java SWING library.

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by Bhushan-Thombre**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

### Description

Desktop application of Connect 4 Game made using Java and JavaFX, extensively based on an object-oriented programming approach.
The program is added to Desktop Applications/Intermediate/Java

Fixes #453 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by Bhushan-Thombre** [comment]
Sure, will do it.

**Comment by Bhushan-Thombre** [comment]
I have added the readme file and gif with the appropriate description of the project.

**Review by Kushal997-das — COMMENTED** [review]
@Bhushan-Thombre Delete this `.idea` folder .

**Comment by Bhushan-Thombre** [comment]
I have removed the .idea folder

**Review by Kushal997-das — APPROVED** [review]
LGTM 👍 
@photon149 have a look !

**Review by photon149 — APPROVED** [review]
Approved from my end.
@prakhar3062 have a look

**Review by prakhar3062 — APPROVED** [review]

**Pull request merged**
