### PR TITLE
Added Blinkit Clone - Basic Web Development Project (#1368)

### LINKED ISSUE #1368: Blinkit Clone | Web Development Project
### Add any other context or screenshots about the proposal request here.

https://github.com/user-attachments/assets/6bd88749-7c97-4cf4-bed8-84cdb52c691c

<hr><br>I have made this simple Blinkit Login page. Tech Stack used here are: <strong>HTML</strong> and <strong>CSS</strong>.<br><br>  @Kushal997-das I would like to contribute to this repository in <strong>Web Development</strong> Folder under <strong>GSSOC-2024-extd</strong> and <strong>Hacktoberfest-2024</strong>. Kindly assign me this issue. Thank you!

### PR DESCRIPTION
**Pull request by neyhere07**
# Project-Guidance! 🎊🎈

### Welcome! 🎉

Thank you for visiting our repository! We're excited to have you here. If you find this project useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 🔧 Fixes #1368  *(Required)*
<pre>Successfully added Blinkit Clone project.
Folder Direction: Web Development ➡️ Basic ➡️ Blinkit Clone</pre>

### 🏷️ Initiative Participation *(Required)*

This pull request is associated with the following initiative. Please choose the one you are contributing to:

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@neyhere07  Hi, could you please add the project names in alphabetical order to the README.md file?

**Comment by neyhere07** [comment]
> @neyhere07 Hi, could you please add the project names in alphabetical order to the README.md file?

Okay, sure!

**Comment by neyhere07** [comment]
Hi @Kushal997-das, updated now.

**Comment by NimraAslamkhan** [comment]
Hi there!
I am the Mentor of this project
Although this repo is not part of Hacktoberfest 2024, we have some great alternatives for you. Welcome to SkillShow, a repository focused on skill enhancement!

Guidelines:

Please adhere to the existing guidelines.
No additional rules, thanks!
Check it out here: [SkillShow](https://github.com/Kushal997-das/SkillShow).
Note: Start by creating an issue. Once it’s assigned to you, feel free to open a pull request (PR). Directly opening a PR will lead to an invalid label.

Looking forward to your contributions!

**Review by Kushal997-das — APPROVED** [review]

**Comment by neyhere07** [comment]
Hello! I request to add hacktoberfest-accepted label and gssoc-extd level number also. Thak you!!

**Comment by MastanSayyad** [comment]
@Kushal997-das Program Manager this Side, in your repo Labels are wrong for gssoc

correct label is: `gssoc-ext`

add me as a collaborator so that I can help you to fix it!

**Comment by Kushal997-das** [comment]
> `gssoc-ext`

Noted , I’ll fix it :)

**Pull request merged**
