### PR TITLE
Reach To the End (changes done)

### LINKED ISSUE #722: Reach to the End Game
### Is your proposal related to a problem? Please describe.

Web Dev.
Game

### Add any other context or screenshots about the proposal request here.

_No response_

### PR DESCRIPTION
**Pull request by DragonUncaged**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #722 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by photon149 — APPROVED** [review]
@DragonUncaged 👍🏻 
Approved.
@Kushal997-das @prakhar3062 have a look

**Review by prakhar3062 — APPROVED** [review]
Nice Work

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@DragonUncaged Reduce the image size from `readme.md` file

**Comment by DragonUncaged** [comment]
> @DragonUncaged Reduce the image size from `readme.md` file

that is just a png file if reduced it will be blurred

**Comment by Kushal997-das** [comment]
> > @DragonUncaged Reduce the image size from `readme.md` file
> 
> that is just a png file if reduced it will be blurred

I'm not saying that you have to reduce the original pic you just need to reduce using HTML code

**Comment by Kushal997-das** [comment]
`GIF` 
Use this

**Comment by DragonUncaged** [comment]
> `GIF` Use this

Done!!

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
