### PR TITLE
Java Desktop Application

### PR DESCRIPTION
**Pull request by TawfikYasser**
Hi

This PR assigned with issue #92 to add a desktop application using `java`

I hope this project be good for other developers.

Thanks

### CODE REVIEW

**Comment by Kushal997-das** [comment]
@TawfikYasser When ever you send PR make sure one PR at a time . Don't spam .

**Comment by TawfikYasser** [comment]
> @TawfikYasser When ever you send PR make sure one PR at a time . Don't spam .

I can’t understand you, Please!

**Comment by Kushal997-das** [comment]
> > @TawfikYasser When ever you send PR make sure one PR at a time . Don't spam .
> 
> I can’t understand you, Please!

When you send PR make sure send this at a time don't update after sending this . When you do this it's quite hard to viewed your changes .

**Comment by TawfikYasser** [comment]
> > > @TawfikYasser When ever you send PR make sure one PR at a time . Don't spam .
> > 
> > 
> > I can’t understand you, Please!
> 
> When you send PR make sure send this at a time don't update after sending this . When you do this it's quite hard to viewed your changes .

Oh Okay, Sorry for that, I have lost my internet connection a little while ago, So I couldn't send the PR once.

**Comment by TawfikYasser** [comment]
I have finished.

**Comment by Kushal997-das** [comment]
> > > @TawfikYasser When ever you send PR make sure one PR at a time . Don't spam .
> > 
> > 
> > I can’t understand you, Please!
> 
> When you send PR make sure send this at a time don't update after sending this . When you do this it's quite hard to viewed your change

> > > > @TawfikYasser When ever you send PR make sure one PR at a time . Don't spam .
> > > 
> > > 
> > > I can’t understand you, Please!
> > 
> > 
> > When you send PR make sure send this at a time don't update after sending this . When you do this it's quite hard to viewed your changes .
> 
> Oh Okay, Sorry for that, I have lost my internet connection a little while ago, So I couldn't send the PR once.

@TawfikYasser No problem .

**Comment by Kushal997-das** [comment]
> I have finished.

@TawfikYasser  May i proceed then ?

**Comment by TawfikYasser** [comment]
> > I have finished.
> 
> @TawfikYasser May i proceed then ?

Yes

**Review by Kushal997-das — APPROVED** [review]
Good job @TawfikYasser

**Comment by TawfikYasser** [comment]
@Kushal997-das Thanks

**Comment by Kushal997-das** [comment]
> @Kushal997-das Thanks

@TawfikYasser Update the [this readme.md file](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md)

**Comment by TawfikYasser** [comment]
> > @Kushal997-das Thanks
> 
> @TawfikYasser Update the [this readme.md file](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md)

Sure, I will do.

**Comment by TawfikYasser** [comment]
@Kushal997-das README File Updated.

**Pull request merged**
