### PR TITLE
Facebook Login or Sign up Clone Web Page

### PR DESCRIPTION
**Pull request by Moksh45**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
yes

### Description
In this project i have made a Facebook clone page using HTML and CSS

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
In this project i have made a Facebook clone page using HTML and CSS

### CODE REVIEW

**Comment by photon149** [comment]
@Moksh45 Please mention the Issue number it fixes.

**Comment by Kushal997-das** [comment]
@Moksh45  Do the requires changes ASAP else we will close this .

**Comment by Moksh45** [comment]
> ### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
> yes
> 
> ### Description
> In this project i have made a Facebook clone page using HTML and CSS
> 
> Fixes #issue_no
> Zero (Because I am adding  a new folder in Web Development\Basic so  I am not Solve any Issue but Add a new Folder)
> ### Checklist
> * [x]  I've read the contribution guidelines.
> * [x] I've checked the issue list before deciding what to submit.
> * [x]  I've edited the `README.md` and link to my code.
> 
> ## Related Issues or Pull Requests
>  I am adding  a new folder in Web Development\Basic so  I am not Solve any Issue but Add a new Folder

**Comment by Moksh45** [comment]
done

**Comment by Kushal997-das** [comment]
> done

What you have done , @

> done

What you have done he @photon149 he said mention the issue number that you have been fixes but you didn't mentioned yet . It's been long time so we gonna close this PR .

**Pull request closed without merging**
