### PR TITLE
Application of Artificial intelligence in friction stir welding

### PR DESCRIPTION
**Pull request by PRIYANSHU2026**
it is very reliable by using ANN

### CODE REVIEW

**Comment by PRIYANSHU2026** [comment]
You have assigned me I send 2 different project I can show you

**Comment by Kushal997-das** [comment]
@PRIYANSHU2026 I assigned you but what you did why you are adding same issue or PR in multiple repos . I'll not accept this in my repo.

**Comment by PRIYANSHU2026** [comment]
where sir

**Comment by Kushal997-das** [comment]
@PRIYANSHU2026 I gonna reopen this PR. For you do not repeat your mistake again.

**Comment by PRIYANSHU2026** [comment]
sure sir

**Pull request closed without merging**
