### PR TITLE
Create greetings.yml

### PR DESCRIPTION
**Pull request by TawfikYasser**
Hi

This PR to adding the `greating.yml` file that runs a GitHub action on every pull request and issue opened (created).

fixing issue #104 

I hope this be good @Kushal997-das , @SamarpanCoder2002 

Thanks

### CODE REVIEW

**Comment by TawfikYasser** [comment]
Please @Kushal997-das , Wait for the PR, I will update something tomorrow.
Thanks

**Comment by TawfikYasser** [comment]
The GitHub action now working well, and the following image show the message displayed for a person who open an new issue, as well as in PR the same.

ii


I hope this be good for you @Kushal997-das 

If you want to change the content of the message tell me :)

And sorry for a lot of commits, Because was there a problem.

Thanks

**Review by Kushal997-das — APPROVED** [review]
Awesome job @TawfikYasser

**Comment by TawfikYasser** [comment]
> Awesome job @TawfikYasser

Thanks @Kushal997-das

**Pull request merged**
