### PR TITLE
Title: Medical Data Visualizer

### LINKED ISSUE #622: Title: Medical Data Visualiser
### Is your feature request related to a problem? Please describe.

Machine Learning Basic Project to visualise medical data in the form of graphs.

### Describe the solution you'd like.

In this project, you will visualize and make calculations from medical examination data using matplotlib, seaborn, and pandas.

### Describe alternatives you've considered.

R Studio can also be used but Python would be easier to work with.

### Add any other context or screenshots about the feature request here.

Dataset is already taken as medical_examination.csv

### PR DESCRIPTION
**Pull request by Viraj-Sanap**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)?

Yes, I have gone through the contributing guidelines.

### Description

This contribution is part of GirlScript Summer of Code 2022. This is a Machine Learning Basic Project to visualise medical data in the form of graphs.

Fixes #622 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Machine Learning Basic Project Contribution.

### CODE REVIEW

**Review by photon149 — APPROVED** [review]
@Viraj-Sanap well designed infographics 👍🏻 
No Duplicity ✅ 
Approved from my end.
@Kushal997-das @prakhar3062 have a look.

**Review by prakhar3062 — APPROVED** [review]

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Viraj-Sanap Please add any gif or image about your **project output** in `readme.md` file.

**Comment by Viraj-Sanap** [comment]
> @Viraj-Sanap Please add any gif or image about your **project output** in `readme.md` file.

@Kushal997-das I have already added the required screenshots in the readme.md file. As the code is just a visualiser, there are no more images apart from the output graphs.

**Comment by Kushal997-das** [comment]
> > @Viraj-Sanap Please add any gif or image about your **project output** in `readme.md` file.
> 
> @Kushal997-das I have already added the required screenshots in the readme.md file. As the code is just a visualiser, there are no more images apart from the output graphs.

save

see there is no such images

**Comment by Viraj-Sanap** [comment]
> > > @Viraj-Sanap Please add any gif or image about your **project output** in `readme.md` file.
> > 
> > 
> > @Kushal997-das I have already added the required screenshots in the readme.md file. As the code is just a visualiser, there are no more images apart from the output graphs.
> 
> save
> 
> see there is no such images

There is a mix-up, I haven't applied for that project yet. This pull request is for Medical Data Visualiser.  
This is the link: https://github.com/Viraj-Sanap/Project-Guidance/tree/main/Machine%20Learning%20and%20Data%20Science/Basic/Medical%20Data%20Visualizer

**Comment by photon149** [comment]
@Kushal997-das I guess you need to wait a little for the images to load as they seem to be heavy. I have checked this & they are visible to me
image
It is even mentioned in the raw of README file.

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
