### PR TITLE
Added Next13 Blogging Site

### LINKED ISSUE #782: Title: Blog Website using NEXT JS 13
### Project Type:
Web Development - Advanced

### Purpose:
A blogging website with an admin dashboard to manage blogs that would be based on next.js 13 with new server-side components and an app directory. Uses tailwind CSS to make clean UI and sanity.io for managing the cms/backend. 

### Technology:
- Next JS 13
- Typescript
- Tailwind CSS
- Sanity.io
- Framer Motion

### Add any other context or screenshots about the proposal request here.

Would request you assign me this issue with the SWOC3 Contributor tag.

### PR DESCRIPTION
**Pull request by ShivangM**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

### Description

A blogging website created using Next.js 13 and Sanity.io 3. 

- Users can post and edit blogs from Sanity Studio integrated into the website but log in with authenticated credentials.
- Users are able to read the blogs posted on the website.
- Users can enter preview mode and see the blog preview without even posting it, in real-time using the studio.
- Created using the latest technology and based on Typescript for robustness.

Fixes #782

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@ShivangM Please add images in your `readme.md` file in order to understand .

**Comment by ShivangM** [comment]
> @ShivangM Please add images in your `readme.md` file in order to understand .

Ok sure.

**Comment by ShivangM** [comment]
Updated the review file with screenshots and a detailed explanation of how to use it.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@ShivangM Kindly add the project output screenshots only and deploy this project , paste the link in `readme.md` file . Try to reduce image width and height also try to delete unwanted files those files are not required .

**Comment by Kushal997-das** [comment]
@ShivangM See it's a very basic landing page ,

1. Submit the project under basic folder.
2.  Sign up and sign bottom not working (if you made like this then it's okey)
3.  Try to change the project name to some logical name .

**Pull request closed without merging**
