### PR TITLE
School Management (New Project added)

### PR DESCRIPTION
**Pull request by UG-SEP**
## _Yes_, I have readed the contributing.md guidelines and try to implement it.
<a href="https://github.com/UG-SEP"></a> <br> <br>
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## No

### CODE REVIEW

**Review by SamarpanCoder2002 — COMMENTED** [review]
Looks good to me

**Review by SamarpanCoder2002 — APPROVED** [review]
LGTM

**Review by Kushal997-das — COMMENTED** [review]
@UG-SEP Great work .

**Comment by UG-SEP** [comment]
@Kushal997-das and @SamarpanCoder2002  
Thanks a lot for your _**beautiful**_ comments.
respect-احترام

**Pull request merged**
