### PR TITLE
Added restaurant

### LINKED ISSUE #799: New web dev project: Online restaurant
### Is your proposal related to a problem? Please describe.

A responsive online restaurant website using HTML, CSS, Bootstrap, and JavaScript. The project will fall under the category of web development (basic). The goal is to create a website that effectively showcases the restaurant's menu, location, and other relevant information to potential customers. Only the frontend part is included.

### Add any other context or screenshots about the proposal request here.

For desktop devices

pic1

For mobile devices

pic2

### PR DESCRIPTION
**Pull request by manisha-nair28**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

A responsive online restaurant website using HTML, CSS, Bootstrap, and JavaScript. The project will fall under the category of web development (basic). The goal is to create a website that effectively showcases the restaurant's menu, location, and other relevant information to potential customers. Only the frontend part is included.

Fixes #799 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

New web dev project: Online restaurant #799

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@manisha-nair28 Please add images in readme also deploy your project and paste the link in `readme.md` file , do these changes first .

**Comment by manisha-nair28** [comment]
Updated the README.md and made the changes.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@manisha-nair28 Looks good , kindly add this project name in [`readme.,d`](https://github.com/manisha-nair28/Project-Guidance/blob/Manisha's-branch/Web%20Development/README.md) file under basic section in alphabetical order .

**Comment by manisha-nair28** [comment]
@Kushal997-das done please check

**Review by Kushal997-das — APPROVED** [review]
@manisha-nair28 👍🏻

**Pull request merged**
