### PR TITLE
Router Synchronization Project

### PR DESCRIPTION
**Pull request by TawfikYasser**
Hi,

This PR for adding the Router Synchronization Application

The project description in the README file

I hope you finds this project well

Assigned with issue #56 

Thanks

### CODE REVIEW

**Comment by TawfikYasser** [comment]
I made some updated in my previous project README files.
in last 3 commits.

Thanks

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Looks good to me but please fetch the project first . Then send PR

**Comment by TawfikYasser** [comment]
> 
> 
> Looks good to me but please fetch the project first . Then send PR

Sorry I can not understand you!

**Comment by Kushal997-das** [comment]
> > Looks good to me but please fetch the project first . Then send PR
> 
> Sorry I can not understand you!

You don't have updated repository please make this even with the original repository then send a PR .

**Comment by TawfikYasser** [comment]
I’m really confused, I’m already forked the repository, Then I made changes and opend a PR, As everyday!
Please explain to me :)

**Comment by Kushal997-das** [comment]
> I’m really confused, I’m already forked the repository, Then I made changes and opend a PR, As everyday!
> Please explain to me :)

Please fetch this repo you don't have updated repo. 
Don't fork it again and again use git bash .
Watch git and github - https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV
How to fetch the repo -  https://youtu.be/-zvHQXnBO6c

**Comment by TawfikYasser** [comment]
> 
> 
> > I’m really confused, I’m already forked the repository, Then I made changes and opend a PR, As everyday!
> > Please explain to me :)
> 
> Please fetch this repo you don't have updated repo.
> Don't fork it again and again use git bash .
> Watch git and github - https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV
> How to fetch the repo - https://youtu.be/-zvHQXnBO6c

Oh, Okay, Sorry I will fix that.

**Comment by TawfikYasser** [comment]
Now I think chnages are done.

**Comment by Kushal997-das** [comment]
> > > I’m really confused, I’m already forked the repository, Then I made changes and opend a PR, As everyday!
> > > Please explain to me :)
> > 
> > 
> > Please fetch this repo you don't have updated repo.
> > Don't fork it again and again use git bash .
> > Watch git and github - https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV
> > How to fetch the repo - https://youtu.be/-zvHQXnBO6c
> 
> Oh, Okay, Sorry I will fix that.

See Your repo behind the original repo.
project1 (2)_LI

**Comment by TawfikYasser** [comment]
> 
> 
> > > > I’m really confused, I’m already forked the repository, Then I made changes and opend a PR, As everyday!
> > > > Please explain to me :)
> > > 
> > > 
> > > Please fetch this repo you don't have updated repo.
> > > Don't fork it again and again use git bash .
> > > Watch git and github - https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV
> > > How to fetch the repo - https://youtu.be/-zvHQXnBO6c
> > 
> > 
> > Oh, Okay, Sorry I will fix that.
> 
> See Your repo behind the original repo.
> project1 (2)_LI

Okay, Sorry for that

**Comment by TawfikYasser** [comment]
It’s ok now ?

**Comment by Kushal997-das** [comment]
> It’s ok now ?

Lemme check 👍🏻

**Comment by TawfikYasser** [comment]
Thanks @Kushal997-das , And sorry for the conflicts.

**Pull request merged**
