### PR TITLE
Added My 4 Web Dev Project to this repo[GSSOC'22 Contributor]

### LINKED ISSUE #202: Add My 4 Web Dev Project to this repo[GSSOC'22 Contributor]
## 🚀 Feature
I want to add 4 web dev projects(all are static webpages hosted on GitHub) to this repository.
**I am contributor at GSSoC'22. Please assign this issue to me.**

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

## Motivation

1. [Netflix Clone](https://github.com/Susmita-Dey/Netflix-Clone-With-HTML-CSS-JS)
2. [Facebook Login Page Clone](https://github.com/Susmita-Dey/Facebook-Login-Page-Clone-Tailwind-CSS)
3. [Password Generator](https://github.com/Susmita-Dey/Password-Generator)
4. [Happy New Year Countdown Timer Project](https://github.com/Susmita-Dey/Happy-New-Year-CountDown-Timer-Project)

## Pitch

Folks can get inspired via this projects

### PR DESCRIPTION
**Pull request by Susmita-Dey**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

(Write your answer here.)

Fixes #202 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

I have added my 4 web dev projects to beginners and intermediate folders. I'm a GSSoC'22 contributor. Kindly merge it to main.

### CODE REVIEW

**Review by Kushal997-das — APPROVED** [review]
LGTM 👍 


@prakhar3062 @photon149 Please check !!

**Comment by Kushal997-das** [comment]
@Susmita-Dey For this time it's okey but for next time if you contribute to this project then please add one project per PR please keep this mind .

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey For this time it's okey but for next time if you contribute to this project then please add one project per PR please keep this mind . 

Shall I take back my other projects then and keep only one?

**Comment by Kushal997-das** [comment]
@Susmita-Dey It's Okey for now if you want to add more project then you have to add one project per PR.

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey It's Okey for now if you want to add more project then you have to add one project per PR. 

Okay, then I'll add my other projects and create an issue and PR one for each.

**Review by prakhar3062 — APPROVED** [review]
@photon149 okay from my side

**Comment by photon149** [comment]
@Susmita-Dey once you create those individual PRs , do close this PR from your side.

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey once you create those individual PRs , do close this PR from your side.

That means you won't merge this PR?

**Comment by photon149** [comment]
@Susmita-Dey We don't mind merging this PR , but just to let you know , that even though you would add 4 projects in the same PR , it still counts as a single PR from GSSOC perspectives.

**Comment by Susmita-Dey** [comment]
Oh

> @Susmita-Dey We don't mind merging this PR , but just to let you know , that even though you would add 4 projects in the same PR , it still counts as a single PR from GSSOC perspectives.

Okay, I understand. So, shall I'm take back my files of the other 3 projects and keeping here one? Then, I'll create each PR after creating an issue for my other projects. I think this would a better idea.

**Comment by photon149** [comment]
Yeah that would be better .
go ahead @Susmita-Dey

**Comment by Susmita-Dey** [comment]
> Yeah that would be better . go ahead @Susmita-Dey

Okay, thanks

**Comment by Susmita-Dey** [comment]
> Yeah that would be better . go ahead @Susmita-Dey

Sorry, I have to close this PR as I ran into some conflicts. I will create each  individuals PRs for each project.

**Pull request closed without merging**
