### PR TITLE
Added RGB Color Slider Project

### LINKED ISSUE #1175: Add RGB Color Slider Project
I would like to RGB Color Slider Project . It renders the color based on R,G,B values given by users.
Screenshot 2024-06-05 124103

### PR DESCRIPTION
**Pull request by AmrutaJayanti**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

### Description

RGB Color Slider Project

Fixes #1175 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

RGB Color Slider

### CODE REVIEW

**Review by Kushal997-das — COMMENTED** [review]
@AmrutaJayanti I noticed that the same project has been added to another repository. Submitting multiple pull requests for the same project across different repositories is not permitted, as it is considered spam and doesn't make sense.

[here](https://github.com/Avdhesh-Varshney/WebMasterLog/pull/242)

**Comment by AmrutaJayanti** [comment]
@Kushal997-das Sorry for the inconvenience . I actually raised issue once at both repo but I was assigned there ,so I created PR.
But to show change from both I have extra created a feature of converting rgb into hexacode .

**Comment by Kushal997-das** [comment]
@AmrutaJayanti, please ensure to add some additional features. I will review this thoroughly.

**Comment by Kushal997-das** [comment]
@AmrutaJayanti, please ensure to add some additional features. I will review this thoroughly.

**Comment by AmrutaJayanti** [comment]
@Kushal997-das I have raised another PR for same .Please approve . Thanks for understanding

**Pull request closed without merging**
