### PR TITLE
Added Flipbook Project

### LINKED ISSUE #378: Add a FlipBook
### Is your feature request related to a problem? Please describe.
I want to add a flipbook project which I have made. 

### Describe the solution you'd like.
This is responsive.

###Tech Stack
- [x] HTML
- [x] CSS
- [x] JavaScript

### Add any other context or screenshots about the feature request here.
image
image

### PR DESCRIPTION
**Pull request by shivam123-dev**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

I have all read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) and followed it.

### Description

This PR regarding the adding of a flipbook project.

Fixes #378 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### Screenshots
image
image
image
image

### CODE REVIEW

**Review by photon149 — CHANGES_REQUESTED** [review]
@shivam123-dev Please Do the following Changes.
- Enhance your README file alongside aligning and resizing the images 
- Add Comments to your code wherever necessary

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@shivam123-dev Please describe or write bit about `flipbook` into your `readme.md` file.

**Comment by shivam123-dev** [comment]
@photon149 @Kushal997-das I have made changes as per your suggestion

**Review by Kushal997-das — APPROVED** [review]
@shivam123-dev Great 👍

**Comment by Kushal997-das** [comment]
@photon149 Please check !!

**Review by photon149 — CHANGES_REQUESTED** [review]
@shivam123-dev Please resize the images in your README file.

**Comment by shivam123-dev** [comment]
@photon149 Please once check my PR

**Comment by photon149** [comment]
Approved from my end.
@prakhar3062 have a look.

**Review by prakhar3062 — APPROVED** [review]
okay from my end

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
