### PR TITLE
Pinterest Static 

### LINKED ISSUE #520: Pinterest Static website
### Is your feature request related to a problem? Please describe.

It is a fully responsive static website that I have made with pure HTML CSS and JS. 

I have checked all the previous issues and current projects in the web dev. folder. This is a new addition to Project Guidance.

I would like to contribute to this issue under GSSOC'22

### Describe the solution you'd like.

None

### Describe alternatives you've considered.

no responce

### Add any other context or screenshots about the feature request here.

idk

### PR DESCRIPTION
**Pull request by VaibhavUpreti**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description
Added pinterest fully responsive static website.

(Write your answer here.)

Fixes #520 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by VaibhavUpreti** [comment]
Contribution made under Gssoc'22... :)

**Comment by Kushal997-das** [comment]
@VaibhavUpreti Wait till your issue been assigned .

**Comment by VaibhavUpreti** [comment]
This page is hosted at 

https://vaibhavupreti.github.io/pinterest-static/

**Review by photon149 — COMMENTED** [review]
@VaibhavUpreti Nice one
No duplicity ✔️ 
Just one minor change , enhance your README file a little more.

**Comment by VaibhavUpreti** [comment]
Sure

**Comment by VaibhavUpreti** [comment]
I have updated the readme 👍

**Review by prakhar3062 — APPROVED** [review]

**Review by photon149 — APPROVED** [review]
Great.
Approved from my end.
@Kushal997-das pls review and merge the same.

**Review by Kushal997-das — APPROVED** [review]

**Comment by VaibhavUpreti** [comment]
Hey @Kushal997-das I had some changes in the project..... I had updated the CSS a bit and also I had removed the images from the folder and added them as links to reduce the storage of the project.... can I revert this PR and commit these changes then u can merge it ... does that sound good? Also I need to add some comments and make the code base more understandable for folks

**Comment by Kushal997-das** [comment]
> Hey @Kushal997-das I had some changes in the project..... I had updated the CSS a bit and also I had removed the images from the folder and added them as links to reduce the storage of the project.... can I revert this PR and commit these changes then u can merge it ... does that sound good? Also I need to add some comments and make the code base more understandable for folks

Yeah go ahead 👍

**Pull request merged**
