### PR TITLE
Heart Disease Prediction Completed 

### LINKED ISSUE #475: Heart Disease Prediction
### Is your feature request related to a problem? Please describe.

Yes, since it comes using Machine Learning

### Describe the solution you'd like.

I will use Logistic Regression using Library

### Describe alternatives you've considered.

If not using Library then I will apply statistics mathematical formulas to solve this

### Add any other context or screenshots about the feature request here.

/-

### PR DESCRIPTION
**Pull request by Kumar-laxmi**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes, I have read it

### Description

This PR solved issue on Heart Disease Prediction using Logistic Regression

Fixes #475 

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Related issue no. 475

### CODE REVIEW

**Comment by Kumar-laxmi** [comment]
@Kushal997-das is this PR ok?

**Review by photon149 — CHANGES_REQUESTED** [review]
No Duplicity ✅ 
@Kumar-laxmi  Please do these changes.
- Please attach a README file to the same.
- Add Multiple Models (at least 3 )
- In the README file , you can mention comparison of models used.

**Comment by Kumar-laxmi** [comment]
@photon149 Ok

**Comment by Kumar-laxmi** [comment]
> No Duplicity ✅ @Kumar-laxmi Please do these changes.
> 
> * Please attach a README file to the same.
> * Add Multiple Models (at least 3 )
> * In the README file , you can mention comparison of models used.

Please have a look at the the recent changes, I have done all the required changes @photon149 @Kushal997-das

**Comment by Kumar-laxmi** [comment]
@Kushal997-das Pls have a look at this PR

**Review by Kushal997-das — APPROVED** [review]
@prakhar3062 Have a look .

**Pull request merged**
