### PR TITLE
Amazon landing page

### LINKED ISSUE #1167: Title: Amazon Landing Page
### Is your proposal related to a problem? Please describe.

I would like to contribute by adding my project in Web Development folder. My project is landing page of Amazon. I built a clone of Amazon using HTML and CSS.

### Add any other context or screenshots about the proposal request here.

_No response_

### PR DESCRIPTION
**Pull request by saiumasankar**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes. I followed the guidelines which are stated in Contributing guidelines.

### Description

I added my amazon landing page clone project files in Basic folder of Web development. It comprises of HTML, CSS and some image files.

Fixes #1167 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by saiumasankar** [comment]
@Kushal997-das Please review this PR.

**Comment by saiumasankar** [comment]
@Kushal997-das Please review this PR and merge it.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@saiumasankar Please make the following changes:

1. Add all the images in one folder, let's call it 'Images'.
2. Add your project to the [readme.md](https://github.com/Kushal997-das/Project-Guidance/tree/main/Web%20Development#level-1-basic-) file.

**Comment by saiumasankar** [comment]
@Kushal997-das I have done the changes asked by you. Please review this PR.

**Review by Kushal997-das — APPROVED** [review]

**Pull request merged**
