### PR TITLE
Block Mario Game (done Chenges)

### LINKED ISSUE #657: JavaScript Game
### Is your proposal related to a problem? Please describe.

- Its A game.
- webdev
- html css js

### PR DESCRIPTION
**Pull request by DragonUncaged**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

yes

### Description

Game

Fixes #657 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
image

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
`Web Development/Basic/Block Retro Mario Game/` Please add your project in this directory .

**Comment by DragonUncaged** [comment]
> 

done!!

**Review by Kushal997-das — APPROVED** [review]

**Comment by Kushal997-das** [comment]
@photon149 have a look .

**Review by photon149 — APPROVED** [review]
Lookks good to me
Approved.
@Kushal997-das @prakhar3062 have a look

**Pull request merged**
