### PR TITLE
Addition of new domain called as Cyber Security

### PR DESCRIPTION
**Pull request by NANDAGOPALNG**
# Project-Guidance! 🎊🎈

### Welcome! 🎉

Thank you for visiting our repository! We're excited to have you here. If you find this project useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description 

I have added anew folder for Cyber Security and added one project each for basic,medium and advanced as of now i will add more project once you review it and i still have to update the website part as well once you review it

### 🏷️ Initiative Participation *(Required)*

This pull request is associated with the following initiative. Please choose the one you are contributing to:

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [ ] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [x] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Comment by NANDAGOPALNG** [comment]
Hey there I just added a new README.md file for Cyber Security domain and also updated index html to get a new domain on website page, i have updated a new image for the cyber security domain and if you review it i can add more projects in this domain Thank you

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@NANDAGOPALNG, only one project is allowed. Please add your project under either the basic, intermediate, or advanced section , but one only.

**Comment by NANDAGOPALNG** [comment]
OK I have only given Basic Project @Kushal997-das

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Hi @NANDAGOPALNG,

I noticed that this project appears to be a standard text file, which does not meet our expectations. You can see the file [here](https://github.com/NANDAGOPALNG/Project-Guidance/blob/main/Cyber%20Security/Basic). Additionally, the README.md file lacks clarity, which can be found [here](https://github.com/NANDAGOPALNG/Project-Guidance/blob/main/Cyber%20Security/README.md). Could you please provide more details about the project?

Thank you!

**Comment by NANDAGOPALNG** [comment]
hi @Kushal997-das  as this is my first time contributing in open source due to lack of experience i had made these mistakes but now i have elaborated the readme file in this commit kindly verify

**Review by Kushal997-das — COMMENTED** [review]
@NANDAGOPALNG Hi, I’m closing this issue as the files are not appropriate yet. Please try to open a new issue that you would love to solve. Thank you!

**Pull request closed without merging**
