### PR TITLE
Refactored Age Calculation Logic with Improved Date Handling

### PR DESCRIPTION
**Pull request by KashishJuneja101003**
# Project-Guidance! 🎊🎈

### Welcome! 🎉

Thank you for visiting our repository! We're excited to have you here. If you find this project useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [x] YES
- [ ] NO

### 📝 Description
I refactored the existing code in age.py to improve the accuracy and readability of the age calculation logic. Specifically, I addressed the following points:
1. Improved Date Handling: The code now accurately handles cases where the day or month of the birthday has not yet occurred in the current year. This is done by adjusting the year and month calculations accordingly.
2. Day Calculation Fix: If the days between the birthday and the current date are negative (meaning the current day is earlier than the birthday day), the month is decremented, and the correct number of days in the previous month is used to adjust the day count. This ensures that the output always shows non-negative values for days.
3. Month Calculation Adjustment: If the months between the current date and birthday are negative (i.e., the birthday month is later in the year than the current month), the year is decremented by 1, and the months are adjusted to ensure that the final age is displayed accurately.
4. Error Handling: Improved the error handling mechanism to catch invalid date formats and provide user-friendly messages.

### 🔧 Fixes #issue_no (Required)
Issue number #1358 

### 🏷️ Initiative Participation (Required)
This pull request is associated with the following initiative. Please choose the one you are contributing to:

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

### CODE REVIEW

**Comment by KashishJuneja101003** [comment]
I changed to entire code, thus I uploaded a different file for the updates code namely "Updated age.py".
I’m new to GSSoC and GitHub, so please forgive me if I made any mistakes during this process. I appreciate any feedback you may have, and let me know if any changes are required.
Thank You!

**Comment by Kushal997-das** [comment]
> I changed to entire code, thus I uploaded a different file for the updates code namely "Updated age.py".
> 
> I’m new to GSSoC and GitHub, so please forgive me if I made any mistakes during this process. I appreciate any feedback you may have, and let me know if any changes are required.
> 
> **Kindly assign the level too.**
> 
> Thank You!

@KashishJuneja101003 No worries, feel free to ask your question , please update the existing file instead of creating a new one.

**Comment by KashishJuneja101003** [comment]
@Kushal997-das 
I tried to clone the repository but I couldn't. The repository is very big in size maybe that's why.
Thus, I had to upload a different file.
Kindly, let me know if there is any other way to do the same.
Thank you!

**Comment by Kushal997-das** [comment]
Hi @KashishJuneja101003 ,

I noticed that you've already cloned the project. Could you please update the existing .py file with the necessary changes instead of creating a new file?

Thank you!

**Comment by KashishJuneja101003** [comment]
Kindly review my pull request.
Thank You!

**Review by Kushal997-das — COMMENTED** [review]
Hi @KashishJuneja101003 ,
I wanted to address a logical inconsistency regarding the dates provided. A date of birth (DOB) of 10/10/2003 (October 10, 2003) cannot occur before today's date of 03/10/2003 (March 10, 2003) within the same year.

To clarify:

- DOB: 10/10/2003 indicates the person was born on October 10, 2003.
- Today's Date: 03/10/2003 signifies it is March 10, 2003.

Since the DOB falls later in the year than today’s date, it is not possible for someone to be born on October 10, 2003, before March 10, 2003.

Given this clarification, I will be closing this PR and issue.

Thank you for your understanding.

**Comment by Kushal997-das** [comment]
Hi @KashishJuneja101003,

I noticed there's some conflict arising. Can you please take a moment to discuss and resolve it? 

Thanks!

**Comment by KashishJuneja101003** [comment]
I resolved this issue.
Kindly check if PR gets merged now.
Thank You!

**Review by Kushal997-das — APPROVED** [review]

**Comment by KashishJuneja101003** [comment]
Hello,
My issue #1358 is still active. Could you please close this issue under pull request #1425 
Thank You!

**Pull request merged**
