### PR TITLE
Added weight-convertor project

### LINKED ISSUE #826: Title: Add a weight converter project in web development
### Is your proposal related to a problem? Please describe.

It will just convert weight from kgs to gms and other units.

### Add any other context or screenshots about the proposal request here.

_No response_

### PR DESCRIPTION
**Pull request by palaksinghania05**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes.

### Description

A simple weight converter project in which the user enters the weight in kilograms and it gets converted to grams, pounds and ounces.

Fixes #826 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@palaksinghania05  Images are not loading in `readme.md` file also deploy your project and add the deployment link in `readme.md` file .

**Comment by palaksinghania05** [comment]
@Kushal997-das I have made the required changes. Kindly approve and merge.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@palaksinghania05  Kindly reduce image width and height .

**Comment by palaksinghania05** [comment]
@Kushal997-das I have adjusted the size. If I reduce it further, then it will get compressed and the content will not be visible.

**Review by Kushal997-das — APPROVED** [review]
@palaksinghania05  Great work

**Pull request merged**
