### PR TITLE
Autism Identification system #976

### LINKED ISSUE #976: Title: Autism Identification System
### Is your proposal related to a problem? Please describe.

Problem statement:- Autistic Spectrum Disorder (ASD) is a neurodevelopmental condition associated with significant healthcare costs, and early diagnosis can significantly reduce these. However, the current wait times for ASD diagnosis are prolonged, and existing procedures lack cost-effectiveness. A time-efficient and accessible ASD screening tool is essential to aid healthcare professionals and guide individuals toward pursuing formal clinical diagnosis. The goal is to develop machine learning techniques to make this screening process faster and more effective.

Please assign me to this issue under tag gssoc'24 

### Add any other context or screenshots about the proposal request here.

I want to add this project proposal to machine learning beginner level project which enables them to have hands on experience. I request you to assign me under gssoc'24 @Kushal997-das

### PR DESCRIPTION
**Pull request by Thewhitewolfsasi**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #976 

### Checklist

- [yes ] I've read the contribution guidelines.
- [ yes] I've checked the issue list before deciding what to submit.
- [ yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

I have made the requested correction in this pr

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
@Thewhitewolfsasi 

1. Your `readme.md` file not neat and clean make sure not to add multiples stuff only mentioned in short and point to point, no need to give you social media details,if you want to try to make the size of button too small.
2. Update the project under [this](https://github.com/Kushal997-das/Project-Guidance/blob/main/Machine%20Learning%20and%20Data%20Science/README.md)

**Comment by Thewhitewolfsasi** [comment]
Sir @Kushal997-das I made the requested changes in main branch. Can you check it and PR under gssoc tag

**Review by Kushal997-das — APPROVED** [review]
@Thewhitewolfsasi Good work 💯

**Comment by Kushal997-das** [comment]
@Thewhitewolfsasi This branch has conflicts kindly fetch the update version of my project from your end.

**Comment by Kushal997-das** [comment]
@Thewhitewolfsasi Hello i found the same project being merged in another repo which can't be accept.

Closing this as spam .

Thanks 

[Report](https://github.com/Niketkumardheeryan/ML-CaPsule/pull/578)

**Pull request closed without merging**
