### PR TITLE
Adding a to do app

### PR DESCRIPTION
**Pull request by Jordistyd**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

I have read the contributing guidelines specified by the repo

### Description

A basic to do web app using the Django framework.
keeps assignments and their due dates.

### Checklist

- [ X] I've read the contribution guidelines.
- [ X] I've checked the issue list before deciding what to submit.
- [ X] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Please add one gif into the `readme.md` file for better understanding @Jordistyd

**Comment by Jordistyd** [comment]
Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das

**Comment by Kushal997-das** [comment]
> Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das

[On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd

**Comment by Jordistyd** [comment]
Hey, I updated the readme with a gif, feel free to update me if any changes are needed @Kushal997-das

**Comment by Jordistyd** [comment]
> > Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das
> 
> 
> 
> [On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd 


@Kushal997-das I updated the readme file :)

**Comment by Kushal997-das** [comment]
> > > Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das
> > 
> > 
> > [On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd
> 
> @Kushal997-das I updated the readme file :)

Your gif is not working fine please check @Jordistyd

**Comment by Jordistyd** [comment]
> > > > Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das
> > > 
> > > 
> > > [On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd
> > 
> > 
> > @Kushal997-das I updated the readme file :)
> 
> Your gif is not working fine please check @Jordistyd

The gif is working fine now I just needed to upload it to the project, thank you! @Kushal997-das

**Comment by Kushal997-das** [comment]
> > > > > Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das
> > > > 
> > > > 
> > > > [On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd
> > > 
> > > 
> > > @Kushal997-das I updated the readme file :)
> > 
> > 
> > Your gif is not working fine please check @Jordistyd
> 
> The gif is working fine now I just needed to upload it to the project, thank you! @Kushal997-das

Please fetch this repo first then i gonna merge Thanks @Jordistyd

**Comment by Jordistyd** [comment]
> > > > > > Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das
> > > > > 
> > > > > 
> > > > > [On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd
> > > > 
> > > > 
> > > > @Kushal997-das I updated the readme file :)
> > > 
> > > 
> > > Your gif is not working fine please check @Jordistyd
> > 
> > 
> > The gif is working fine now I just needed to upload it to the project, thank you! @Kushal997-das
> 
> Please fetch this repo first then i gonna merge Thanks @Jordistyd

Hey I fetched the repo on to my machine, do I need to commit to see the changes?
let me know, thanks!

**Comment by Kushal997-das** [comment]
> > > > > > > Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das
> > > > > > 
> > > > > > 
> > > > > > [On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd
> > > > > 
> > > > > 
> > > > > @Kushal997-das I updated the readme file :)
> > > > 
> > > > 
> > > > Your gif is not working fine please check @Jordistyd
> > > 
> > > 
> > > The gif is working fine now I just needed to upload it to the project, thank you! @Kushal997-das
> > 
> > 
> > Please fetch this repo first then i gonna merge Thanks @Jordistyd
> 
> Hey I fetched the repo on to my machine, do I need to commit to see the changes?
> let me know, thanks!

You should push from local to origin .

**Comment by Jordistyd** [comment]
> > > > > > > > Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das
> 
> > > > > > > 
> 
> > > > > > > 
> 
> > > > > > > [On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > @Kushal997-das I updated the readme file :)
> 
> > > > > 
> 
> > > > > 
> 
> > > > > Your gif is not working fine please check @Jordistyd
> 
> > > > 
> 
> > > > 
> 
> > > > The gif is working fine now I just needed to upload it to the project, thank you! @Kushal997-das
> 
> > > 
> 
> > > 
> 
> > > Please fetch this repo first then i gonna merge Thanks @Jordistyd
> 
> > 
> 
> > Hey I fetched the repo on to my machine, do I need to commit to see the changes?
> 
> > let me know, thanks!
> 
> 
> 
> You should push from local to origin .

I have pushed to origin under jordibranch, the terminal says that everything is up to date with the main branch, anything else that needs to be done?
@Kushal997-das

**Comment by Kushal997-das** [comment]
> > > > > > > > > Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das
> > 
> > 
> > > > > > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > > > > > > [On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd
> > 
> > 
> > > > > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > > > > > @Kushal997-das I updated the readme file :)
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > Your gif is not working fine please check @Jordistyd
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > The gif is working fine now I just needed to upload it to the project, thank you! @Kushal997-das
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Please fetch this repo first then i gonna merge Thanks @Jordistyd
> > 
> > 
> > > 
> > 
> > 
> > > Hey I fetched the repo on to my machine, do I need to commit to see the changes?
> > 
> > 
> > > let me know, thanks!
> > 
> > 
> > You should push from local to origin .
> 
> I have pushed to origin under jordibranch, the terminal says that everything is up to date with the main branch, anything else that needs to be done?
> @Kushal997-das

Everything is up to date in your local not origin try this command `git push origin master`

**Comment by Jordistyd** [comment]
> > > > > > > > > > Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das
> > > 
> > > 
> > > > > > > > >
> > > 
> > > 
> > > > > > > > >
> > > 
> > > 
> > > > > > > > > [On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd
> > > 
> > > 
> > > > > > > >
> > > 
> > > 
> > > > > > > >
> > > 
> > > 
> > > > > > > > @Kushal997-das I updated the readme file :)
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > Your gif is not working fine please check @Jordistyd
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > > The gif is working fine now I just needed to upload it to the project, thank you! @Kushal997-das
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > Please fetch this repo first then i gonna merge Thanks @Jordistyd
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Hey I fetched the repo on to my machine, do I need to commit to see the changes?
> > > 
> > > 
> > > > let me know, thanks!
> > > 
> > > 
> > > You should push from local to origin .
> > 
> > 
> > I have pushed to origin under jordibranch, the terminal says that everything is up to date with the main branch, anything else that needs to be done?
> > @Kushal997-das
> 
> Everything is up to date in your local not origin try this command `git push origin master`

oohhh ok I saw my mistake.
had to run the command git push origin HEAD:main to get it to work but its updated now

**Comment by Kushal997-das** [comment]
> > > > > > > > > > > Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das
> > > > 
> > > > 
> > > > > > > > > >
> > > > 
> > > > 
> > > > > > > > > >
> > > > 
> > > > 
> > > > > > > > > > [On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd
> > > > 
> > > > 
> > > > > > > > >
> > > > 
> > > > 
> > > > > > > > >
> > > > 
> > > > 
> > > > > > > > > @Kushal997-das I updated the readme file :)
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > Your gif is not working fine please check @Jordistyd
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > > > The gif is working fine now I just needed to upload it to the project, thank you! @Kushal997-das
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > Please fetch this repo first then i gonna merge Thanks @Jordistyd
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > Hey I fetched the repo on to my machine, do I need to commit to see the changes?
> > > > 
> > > > 
> > > > > let me know, thanks!
> > > > 
> > > > 
> > > > You should push from local to origin .
> > > 
> > > 
> > > I have pushed to origin under jordibranch, the terminal says that everything is up to date with the main branch, anything else that needs to be done?
> > > @Kushal997-das
> > 
> > 
> > Everything is up to date in your local not origin try this command `git push origin master`
> 
> oohhh ok I saw my mistake.
> had to run the command git push origin HEAD:main to get it to work but its updated now

You still 7 commits behind the original repo @Jordistyd

**Comment by Jordistyd** [comment]
> > > > > > > > > > > > Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > > > > > [On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > > > > @Kushal997-das I updated the readme file :)
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > > > Your gif is not working fine please check @Jordistyd
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > > The gif is working fine now I just needed to upload it to the project, thank you! @Kushal997-das
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > Please fetch this repo first then i gonna merge Thanks @Jordistyd
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > 
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > Hey I fetched the repo on to my machine, do I need to commit to see the changes?
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > let me know, thanks!
> 
> > > > > 
> 
> > > > > 
> 
> > > > > You should push from local to origin .
> 
> > > > 
> 
> > > > 
> 
> > > > I have pushed to origin under jordibranch, the terminal says that everything is up to date with the main branch, anything else that needs to be done?
> 
> > > > @Kushal997-das
> 
> > > 
> 
> > > 
> 
> > > Everything is up to date in your local not origin try this command `git push origin master`
> 
> > 
> 
> > oohhh ok I saw my mistake.
> 
> > had to run the command git push origin HEAD:main to get it to work but its updated now
> 
> 
> 
> You still 7 commits behind the original repo @Jordistyd 

Hey, am I still behind? I just updated

**Comment by Kushal997-das** [comment]
> > > > > > > > > > > > > Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > > > > > [On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > > > > @Kushal997-das I updated the readme file :)
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > > > Your gif is not working fine please check @Jordistyd
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > > The gif is working fine now I just needed to upload it to the project, thank you! @Kushal997-das
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > Please fetch this repo first then i gonna merge Thanks @Jordistyd
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > Hey I fetched the repo on to my machine, do I need to commit to see the changes?
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > let me know, thanks!
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > You should push from local to origin .
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > I have pushed to origin under jordibranch, the terminal says that everything is up to date with the main branch, anything else that needs to be done?
> > 
> > 
> > > > > @Kushal997-das
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Everything is up to date in your local not origin try this command `git push origin master`
> > 
> > 
> > > 
> > 
> > 
> > > oohhh ok I saw my mistake.
> > 
> > 
> > > had to run the command git push origin HEAD:main to get it to work but its updated now
> > 
> > 
> > You still 7 commits behind the original repo @Jordistyd
> 
> Hey, am I still behind? I just updated

Yes

**Comment by Jordistyd** [comment]
> > > > > > > > > > > > > > Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > > > > > > [On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > > > > > @Kushal997-das I updated the readme file :)
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > > > > Your gif is not working fine please check @Jordistyd
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > > > The gif is working fine now I just needed to upload it to the project, thank you! @Kushal997-das
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > > Please fetch this repo first then i gonna merge Thanks @Jordistyd
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > Hey I fetched the repo on to my machine, do I need to commit to see the changes?
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > > let me know, thanks!
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > >
> > > 
> > > 
> > > > > > > You should push from local to origin .
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > > I have pushed to origin under jordibranch, the terminal says that everything is up to date with the main branch, anything else that needs to be done?
> > > 
> > > 
> > > > > > @Kushal997-das
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > Everything is up to date in your local not origin try this command `git push origin master`
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > oohhh ok I saw my mistake.
> > > 
> > > 
> > > > had to run the command git push origin HEAD:main to get it to work but its updated now
> > > 
> > > 
> > > You still 7 commits behind the original repo @Jordistyd
> > 
> > 
> > Hey, am I still behind? I just updated
> 
> Yes

Hi, Sorry for all of the inconvinience, I fetched everything from main and merged it, should be fine now
please let me know and thank you!

**Comment by Kushal997-das** [comment]
> > > > > > > > > > > > > > > Of course! Just to be clear, a gif of my app? And in which readme? Mine or the repo's main one? @Kushal997-das
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > > > > > > [On this file](https://github.com/Jordistyd/Project-Guidance/blob/jordibranch/Web%20Development/Basic/To%20Do%20App/README.md) @Jordistyd
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > > > > > @Kushal997-das I updated the readme file :)
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > > > > Your gif is not working fine please check @Jordistyd
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > > > The gif is working fine now I just needed to upload it to the project, thank you! @Kushal997-das
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > > Please fetch this repo first then i gonna merge Thanks @Jordistyd
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > Hey I fetched the repo on to my machine, do I need to commit to see the changes?
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > > let me know, thanks!
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > >
> > > > 
> > > > 
> > > > > > > > You should push from local to origin .
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > > > I have pushed to origin under jordibranch, the terminal says that everything is up to date with the main branch, anything else that needs to be done?
> > > > 
> > > > 
> > > > > > > @Kushal997-das
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > Everything is up to date in your local not origin try this command `git push origin master`
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > oohhh ok I saw my mistake.
> > > > 
> > > > 
> > > > > had to run the command git push origin HEAD:main to get it to work but its updated now
> > > > 
> > > > 
> > > > You still 7 commits behind the original repo @Jordistyd
> > > 
> > > 
> > > Hey, am I still behind? I just updated
> > 
> > 
> > Yes
> 
> Hi, Sorry for all of the inconvinience, I fetched everything from main and merged it, should be fine now
> please let me know and thank you!

Now it's fine @Jordistyd

**Review by Kushal997-das — APPROVED** [review]
LGTM 👍

**Pull request merged**
