### PR TITLE
Add a web development project

### PR DESCRIPTION
**Pull request by TawfikYasser**
Hi,

This PR to add a new web development project assigned with issue #48

The project developed with:

JSP
Servlets
HTML5 & CSS3
JavaScript & JQuery
Ajax
MySQL
I hope this project helps other developers.

### CODE REVIEW

**Review by SamarpanCoder2002 — COMMENTED** [review]
It's an amazing project.... It looks really good.... We are very happy to have a contributor like you...Love your good effort.....Expecting more projects from you.....Thanks for your interest...

**Comment by TawfikYasser** [comment]
> It's an amazing project.... It looks really good.... We are very happy to have a contributor like you...Love your good effort.....Expecting more projects from you.....Thanks for your interest...

Thank you very much, It’s a great chance for me to be one of this great repository.
I hope we all do more.

**Comment by SamarpanCoder2002** [comment]
> > It's an amazing project.... It looks really good.... We are very happy to have a contributor like you...Love your good effort.....Expecting more projects from you.....Thanks for your interest...
> 
> Thank you very much, It’s a great chance for me to be one of this great repository.
> I hope we all do more.

Yah...More new and interesting projects coming soon

**Review by Kushal997-das — COMMENTED** [review]
Looks good to me 💯

**Pull request merged**
