### PR TITLE
LLM (LANGCHAIN GEN AI) folder

### LINKED ISSUE #1001: GSSOC'24 Want to add my project "A complete Langchain GEN AI Pack".
### Is your proposal related to a problem? Please describe.

Absolutely. As language models (LLMs) advance rapidly, there's a rising interest in exploring, contributing to, and learning from projects in this field. I would like to add my project that I have on my github account.

What if we create a new folder exclusively for projects related to LangChain generative AI?

What outcome are you hoping for?
Looking to organize projects focused on LangChain generative AI into a dedicated folder under Artificial Intelligence. This way, we can efficiently showcase and collaborate on projects using APIs like Gemini and ChatGPT, as well as frameworks like LangChain.

### Add any other context or screenshots about the proposal request here.

This is how it looks like.
Screenshot 2024-05-13 001058

### PR DESCRIPTION
**Pull request by VarsaGupta**
### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

yes, I do have.

### Description
I have added the folder "LLM (LANGCHAIN GEN AI)" under Artificial Intelligence folder. This pack consists of 4 projects in it. The readme file has been provided for the clear guidance. 

Fixes #1001 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Any suggestion regarding this contribution is welcomed.

### CODE REVIEW

**Comment by VarsaGupta** [comment]
@Kushal997-das, please check the pull request and let me know if change is required.

**Review by Kushal997-das — CHANGES_REQUESTED** [review]
Sure, here's the revised version of the sentence:

---

@VarsaGupta Things you need to change:

1. Add your project [here](https://github.com/Kushal997-das/Project-Guidance/blob/main/Machine%20Learning%20and%20Data%20Science/README.md).
2. Provide clear, step-by-step instructions in the `README.md` file. Make it simple and easy to understand for the user.
3. Ensure you fetch the updated version of `project-guidance`.

**Comment by VarsaGupta** [comment]
@Kushal997-das , hey, the project is related to AI. Should I still add it in ML and Data Science folder??

**Comment by Kushal997-das** [comment]
> Sure, here's the revised version of the sentence:
> 
> @VarsaGupta Things you need to change:
> 
> 1. Add your project [here](https://github.com/Kushal997-das/Project-Guidance/blob/main/Machine%20Learning%20and%20Data%20Science/README.md).
> 2. Provide clear, step-by-step instructions in the `README.md` file. Make it simple and easy to understand for the user.
> 3. Ensure you fetch the updated version of `project-guidance`.

Please do the required changes

**Comment by Kushal997-das** [comment]
@VarsaGupta Kindly update on this.

**Pull request closed without merging**
